//! Turns `data/names.json` into the two default name lists.
//!
//! Two hundred and fifty names, one per line, were most of `names.rs` — a file
//! whose actual subject is how a townsperson's label is assembled out of a name
//! and a trade, and which read as a phone book. They are `data/names.json` now,
//! eight to a line, and `build.rs` emits the `const`s before the crate compiles.
//!
//! The lists are a *default*: `Data/names.xml` holds 3,632 names and belongs to
//! the operator's own ServUO checkout, not this repository. A pack that wants
//! the whole list registers it and overrides these. Moving them out of the
//! source is a step towards that — the shape a pack ships is a data file, and
//! this is now the same shape.

use std::collections::BTreeMap;
use std::fmt::Write as _;
use std::path::Path;

/// Emits one list. The order is the data's, because the roll indexes into it and
/// a shard's names have to replay: the same seed must pick the same name.
fn list(out: &mut String, ident: &str, doc: &str, names: &[String]) {
    writeln!(out, "/// {doc}").unwrap();
    writeln!(out, "const {ident}: &[&str] = &[").unwrap();
    for name in names {
        writeln!(out, "    {name:?},").unwrap();
    }
    out.push_str("];\n\n");
}

fn main() {
    let out_dir = std::env::var("OUT_DIR").expect("cargo sets OUT_DIR");
    println!("cargo:rerun-if-changed=build.rs");
    println!("cargo:rerun-if-changed=data");

    let path = Path::new("data").join("names.json");
    let text = std::fs::read_to_string(&path).unwrap_or_else(|e| panic!("{}: {e}", path.display()));
    let lists: BTreeMap<String, Vec<String>> =
        serde_json::from_str(&text).unwrap_or_else(|e| panic!("{}: {e}", path.display()));

    let mut out = String::from("// @generated by build.rs from data/names.json.\n\n");
    for (key, ident, doc) in [
        ("male", "MALE_NAMES", "The core's default male personal names."),
        (
            "female",
            "FEMALE_NAMES",
            "The core's default female personal names.",
        ),
    ] {
        let names = lists
            .get(key)
            .unwrap_or_else(|| panic!("names.json has no \"{key}\" list"));
        list(&mut out, ident, doc, names);
    }

    std::fs::write(Path::new(&out_dir).join("names.rs"), out).expect("writing names.rs");
}
