//! DefAlchemy's recipes, as core data.
//!
//! Generated once from ServUO by `tools/gen-craft-tables`, and ordinary source
//! from then on: edit it, do not regenerate it. Skills are in tenths.

use openshard_state::Skill;

use crate::recipe::{CraftRes, CraftSkillReq, Recipe};
use crate::system::{Needs, Text};

/// The gump's left-hand column.
pub const GROUPS: &[Text] = &[
    Text::Cliloc(1116348),
    Text::Cliloc(1116349),
    Text::Cliloc(1116350),
    Text::Cliloc(1116351),
    Text::Cliloc(1116353),
];

const SKILLS_0: &[CraftSkillReq] = &[CraftSkillReq {
    skill: Skill::Alchemy,
    min: -250,
    max: 250,
}];
const RES_0: &[CraftRes] = &[
    CraftRes {
        graphic: 0x0F7A,
        hue: 0x0000,
        amount: 1,
        name: Text::Cliloc(1044353),
        message: Text::Cliloc(1044361),
        from_axis: false,
    },
    CraftRes {
        graphic: 0x0F0E,
        hue: 0x0000,
        amount: 1,
        name: Text::Cliloc(1044529),
        message: Text::Cliloc(500315),
        from_axis: false,
    },
];
const SKILLS_1: &[CraftSkillReq] = &[CraftSkillReq {
    skill: Skill::Alchemy,
    min: 250,
    max: 750,
}];
const RES_1: &[CraftRes] = &[
    CraftRes {
        graphic: 0x0F7A,
        hue: 0x0000,
        amount: 5,
        name: Text::Cliloc(1044353),
        message: Text::Cliloc(1044361),
        from_axis: false,
    },
    CraftRes {
        graphic: 0x0F0E,
        hue: 0x0000,
        amount: 1,
        name: Text::Cliloc(1044529),
        message: Text::Cliloc(500315),
        from_axis: false,
    },
];
const SKILLS_2: &[CraftSkillReq] = &[CraftSkillReq {
    skill: Skill::Alchemy,
    min: -250,
    max: 250,
}];
const RES_2: &[CraftRes] = &[
    CraftRes {
        graphic: 0x0F85,
        hue: 0x0000,
        amount: 1,
        name: Text::Cliloc(1044356),
        message: Text::Cliloc(1044364),
        from_axis: false,
    },
    CraftRes {
        graphic: 0x0F0E,
        hue: 0x0000,
        amount: 1,
        name: Text::Cliloc(1044529),
        message: Text::Cliloc(500315),
        from_axis: false,
    },
];
const SKILLS_3: &[CraftSkillReq] = &[CraftSkillReq {
    skill: Skill::Alchemy,
    min: 150,
    max: 650,
}];
const RES_3: &[CraftRes] = &[
    CraftRes {
        graphic: 0x0F85,
        hue: 0x0000,
        amount: 3,
        name: Text::Cliloc(1044356),
        message: Text::Cliloc(1044364),
        from_axis: false,
    },
    CraftRes {
        graphic: 0x0F0E,
        hue: 0x0000,
        amount: 1,
        name: Text::Cliloc(1044529),
        message: Text::Cliloc(500315),
        from_axis: false,
    },
];
const SKILLS_4: &[CraftSkillReq] = &[CraftSkillReq {
    skill: Skill::Alchemy,
    min: 550,
    max: 1050,
}];
const RES_4: &[CraftRes] = &[
    CraftRes {
        graphic: 0x0F85,
        hue: 0x0000,
        amount: 7,
        name: Text::Cliloc(1044356),
        message: Text::Cliloc(1044364),
        from_axis: false,
    },
    CraftRes {
        graphic: 0x0F0E,
        hue: 0x0000,
        amount: 1,
        name: Text::Cliloc(1044529),
        message: Text::Cliloc(500315),
        from_axis: false,
    },
];
const SKILLS_5: &[CraftSkillReq] = &[CraftSkillReq {
    skill: Skill::Alchemy,
    min: -100,
    max: 400,
}];
const RES_5: &[CraftRes] = &[
    CraftRes {
        graphic: 0x0F84,
        hue: 0x0000,
        amount: 1,
        name: Text::Cliloc(1044355),
        message: Text::Cliloc(1044363),
        from_axis: false,
    },
    CraftRes {
        graphic: 0x0F0E,
        hue: 0x0000,
        amount: 1,
        name: Text::Cliloc(1044529),
        message: Text::Cliloc(500315),
        from_axis: false,
    },
];
const SKILLS_6: &[CraftSkillReq] = &[CraftSkillReq {
    skill: Skill::Alchemy,
    min: 250,
    max: 750,
}];
const RES_6: &[CraftRes] = &[
    CraftRes {
        graphic: 0x0F84,
        hue: 0x0000,
        amount: 3,
        name: Text::Cliloc(1044355),
        message: Text::Cliloc(1044363),
        from_axis: false,
    },
    CraftRes {
        graphic: 0x0F0E,
        hue: 0x0000,
        amount: 1,
        name: Text::Cliloc(1044529),
        message: Text::Cliloc(500315),
        from_axis: false,
    },
];
const SKILLS_7: &[CraftSkillReq] = &[CraftSkillReq {
    skill: Skill::Alchemy,
    min: 650,
    max: 1150,
}];
const RES_7: &[CraftRes] = &[
    CraftRes {
        graphic: 0x0F84,
        hue: 0x0000,
        amount: 6,
        name: Text::Cliloc(1044355),
        message: Text::Cliloc(1044363),
        from_axis: false,
    },
    CraftRes {
        graphic: 0x0F0E,
        hue: 0x0000,
        amount: 1,
        name: Text::Cliloc(1044529),
        message: Text::Cliloc(500315),
        from_axis: false,
    },
];
const SKILLS_8: &[CraftSkillReq] = &[CraftSkillReq {
    skill: Skill::Alchemy,
    min: 150,
    max: 650,
}];
const RES_8: &[CraftRes] = &[
    CraftRes {
        graphic: 0x0F7B,
        hue: 0x0000,
        amount: 1,
        name: Text::Cliloc(1044354),
        message: Text::Cliloc(1044362),
        from_axis: false,
    },
    CraftRes {
        graphic: 0x0F0E,
        hue: 0x0000,
        amount: 1,
        name: Text::Cliloc(1044529),
        message: Text::Cliloc(500315),
        from_axis: false,
    },
];
const SKILLS_9: &[CraftSkillReq] = &[CraftSkillReq {
    skill: Skill::Alchemy,
    min: 350,
    max: 850,
}];
const RES_9: &[CraftRes] = &[
    CraftRes {
        graphic: 0x0F7B,
        hue: 0x0000,
        amount: 3,
        name: Text::Cliloc(1044354),
        message: Text::Cliloc(1044362),
        from_axis: false,
    },
    CraftRes {
        graphic: 0x0F0E,
        hue: 0x0000,
        amount: 1,
        name: Text::Cliloc(1044529),
        message: Text::Cliloc(500315),
        from_axis: false,
    },
];
const SKILLS_10: &[CraftSkillReq] = &[CraftSkillReq {
    skill: Skill::Alchemy,
    min: -250,
    max: 250,
}];
const RES_10: &[CraftRes] = &[
    CraftRes {
        graphic: 0x0F8D,
        hue: 0x0000,
        amount: 1,
        name: Text::Cliloc(1044360),
        message: Text::Cliloc(1044368),
        from_axis: false,
    },
    CraftRes {
        graphic: 0x0F0E,
        hue: 0x0000,
        amount: 1,
        name: Text::Cliloc(1044529),
        message: Text::Cliloc(500315),
        from_axis: false,
    },
];
const SKILLS_11: &[CraftSkillReq] = &[CraftSkillReq {
    skill: Skill::Alchemy,
    min: 250,
    max: 750,
}];
const RES_11: &[CraftRes] = &[
    CraftRes {
        graphic: 0x0F86,
        hue: 0x0000,
        amount: 2,
        name: Text::Cliloc(1044357),
        message: Text::Cliloc(1044365),
        from_axis: false,
    },
    CraftRes {
        graphic: 0x0F0E,
        hue: 0x0000,
        amount: 1,
        name: Text::Cliloc(1044529),
        message: Text::Cliloc(500315),
        from_axis: false,
    },
];
const SKILLS_12: &[CraftSkillReq] = &[CraftSkillReq {
    skill: Skill::Alchemy,
    min: 450,
    max: 950,
}];
const RES_12: &[CraftRes] = &[
    CraftRes {
        graphic: 0x0F86,
        hue: 0x0000,
        amount: 5,
        name: Text::Cliloc(1044357),
        message: Text::Cliloc(1044365),
        from_axis: false,
    },
    CraftRes {
        graphic: 0x0F0E,
        hue: 0x0000,
        amount: 1,
        name: Text::Cliloc(1044529),
        message: Text::Cliloc(500315),
        from_axis: false,
    },
];
const SKILLS_13: &[CraftSkillReq] = &[CraftSkillReq {
    skill: Skill::Alchemy,
    min: -50,
    max: 450,
}];
const RES_13: &[CraftRes] = &[
    CraftRes {
        graphic: 0x0F88,
        hue: 0x0000,
        amount: 1,
        name: Text::Cliloc(1044358),
        message: Text::Cliloc(1044366),
        from_axis: false,
    },
    CraftRes {
        graphic: 0x0F0E,
        hue: 0x0000,
        amount: 1,
        name: Text::Cliloc(1044529),
        message: Text::Cliloc(500315),
        from_axis: false,
    },
];
const SKILLS_14: &[CraftSkillReq] = &[CraftSkillReq {
    skill: Skill::Alchemy,
    min: 150,
    max: 650,
}];
const RES_14: &[CraftRes] = &[
    CraftRes {
        graphic: 0x0F88,
        hue: 0x0000,
        amount: 2,
        name: Text::Cliloc(1044358),
        message: Text::Cliloc(1044366),
        from_axis: false,
    },
    CraftRes {
        graphic: 0x0F0E,
        hue: 0x0000,
        amount: 1,
        name: Text::Cliloc(1044529),
        message: Text::Cliloc(500315),
        from_axis: false,
    },
];
const SKILLS_15: &[CraftSkillReq] = &[CraftSkillReq {
    skill: Skill::Alchemy,
    min: 550,
    max: 1050,
}];
const RES_15: &[CraftRes] = &[
    CraftRes {
        graphic: 0x0F88,
        hue: 0x0000,
        amount: 4,
        name: Text::Cliloc(1044358),
        message: Text::Cliloc(1044366),
        from_axis: false,
    },
    CraftRes {
        graphic: 0x0F0E,
        hue: 0x0000,
        amount: 1,
        name: Text::Cliloc(1044529),
        message: Text::Cliloc(500315),
        from_axis: false,
    },
];
const SKILLS_16: &[CraftSkillReq] = &[CraftSkillReq {
    skill: Skill::Alchemy,
    min: 900,
    max: 1400,
}];
const RES_16: &[CraftRes] = &[
    CraftRes {
        graphic: 0x0F88,
        hue: 0x0000,
        amount: 8,
        name: Text::Cliloc(1044358),
        message: Text::Cliloc(1044366),
        from_axis: false,
    },
    CraftRes {
        graphic: 0x0F0E,
        hue: 0x0000,
        amount: 1,
        name: Text::Cliloc(1044529),
        message: Text::Cliloc(500315),
        from_axis: false,
    },
];
const SKILLS_17: &[CraftSkillReq] = &[CraftSkillReq {
    skill: Skill::Alchemy,
    min: 750,
    max: 1000,
}];
const RES_17: &[CraftRes] = &[
    CraftRes {
        graphic: 0x4005,
        hue: 0x0000,
        amount: 1,
        name: Text::Cliloc(1112291),
        message: Text::Cliloc(1044253),
        from_axis: false,
    },
    CraftRes {
        graphic: 0x0F0E,
        hue: 0x0000,
        amount: 1,
        name: Text::Cliloc(1044529),
        message: Text::Cliloc(500315),
        from_axis: false,
    },
];
const SKILLS_18: &[CraftSkillReq] = &[CraftSkillReq {
    skill: Skill::Alchemy,
    min: 50,
    max: 550,
}];
const RES_18: &[CraftRes] = &[
    CraftRes {
        graphic: 0x0F8C,
        hue: 0x0000,
        amount: 3,
        name: Text::Cliloc(1044359),
        message: Text::Cliloc(1044367),
        from_axis: false,
    },
    CraftRes {
        graphic: 0x0F0E,
        hue: 0x0000,
        amount: 1,
        name: Text::Cliloc(1044529),
        message: Text::Cliloc(500315),
        from_axis: false,
    },
];
const SKILLS_19: &[CraftSkillReq] = &[CraftSkillReq {
    skill: Skill::Alchemy,
    min: 350,
    max: 850,
}];
const RES_19: &[CraftRes] = &[
    CraftRes {
        graphic: 0x0F8C,
        hue: 0x0000,
        amount: 5,
        name: Text::Cliloc(1044359),
        message: Text::Cliloc(1044367),
        from_axis: false,
    },
    CraftRes {
        graphic: 0x0F0E,
        hue: 0x0000,
        amount: 1,
        name: Text::Cliloc(1044529),
        message: Text::Cliloc(500315),
        from_axis: false,
    },
];
const SKILLS_20: &[CraftSkillReq] = &[CraftSkillReq {
    skill: Skill::Alchemy,
    min: 650,
    max: 1150,
}];
const RES_20: &[CraftRes] = &[
    CraftRes {
        graphic: 0x0F8C,
        hue: 0x0000,
        amount: 10,
        name: Text::Cliloc(1044359),
        message: Text::Cliloc(1044367),
        from_axis: false,
    },
    CraftRes {
        graphic: 0x0F0E,
        hue: 0x0000,
        amount: 1,
        name: Text::Cliloc(1044529),
        message: Text::Cliloc(500315),
        from_axis: false,
    },
];
const SKILLS_21: &[CraftSkillReq] = &[CraftSkillReq {
    skill: Skill::Alchemy,
    min: 550,
    max: 1050,
}];
const RES_21: &[CraftRes] = &[
    CraftRes {
        graphic: 0x0F0E,
        hue: 0x0000,
        amount: 1,
        name: Text::Cliloc(1044529),
        message: Text::Cliloc(500315),
        from_axis: false,
    },
    CraftRes {
        graphic: 0x0F8F,
        hue: 0x0000,
        amount: 5,
        name: Text::Cliloc(1023983),
        message: Text::Cliloc(1044253),
        from_axis: false,
    },
];
const SKILLS_22: &[CraftSkillReq] = &[CraftSkillReq {
    skill: Skill::Alchemy,
    min: 700,
    max: 1200,
}];
const RES_22: &[CraftRes] = &[
    CraftRes {
        graphic: 0x0F0E,
        hue: 0x0000,
        amount: 1,
        name: Text::Cliloc(1044529),
        message: Text::Cliloc(500315),
        from_axis: false,
    },
    CraftRes {
        graphic: 0x0F8F,
        hue: 0x0000,
        amount: 10,
        name: Text::Cliloc(1023983),
        message: Text::Cliloc(1044253),
        from_axis: false,
    },
];
const SKILLS_23: &[CraftSkillReq] = &[CraftSkillReq {
    skill: Skill::Alchemy,
    min: 550,
    max: 1050,
}];
const RES_23: &[CraftRes] = &[
    CraftRes {
        graphic: 0x0F0E,
        hue: 0x0000,
        amount: 1,
        name: Text::Cliloc(1044529),
        message: Text::Cliloc(500315),
        from_axis: false,
    },
    CraftRes {
        graphic: 0x0F8A,
        hue: 0x0000,
        amount: 5,
        name: Text::Cliloc(1023978),
        message: Text::Cliloc(1044253),
        from_axis: false,
    },
];
const SKILLS_24: &[CraftSkillReq] = &[CraftSkillReq {
    skill: Skill::Alchemy,
    min: 700,
    max: 1200,
}];
const RES_24: &[CraftRes] = &[
    CraftRes {
        graphic: 0x0F0E,
        hue: 0x0000,
        amount: 1,
        name: Text::Cliloc(1044529),
        message: Text::Cliloc(500315),
        from_axis: false,
    },
    CraftRes {
        graphic: 0x0F8A,
        hue: 0x0000,
        amount: 10,
        name: Text::Cliloc(1023978),
        message: Text::Cliloc(1044253),
        from_axis: false,
    },
];
const SKILLS_25: &[CraftSkillReq] = &[CraftSkillReq {
    skill: Skill::Alchemy,
    min: 900,
    max: 1200,
}];
const RES_25: &[CraftRes] = &[
    CraftRes {
        graphic: 0x09B5,
        hue: 0x0000,
        amount: 1,
        name: Text::Cliloc(1044477),
        message: Text::Cliloc(1044253),
        from_axis: false,
    },
    CraftRes {
        graphic: 0x0F85,
        hue: 0x0000,
        amount: 3,
        name: Text::Cliloc(1044356),
        message: Text::Cliloc(1044364),
        from_axis: false,
    },
];
const SKILLS_26: &[CraftSkillReq] = &[CraftSkillReq {
    skill: Skill::Alchemy,
    min: 750,
    max: 1250,
}];
const RES_26: &[CraftRes] = &[CraftRes {
    graphic: 0x318E,
    hue: 0x0000,
    amount: 4,
    name: Text::Cliloc(1032686),
    message: Text::Cliloc(1044253),
    from_axis: false,
}];
const SKILLS_27: &[CraftSkillReq] = &[CraftSkillReq {
    skill: Skill::Alchemy,
    min: 900,
    max: 1200,
}];
const RES_27: &[CraftRes] = &[
    CraftRes {
        graphic: 0x0F86,
        hue: 0x0000,
        amount: 10,
        name: Text::Cliloc(1015013),
        message: Text::Cliloc(1044253),
        from_axis: false,
    },
    CraftRes {
        graphic: 0x0F8D,
        hue: 0x0000,
        amount: 10,
        name: Text::Cliloc(1015007),
        message: Text::Cliloc(1044253),
        from_axis: false,
    },
    CraftRes {
        graphic: 0x3192,
        hue: 0x0000,
        amount: 5,
        name: Text::Cliloc(1032690),
        message: Text::Cliloc(1044253),
        from_axis: false,
    },
    CraftRes {
        graphic: 0x573B,
        hue: 0x0000,
        amount: 5,
        name: Text::Cliloc(1113351),
        message: Text::Cliloc(1044253),
        from_axis: false,
    },
];

/// Everything this trade can make.
pub const RECIPES: &[Recipe] = &[
    Recipe {
        graphic: 0x0F0B,
        name: Text::Cliloc(1044538),
        group: 0,
        skills: SKILLS_0,
        resources: RES_0,
        amount: 1,
        hue: 0x0000,
        use_all_res: false,
        min_skill_offset: 0,
        markable: false,
        never_exceptional: false,
        always_exceptional: false,
        needs: Needs::none(),
    },
    Recipe {
        graphic: 0x0F0B,
        name: Text::Cliloc(1044539),
        group: 0,
        skills: SKILLS_1,
        resources: RES_1,
        amount: 1,
        hue: 0x0000,
        use_all_res: false,
        min_skill_offset: 0,
        markable: false,
        never_exceptional: false,
        always_exceptional: false,
        needs: Needs::none(),
    },
    Recipe {
        graphic: 0x0F0C,
        name: Text::Cliloc(1044543),
        group: 0,
        skills: SKILLS_2,
        resources: RES_2,
        amount: 1,
        hue: 0x0000,
        use_all_res: false,
        min_skill_offset: 0,
        markable: false,
        never_exceptional: false,
        always_exceptional: false,
        needs: Needs::none(),
    },
    Recipe {
        graphic: 0x0F0C,
        name: Text::Cliloc(1044544),
        group: 0,
        skills: SKILLS_3,
        resources: RES_3,
        amount: 1,
        hue: 0x0000,
        use_all_res: false,
        min_skill_offset: 0,
        markable: false,
        never_exceptional: false,
        always_exceptional: false,
        needs: Needs::none(),
    },
    Recipe {
        graphic: 0x0F0C,
        name: Text::Cliloc(1044545),
        group: 0,
        skills: SKILLS_4,
        resources: RES_4,
        amount: 1,
        hue: 0x0000,
        use_all_res: false,
        min_skill_offset: 0,
        markable: false,
        never_exceptional: false,
        always_exceptional: false,
        needs: Needs::none(),
    },
    Recipe {
        graphic: 0x0F07,
        name: Text::Cliloc(1044552),
        group: 0,
        skills: SKILLS_5,
        resources: RES_5,
        amount: 1,
        hue: 0x0000,
        use_all_res: false,
        min_skill_offset: 0,
        markable: false,
        never_exceptional: false,
        always_exceptional: false,
        needs: Needs::none(),
    },
    Recipe {
        graphic: 0x0F07,
        name: Text::Cliloc(1044553),
        group: 0,
        skills: SKILLS_6,
        resources: RES_6,
        amount: 1,
        hue: 0x0000,
        use_all_res: false,
        min_skill_offset: 0,
        markable: false,
        never_exceptional: false,
        always_exceptional: false,
        needs: Needs::none(),
    },
    Recipe {
        graphic: 0x0F07,
        name: Text::Cliloc(1044554),
        group: 0,
        skills: SKILLS_7,
        resources: RES_7,
        amount: 1,
        hue: 0x0000,
        use_all_res: false,
        min_skill_offset: 0,
        markable: false,
        never_exceptional: false,
        always_exceptional: false,
        needs: Needs::none(),
    },
    Recipe {
        graphic: 0x0F08,
        name: Text::Cliloc(1044540),
        group: 1,
        skills: SKILLS_8,
        resources: RES_8,
        amount: 1,
        hue: 0x0000,
        use_all_res: false,
        min_skill_offset: 0,
        markable: false,
        never_exceptional: false,
        always_exceptional: false,
        needs: Needs::none(),
    },
    Recipe {
        graphic: 0x0F08,
        name: Text::Cliloc(1044541),
        group: 1,
        skills: SKILLS_9,
        resources: RES_9,
        amount: 1,
        hue: 0x0000,
        use_all_res: false,
        min_skill_offset: 0,
        markable: false,
        never_exceptional: false,
        always_exceptional: false,
        needs: Needs::none(),
    },
    Recipe {
        graphic: 0x0F06,
        name: Text::Cliloc(1044542),
        group: 1,
        skills: SKILLS_10,
        resources: RES_10,
        amount: 1,
        hue: 0x0000,
        use_all_res: false,
        min_skill_offset: 0,
        markable: false,
        never_exceptional: false,
        always_exceptional: false,
        needs: Needs::none(),
    },
    Recipe {
        graphic: 0x0F09,
        name: Text::Cliloc(1044546),
        group: 1,
        skills: SKILLS_11,
        resources: RES_11,
        amount: 1,
        hue: 0x0000,
        use_all_res: false,
        min_skill_offset: 0,
        markable: false,
        never_exceptional: false,
        always_exceptional: false,
        needs: Needs::none(),
    },
    Recipe {
        graphic: 0x0F09,
        name: Text::Cliloc(1044547),
        group: 1,
        skills: SKILLS_12,
        resources: RES_12,
        amount: 1,
        hue: 0x0000,
        use_all_res: false,
        min_skill_offset: 0,
        markable: false,
        never_exceptional: false,
        always_exceptional: false,
        needs: Needs::none(),
    },
    Recipe {
        graphic: 0x0F0A,
        name: Text::Cliloc(1044548),
        group: 2,
        skills: SKILLS_13,
        resources: RES_13,
        amount: 1,
        hue: 0x0000,
        use_all_res: false,
        min_skill_offset: 0,
        markable: false,
        never_exceptional: false,
        always_exceptional: false,
        needs: Needs::none(),
    },
    Recipe {
        graphic: 0x0F0A,
        name: Text::Cliloc(1044549),
        group: 2,
        skills: SKILLS_14,
        resources: RES_14,
        amount: 1,
        hue: 0x0000,
        use_all_res: false,
        min_skill_offset: 0,
        markable: false,
        never_exceptional: false,
        always_exceptional: false,
        needs: Needs::none(),
    },
    Recipe {
        graphic: 0x0F0A,
        name: Text::Cliloc(1044550),
        group: 2,
        skills: SKILLS_15,
        resources: RES_15,
        amount: 1,
        hue: 0x0000,
        use_all_res: false,
        min_skill_offset: 0,
        markable: false,
        never_exceptional: false,
        always_exceptional: false,
        needs: Needs::none(),
    },
    Recipe {
        graphic: 0x0F0A,
        name: Text::Cliloc(1044551),
        group: 2,
        skills: SKILLS_16,
        resources: RES_16,
        amount: 1,
        hue: 0x0000,
        use_all_res: false,
        min_skill_offset: 0,
        markable: false,
        never_exceptional: false,
        always_exceptional: false,
        needs: Needs::none(),
    },
    Recipe {
        graphic: 0x1848,
        name: Text::Cliloc(1112292),
        group: 2,
        skills: SKILLS_17,
        resources: RES_17,
        amount: 1,
        hue: 0x0000,
        use_all_res: false,
        min_skill_offset: 0,
        markable: false,
        never_exceptional: false,
        always_exceptional: false,
        needs: Needs::none(),
    },
    Recipe {
        graphic: 0x0F0D,
        name: Text::Cliloc(1044555),
        group: 3,
        skills: SKILLS_18,
        resources: RES_18,
        amount: 1,
        hue: 0x0000,
        use_all_res: false,
        min_skill_offset: 0,
        markable: false,
        never_exceptional: false,
        always_exceptional: false,
        needs: Needs::none(),
    },
    Recipe {
        graphic: 0x0F0D,
        name: Text::Cliloc(1044556),
        group: 3,
        skills: SKILLS_19,
        resources: RES_19,
        amount: 1,
        hue: 0x0000,
        use_all_res: false,
        min_skill_offset: 0,
        markable: false,
        never_exceptional: false,
        always_exceptional: false,
        needs: Needs::none(),
    },
    Recipe {
        graphic: 0x0F0D,
        name: Text::Cliloc(1044557),
        group: 3,
        skills: SKILLS_20,
        resources: RES_20,
        amount: 1,
        hue: 0x0000,
        use_all_res: false,
        min_skill_offset: 0,
        markable: false,
        never_exceptional: false,
        always_exceptional: false,
        needs: Needs::none(),
    },
    Recipe {
        graphic: 0x0F06,
        name: Text::Cliloc(1072096),
        group: 3,
        skills: SKILLS_21,
        resources: RES_21,
        amount: 1,
        hue: 0x0000,
        use_all_res: false,
        min_skill_offset: 0,
        markable: false,
        never_exceptional: false,
        always_exceptional: false,
        needs: Needs::none(),
    },
    Recipe {
        graphic: 0x0F06,
        name: Text::Cliloc(1072099),
        group: 3,
        skills: SKILLS_22,
        resources: RES_22,
        amount: 1,
        hue: 0x0000,
        use_all_res: false,
        min_skill_offset: 0,
        markable: false,
        never_exceptional: false,
        always_exceptional: false,
        needs: Needs::none(),
    },
    Recipe {
        graphic: 0x0F06,
        name: Text::Cliloc(1072106),
        group: 3,
        skills: SKILLS_23,
        resources: RES_23,
        amount: 1,
        hue: 0x0000,
        use_all_res: false,
        min_skill_offset: 0,
        markable: false,
        never_exceptional: false,
        always_exceptional: false,
        needs: Needs::none(),
    },
    Recipe {
        graphic: 0x0F06,
        name: Text::Cliloc(1072109),
        group: 3,
        skills: SKILLS_24,
        resources: RES_24,
        amount: 1,
        hue: 0x0000,
        use_all_res: false,
        min_skill_offset: 0,
        markable: false,
        never_exceptional: false,
        always_exceptional: false,
        needs: Needs::none(),
    },
    Recipe {
        graphic: 0x2808,
        name: Text::Cliloc(1030248),
        group: 4,
        skills: SKILLS_25,
        resources: RES_25,
        amount: 1,
        hue: 0x0000,
        use_all_res: false,
        min_skill_offset: 0,
        markable: false,
        never_exceptional: false,
        always_exceptional: false,
        needs: Needs::none(),
    },
    Recipe {
        graphic: 0x2100,
        name: Text::Cliloc(1072881),
        group: 4,
        skills: SKILLS_26,
        resources: RES_26,
        amount: 1,
        hue: 0x0000,
        use_all_res: false,
        min_skill_offset: 0,
        markable: false,
        never_exceptional: false,
        always_exceptional: false,
        needs: Needs::none(),
    },
    Recipe {
        graphic: 0x4B82,
        name: Text::Cliloc(1153501),
        group: 4,
        skills: SKILLS_27,
        resources: RES_27,
        amount: 1,
        hue: 0x0000,
        use_all_res: false,
        min_skill_offset: 0,
        markable: false,
        never_exceptional: true,
        always_exceptional: false,
        needs: Needs::none(),
    },
];
