//! DefBlacksmithy's recipes, as core data.
//!
//! Generated once from ServUO by `tools/gen-craft-tables`, and ordinary source
//! from then on: edit it, do not regenerate it. Skills are in tenths.

use openshard_protocol::wire::{Graphic, Hue};
use openshard_state::Skill;

use crate::recipe::{CraftRes, CraftSkillReq, Recipe, SubRes, SubResAxis};
use crate::system::{Needs, Text};

/// The gump's left-hand column.
pub const GROUPS: &[Text] = &[
    Text::Cliloc(1111704),
    Text::Cliloc(1011079),
    Text::Cliloc(1011080),
    Text::Cliloc(1011081),
    Text::Cliloc(1011082),
    Text::Cliloc(1011083),
    Text::Cliloc(1011084),
    Text::Cliloc(1011173),
];

const SKILLS_0: &[CraftSkillReq] = &[CraftSkillReq {
    skill: Skill::Blacksmith,
    min: 120,
    max: 620,
}];
const RES_0: &[CraftRes] = &[CraftRes {
    graphic: Graphic(0x1BF2),
    hue: Hue(0x0000),
    amount: 10,
    name: Text::Cliloc(1044036),
    message: Text::Cliloc(1044037),
    from_axis: true,
}];
const SKILLS_1: &[CraftSkillReq] = &[CraftSkillReq {
    skill: Skill::Blacksmith,
    min: 194,
    max: 694,
}];
const RES_1: &[CraftRes] = &[CraftRes {
    graphic: Graphic(0x1BF2),
    hue: Hue(0x0000),
    amount: 16,
    name: Text::Cliloc(1044036),
    message: Text::Cliloc(1044037),
    from_axis: true,
}];
const SKILLS_2: &[CraftSkillReq] = &[CraftSkillReq {
    skill: Skill::Blacksmith,
    min: 169,
    max: 669,
}];
const RES_2: &[CraftRes] = &[CraftRes {
    graphic: Graphic(0x1BF2),
    hue: Hue(0x0000),
    amount: 14,
    name: Text::Cliloc(1044036),
    message: Text::Cliloc(1044037),
    from_axis: true,
}];
const SKILLS_3: &[CraftSkillReq] = &[CraftSkillReq {
    skill: Skill::Blacksmith,
    min: 219,
    max: 719,
}];
const RES_3: &[CraftRes] = &[CraftRes {
    graphic: Graphic(0x1BF2),
    hue: Hue(0x0000),
    amount: 18,
    name: Text::Cliloc(1044036),
    message: Text::Cliloc(1044037),
    from_axis: true,
}];
const SKILLS_4: &[CraftSkillReq] = &[CraftSkillReq {
    skill: Skill::Blacksmith,
    min: 145,
    max: 645,
}];
const RES_4: &[CraftRes] = &[CraftRes {
    graphic: Graphic(0x1BF2),
    hue: Hue(0x0000),
    amount: 10,
    name: Text::Cliloc(1044036),
    message: Text::Cliloc(1044037),
    from_axis: true,
}];
const SKILLS_5: &[CraftSkillReq] = &[CraftSkillReq {
    skill: Skill::Blacksmith,
    min: 367,
    max: 867,
}];
const RES_5: &[CraftRes] = &[CraftRes {
    graphic: Graphic(0x1BF2),
    hue: Hue(0x0000),
    amount: 18,
    name: Text::Cliloc(1044036),
    message: Text::Cliloc(1044037),
    from_axis: true,
}];
const SKILLS_6: &[CraftSkillReq] = &[CraftSkillReq {
    skill: Skill::Blacksmith,
    min: 391,
    max: 891,
}];
const RES_6: &[CraftRes] = &[CraftRes {
    graphic: Graphic(0x1BF2),
    hue: Hue(0x0000),
    amount: 20,
    name: Text::Cliloc(1044036),
    message: Text::Cliloc(1044037),
    from_axis: true,
}];
const SKILLS_7: &[CraftSkillReq] = &[CraftSkillReq {
    skill: Skill::Blacksmith,
    min: 663,
    max: 1163,
}];
const RES_7: &[CraftRes] = &[CraftRes {
    graphic: Graphic(0x1BF2),
    hue: Hue(0x0000),
    amount: 18,
    name: Text::Cliloc(1044036),
    message: Text::Cliloc(1044037),
    from_axis: true,
}];
const SKILLS_8: &[CraftSkillReq] = &[CraftSkillReq {
    skill: Skill::Blacksmith,
    min: 589,
    max: 1089,
}];
const RES_8: &[CraftRes] = &[CraftRes {
    graphic: Graphic(0x1BF2),
    hue: Hue(0x0000),
    amount: 12,
    name: Text::Cliloc(1044036),
    message: Text::Cliloc(1044037),
    from_axis: true,
}];
const SKILLS_9: &[CraftSkillReq] = &[CraftSkillReq {
    skill: Skill::Blacksmith,
    min: 564,
    max: 1064,
}];
const RES_9: &[CraftRes] = &[CraftRes {
    graphic: Graphic(0x1BF2),
    hue: Hue(0x0000),
    amount: 10,
    name: Text::Cliloc(1044036),
    message: Text::Cliloc(1044037),
    from_axis: true,
}];
const SKILLS_10: &[CraftSkillReq] = &[CraftSkillReq {
    skill: Skill::Blacksmith,
    min: 688,
    max: 1188,
}];
const RES_10: &[CraftRes] = &[CraftRes {
    graphic: Graphic(0x1BF2),
    hue: Hue(0x0000),
    amount: 20,
    name: Text::Cliloc(1044036),
    message: Text::Cliloc(1044037),
    from_axis: true,
}];
const SKILLS_11: &[CraftSkillReq] = &[CraftSkillReq {
    skill: Skill::Blacksmith,
    min: 750,
    max: 1250,
}];
const RES_11: &[CraftRes] = &[CraftRes {
    graphic: Graphic(0x1BF2),
    hue: Hue(0x0000),
    amount: 25,
    name: Text::Cliloc(1044036),
    message: Text::Cliloc(1044037),
    from_axis: true,
}];
const SKILLS_12: &[CraftSkillReq] = &[CraftSkillReq {
    skill: Skill::Blacksmith,
    min: 441,
    max: 941,
}];
const RES_12: &[CraftRes] = &[CraftRes {
    graphic: Graphic(0x1BF2),
    hue: Hue(0x0000),
    amount: 20,
    name: Text::Cliloc(1044036),
    message: Text::Cliloc(1044037),
    from_axis: true,
}];
const SKILLS_13: &[CraftSkillReq] = &[CraftSkillReq {
    skill: Skill::Blacksmith,
    min: 725,
    max: 1225,
}];
const RES_13: &[CraftRes] = &[CraftRes {
    graphic: Graphic(0x1BF2),
    hue: Hue(0x0000),
    amount: 750,
    name: Text::Cliloc(1044036),
    message: Text::Cliloc(1044037),
    from_axis: true,
}];
const SKILLS_14: &[CraftSkillReq] = &[CraftSkillReq {
    skill: Skill::Blacksmith,
    min: 800,
    max: 1300,
}];
const RES_14: &[CraftRes] = &[CraftRes {
    graphic: Graphic(0x1BF2),
    hue: Hue(0x0000),
    amount: 18,
    name: Text::Cliloc(1044036),
    message: Text::Cliloc(1044037),
    from_axis: true,
}];
const SKILLS_15: &[CraftSkillReq] = &[CraftSkillReq {
    skill: Skill::Blacksmith,
    min: 800,
    max: 1300,
}];
const RES_15: &[CraftRes] = &[CraftRes {
    graphic: Graphic(0x1BF2),
    hue: Hue(0x0000),
    amount: 28,
    name: Text::Cliloc(1044036),
    message: Text::Cliloc(1044037),
    from_axis: true,
}];
const SKILLS_16: &[CraftSkillReq] = &[CraftSkillReq {
    skill: Skill::Blacksmith,
    min: 800,
    max: 1300,
}];
const RES_16: &[CraftRes] = &[CraftRes {
    graphic: Graphic(0x1BF2),
    hue: Hue(0x0000),
    amount: 16,
    name: Text::Cliloc(1044036),
    message: Text::Cliloc(1044037),
    from_axis: true,
}];
const SKILLS_17: &[CraftSkillReq] = &[CraftSkillReq {
    skill: Skill::Blacksmith,
    min: 650,
    max: 1150,
}];
const RES_17: &[CraftRes] = &[CraftRes {
    graphic: Graphic(0x1BF2),
    hue: Hue(0x0000),
    amount: 20,
    name: Text::Cliloc(1044036),
    message: Text::Cliloc(1044037),
    from_axis: true,
}];
const SKILLS_18: &[CraftSkillReq] = &[CraftSkillReq {
    skill: Skill::Blacksmith,
    min: 650,
    max: 1150,
}];
const RES_18: &[CraftRes] = &[CraftRes {
    graphic: Graphic(0x1BF2),
    hue: Hue(0x0000),
    amount: 20,
    name: Text::Cliloc(1044036),
    message: Text::Cliloc(1044037),
    from_axis: true,
}];
const SKILLS_19: &[CraftSkillReq] = &[CraftSkillReq {
    skill: Skill::Blacksmith,
    min: 83,
    max: 583,
}];
const RES_19: &[CraftRes] = &[CraftRes {
    graphic: Graphic(0x1BF2),
    hue: Hue(0x0000),
    amount: 15,
    name: Text::Cliloc(1044036),
    message: Text::Cliloc(1044037),
    from_axis: true,
}];
const SKILLS_20: &[CraftSkillReq] = &[CraftSkillReq {
    skill: Skill::Blacksmith,
    min: 379,
    max: 879,
}];
const RES_20: &[CraftRes] = &[CraftRes {
    graphic: Graphic(0x1BF2),
    hue: Hue(0x0000),
    amount: 15,
    name: Text::Cliloc(1044036),
    message: Text::Cliloc(1044037),
    from_axis: true,
}];
const SKILLS_21: &[CraftSkillReq] = &[CraftSkillReq {
    skill: Skill::Blacksmith,
    min: 379,
    max: 879,
}];
const RES_21: &[CraftRes] = &[CraftRes {
    graphic: Graphic(0x1BF2),
    hue: Hue(0x0000),
    amount: 15,
    name: Text::Cliloc(1044036),
    message: Text::Cliloc(1044037),
    from_axis: true,
}];
const SKILLS_22: &[CraftSkillReq] = &[CraftSkillReq {
    skill: Skill::Blacksmith,
    min: 379,
    max: 879,
}];
const RES_22: &[CraftRes] = &[CraftRes {
    graphic: Graphic(0x1BF2),
    hue: Hue(0x0000),
    amount: 15,
    name: Text::Cliloc(1044036),
    message: Text::Cliloc(1044037),
    from_axis: true,
}];
const SKILLS_23: &[CraftSkillReq] = &[CraftSkillReq {
    skill: Skill::Blacksmith,
    min: 626,
    max: 1126,
}];
const RES_23: &[CraftRes] = &[CraftRes {
    graphic: Graphic(0x1BF2),
    hue: Hue(0x0000),
    amount: 15,
    name: Text::Cliloc(1044036),
    message: Text::Cliloc(1044037),
    from_axis: true,
}];
const SKILLS_24: &[CraftSkillReq] = &[CraftSkillReq {
    skill: Skill::Blacksmith,
    min: 300,
    max: 800,
}];
const RES_24: &[CraftRes] = &[CraftRes {
    graphic: Graphic(0x1BF2),
    hue: Hue(0x0000),
    amount: 20,
    name: Text::Cliloc(1044036),
    message: Text::Cliloc(1044037),
    from_axis: true,
}];
const SKILLS_25: &[CraftSkillReq] = &[CraftSkillReq {
    skill: Skill::Blacksmith,
    min: 450,
    max: 950,
}];
const RES_25: &[CraftRes] = &[CraftRes {
    graphic: Graphic(0x1BF2),
    hue: Hue(0x0000),
    amount: 20,
    name: Text::Cliloc(1044036),
    message: Text::Cliloc(1044037),
    from_axis: true,
}];
const SKILLS_26: &[CraftSkillReq] = &[CraftSkillReq {
    skill: Skill::Blacksmith,
    min: 450,
    max: 950,
}];
const RES_26: &[CraftRes] = &[CraftRes {
    graphic: Graphic(0x1BF2),
    hue: Hue(0x0000),
    amount: 20,
    name: Text::Cliloc(1044036),
    message: Text::Cliloc(1044037),
    from_axis: true,
}];
const SKILLS_27: &[CraftSkillReq] = &[CraftSkillReq {
    skill: Skill::Blacksmith,
    min: 450,
    max: 950,
}];
const RES_27: &[CraftRes] = &[CraftRes {
    graphic: Graphic(0x1BF2),
    hue: Hue(0x0000),
    amount: 20,
    name: Text::Cliloc(1044036),
    message: Text::Cliloc(1044037),
    from_axis: true,
}];
const SKILLS_28: &[CraftSkillReq] = &[CraftSkillReq {
    skill: Skill::Blacksmith,
    min: 450,
    max: 950,
}];
const RES_28: &[CraftRes] = &[CraftRes {
    graphic: Graphic(0x1BF2),
    hue: Hue(0x0000),
    amount: 20,
    name: Text::Cliloc(1044036),
    message: Text::Cliloc(1044037),
    from_axis: true,
}];
const SKILLS_29: &[CraftSkillReq] = &[CraftSkillReq {
    skill: Skill::Blacksmith,
    min: 900,
    max: 1400,
}];
const RES_29: &[CraftRes] = &[CraftRes {
    graphic: Graphic(0x1BF2),
    hue: Hue(0x0000),
    amount: 25,
    name: Text::Cliloc(1044036),
    message: Text::Cliloc(1044037),
    from_axis: true,
}];
const SKILLS_30: &[CraftSkillReq] = &[CraftSkillReq {
    skill: Skill::Blacksmith,
    min: 900,
    max: 1400,
}];
const RES_30: &[CraftRes] = &[CraftRes {
    graphic: Graphic(0x1BF2),
    hue: Hue(0x0000),
    amount: 25,
    name: Text::Cliloc(1044036),
    message: Text::Cliloc(1044037),
    from_axis: true,
}];
const SKILLS_31: &[CraftSkillReq] = &[CraftSkillReq {
    skill: Skill::Blacksmith,
    min: 900,
    max: 1400,
}];
const RES_31: &[CraftRes] = &[CraftRes {
    graphic: Graphic(0x1BF2),
    hue: Hue(0x0000),
    amount: 25,
    name: Text::Cliloc(1044036),
    message: Text::Cliloc(1044037),
    from_axis: true,
}];
const SKILLS_32: &[CraftSkillReq] = &[CraftSkillReq {
    skill: Skill::Blacksmith,
    min: 621,
    max: 1121,
}];
const RES_32: &[CraftRes] = &[CraftRes {
    graphic: Graphic(0x1BF2),
    hue: Hue(0x0000),
    amount: 6,
    name: Text::Cliloc(1044036),
    message: Text::Cliloc(1044037),
    from_axis: true,
}];
const SKILLS_33: &[CraftSkillReq] = &[CraftSkillReq {
    skill: Skill::Blacksmith,
    min: 700,
    max: 1200,
}];
const RES_33: &[CraftRes] = &[CraftRes {
    graphic: Graphic(0x1BF2),
    hue: Hue(0x0000),
    amount: 6,
    name: Text::Cliloc(1044036),
    message: Text::Cliloc(1044037),
    from_axis: true,
}];
const SKILLS_34: &[CraftSkillReq] = &[CraftSkillReq {
    skill: Skill::Blacksmith,
    min: 750,
    max: 1250,
}];
const RES_34: &[CraftRes] = &[
    CraftRes {
        graphic: Graphic(0x1BF2),
        hue: Hue(0x0000),
        amount: 6,
        name: Text::Cliloc(1044036),
        message: Text::Cliloc(1044037),
        from_axis: true,
    },
    CraftRes {
        graphic: Graphic(0x0F18),
        hue: Hue(0x0000),
        amount: 1,
        name: Text::Cliloc(1044237),
        message: Text::Cliloc(1044240),
        from_axis: false,
    },
    CraftRes {
        graphic: Graphic(0x0F16),
        hue: Hue(0x0000),
        amount: 1,
        name: Text::Cliloc(1044236),
        message: Text::Cliloc(1044240),
        from_axis: false,
    },
    CraftRes {
        graphic: Graphic(0x3198),
        hue: Hue(0x0000),
        amount: 1,
        name: Text::Cliloc(1032696),
        message: Text::Cliloc(1044240),
        from_axis: false,
    },
];
const SKILLS_35: &[CraftSkillReq] = &[CraftSkillReq {
    skill: Skill::Blacksmith,
    min: -250,
    max: 250,
}];
const RES_35: &[CraftRes] = &[CraftRes {
    graphic: Graphic(0x1BF2),
    hue: Hue(0x0000),
    amount: 10,
    name: Text::Cliloc(1044036),
    message: Text::Cliloc(1044037),
    from_axis: true,
}];
const SKILLS_36: &[CraftSkillReq] = &[CraftSkillReq {
    skill: Skill::Blacksmith,
    min: -152,
    max: 348,
}];
const RES_36: &[CraftRes] = &[CraftRes {
    graphic: Graphic(0x1BF2),
    hue: Hue(0x0000),
    amount: 12,
    name: Text::Cliloc(1044036),
    message: Text::Cliloc(1044037),
    from_axis: true,
}];
const SKILLS_37: &[CraftSkillReq] = &[CraftSkillReq {
    skill: Skill::Blacksmith,
    min: 243,
    max: 743,
}];
const RES_37: &[CraftRes] = &[CraftRes {
    graphic: Graphic(0x1BF2),
    hue: Hue(0x0000),
    amount: 18,
    name: Text::Cliloc(1044036),
    message: Text::Cliloc(1044037),
    from_axis: true,
}];
const SKILLS_38: &[CraftSkillReq] = &[CraftSkillReq {
    skill: Skill::Blacksmith,
    min: -102,
    max: 398,
}];
const RES_38: &[CraftRes] = &[CraftRes {
    graphic: Graphic(0x1BF2),
    hue: Hue(0x0000),
    amount: 14,
    name: Text::Cliloc(1044036),
    message: Text::Cliloc(1044037),
    from_axis: true,
}];
const SKILLS_39: &[CraftSkillReq] = &[CraftSkillReq {
    skill: Skill::Blacksmith,
    min: 46,
    max: 546,
}];
const RES_39: &[CraftRes] = &[CraftRes {
    graphic: Graphic(0x1BF2),
    hue: Hue(0x0000),
    amount: 16,
    name: Text::Cliloc(1044036),
    message: Text::Cliloc(1044037),
    from_axis: true,
}];
const SKILLS_40: &[CraftSkillReq] = &[CraftSkillReq {
    skill: Skill::Blacksmith,
    min: -152,
    max: 348,
}];
const RES_40: &[CraftRes] = &[CraftRes {
    graphic: Graphic(0x1BF2),
    hue: Hue(0x0000),
    amount: 8,
    name: Text::Cliloc(1044036),
    message: Text::Cliloc(1044037),
    from_axis: true,
}];
const SKILLS_41: &[CraftSkillReq] = &[CraftSkillReq {
    skill: Skill::Blacksmith,
    min: 850,
    max: 1350,
}];
const RES_41: &[CraftRes] = &[CraftRes {
    graphic: Graphic(0x1BF2),
    hue: Hue(0x0000),
    amount: 25,
    name: Text::Cliloc(1044036),
    message: Text::Cliloc(1044037),
    from_axis: true,
}];
const SKILLS_42: &[CraftSkillReq] = &[CraftSkillReq {
    skill: Skill::Blacksmith,
    min: 850,
    max: 1350,
}];
const RES_42: &[CraftRes] = &[CraftRes {
    graphic: Graphic(0x1BF2),
    hue: Hue(0x0000),
    amount: 25,
    name: Text::Cliloc(1044036),
    message: Text::Cliloc(1044037),
    from_axis: true,
}];
const SKILLS_43: &[CraftSkillReq] = &[CraftSkillReq {
    skill: Skill::Blacksmith,
    min: 330,
    max: 830,
}];
const RES_43: &[CraftRes] = &[CraftRes {
    graphic: Graphic(0x1BF2),
    hue: Hue(0x0000),
    amount: 10,
    name: Text::Cliloc(1044036),
    message: Text::Cliloc(1044037),
    from_axis: true,
}];
const SKILLS_44: &[CraftSkillReq] = &[CraftSkillReq {
    skill: Skill::Blacksmith,
    min: 354,
    max: 854,
}];
const RES_44: &[CraftRes] = &[CraftRes {
    graphic: Graphic(0x1BF2),
    hue: Hue(0x0000),
    amount: 10,
    name: Text::Cliloc(1044036),
    message: Text::Cliloc(1044037),
    from_axis: true,
}];
const SKILLS_45: &[CraftSkillReq] = &[CraftSkillReq {
    skill: Skill::Blacksmith,
    min: 450,
    max: 950,
}];
const RES_45: &[CraftRes] = &[CraftRes {
    graphic: Graphic(0x1BF2),
    hue: Hue(0x0000),
    amount: 14,
    name: Text::Cliloc(1044036),
    message: Text::Cliloc(1044037),
    from_axis: true,
}];
const SKILLS_46: &[CraftSkillReq] = &[CraftSkillReq {
    skill: Skill::Blacksmith,
    min: 243,
    max: 743,
}];
const RES_46: &[CraftRes] = &[CraftRes {
    graphic: Graphic(0x1BF2),
    hue: Hue(0x0000),
    amount: 8,
    name: Text::Cliloc(1044036),
    message: Text::Cliloc(1044037),
    from_axis: true,
}];
const SKILLS_47: &[CraftSkillReq] = &[CraftSkillReq {
    skill: Skill::Blacksmith,
    min: -4,
    max: 496,
}];
const RES_47: &[CraftRes] = &[CraftRes {
    graphic: Graphic(0x1BF2),
    hue: Hue(0x0000),
    amount: 3,
    name: Text::Cliloc(1044036),
    message: Text::Cliloc(1044037),
    from_axis: true,
}];
const SKILLS_48: &[CraftSkillReq] = &[CraftSkillReq {
    skill: Skill::Blacksmith,
    min: 441,
    max: 941,
}];
const RES_48: &[CraftRes] = &[CraftRes {
    graphic: Graphic(0x1BF2),
    hue: Hue(0x0000),
    amount: 8,
    name: Text::Cliloc(1044036),
    message: Text::Cliloc(1044037),
    from_axis: true,
}];
const SKILLS_49: &[CraftSkillReq] = &[CraftSkillReq {
    skill: Skill::Blacksmith,
    min: 367,
    max: 867,
}];
const RES_49: &[CraftRes] = &[CraftRes {
    graphic: Graphic(0x1BF2),
    hue: Hue(0x0000),
    amount: 8,
    name: Text::Cliloc(1044036),
    message: Text::Cliloc(1044037),
    from_axis: true,
}];
const SKILLS_50: &[CraftSkillReq] = &[CraftSkillReq {
    skill: Skill::Blacksmith,
    min: 280,
    max: 780,
}];
const RES_50: &[CraftRes] = &[CraftRes {
    graphic: Graphic(0x1BF2),
    hue: Hue(0x0000),
    amount: 12,
    name: Text::Cliloc(1044036),
    message: Text::Cliloc(1044037),
    from_axis: true,
}];
const SKILLS_51: &[CraftSkillReq] = &[CraftSkillReq {
    skill: Skill::Blacksmith,
    min: 317,
    max: 817,
}];
const RES_51: &[CraftRes] = &[CraftRes {
    graphic: Graphic(0x1BF2),
    hue: Hue(0x0000),
    amount: 10,
    name: Text::Cliloc(1044036),
    message: Text::Cliloc(1044037),
    from_axis: true,
}];
const SKILLS_52: &[CraftSkillReq] = &[CraftSkillReq {
    skill: Skill::Blacksmith,
    min: 243,
    max: 743,
}];
const RES_52: &[CraftRes] = &[CraftRes {
    graphic: Graphic(0x1BF2),
    hue: Hue(0x0000),
    amount: 14,
    name: Text::Cliloc(1044036),
    message: Text::Cliloc(1044037),
    from_axis: true,
}];
const SKILLS_53: &[CraftSkillReq] = &[CraftSkillReq {
    skill: Skill::Blacksmith,
    min: 750,
    max: 1250,
}];
const RES_53: &[CraftRes] = &[CraftRes {
    graphic: Graphic(0x1BF2),
    hue: Hue(0x0000),
    amount: 18,
    name: Text::Cliloc(1044036),
    message: Text::Cliloc(1044037),
    from_axis: true,
}];
const SKILLS_54: &[CraftSkillReq] = &[CraftSkillReq {
    skill: Skill::Blacksmith,
    min: 500,
    max: 1000,
}];
const RES_54: &[CraftRes] = &[CraftRes {
    graphic: Graphic(0x1BF2),
    hue: Hue(0x0000),
    amount: 8,
    name: Text::Cliloc(1044036),
    message: Text::Cliloc(1044037),
    from_axis: true,
}];
const SKILLS_55: &[CraftSkillReq] = &[CraftSkillReq {
    skill: Skill::Blacksmith,
    min: 800,
    max: 1300,
}];
const RES_55: &[CraftRes] = &[CraftRes {
    graphic: Graphic(0x1BF2),
    hue: Hue(0x0000),
    amount: 25,
    name: Text::Cliloc(1044036),
    message: Text::Cliloc(1044037),
    from_axis: true,
}];
const SKILLS_56: &[CraftSkillReq] = &[CraftSkillReq {
    skill: Skill::Blacksmith,
    min: 600,
    max: 1100,
}];
const RES_56: &[CraftRes] = &[CraftRes {
    graphic: Graphic(0x1BF2),
    hue: Hue(0x0000),
    amount: 15,
    name: Text::Cliloc(1044036),
    message: Text::Cliloc(1044037),
    from_axis: true,
}];
const SKILLS_57: &[CraftSkillReq] = &[CraftSkillReq {
    skill: Skill::Blacksmith,
    min: 550,
    max: 1050,
}];
const RES_57: &[CraftRes] = &[CraftRes {
    graphic: Graphic(0x1BF2),
    hue: Hue(0x0000),
    amount: 12,
    name: Text::Cliloc(1044036),
    message: Text::Cliloc(1044037),
    from_axis: true,
}];
const SKILLS_58: &[CraftSkillReq] = &[CraftSkillReq {
    skill: Skill::Blacksmith,
    min: 450,
    max: 950,
}];
const RES_58: &[CraftRes] = &[CraftRes {
    graphic: Graphic(0x1BF2),
    hue: Hue(0x0000),
    amount: 5,
    name: Text::Cliloc(1044036),
    message: Text::Cliloc(1044037),
    from_axis: true,
}];
const SKILLS_59: &[CraftSkillReq] = &[CraftSkillReq {
    skill: Skill::Blacksmith,
    min: 400,
    max: 900,
}];
const RES_59: &[CraftRes] = &[CraftRes {
    graphic: Graphic(0x1BF2),
    hue: Hue(0x0000),
    amount: 14,
    name: Text::Cliloc(1044036),
    message: Text::Cliloc(1044037),
    from_axis: true,
}];
const SKILLS_60: &[CraftSkillReq] = &[CraftSkillReq {
    skill: Skill::Blacksmith,
    min: 500,
    max: 1000,
}];
const RES_60: &[CraftRes] = &[CraftRes {
    graphic: Graphic(0x1BF2),
    hue: Hue(0x0000),
    amount: 12,
    name: Text::Cliloc(1044036),
    message: Text::Cliloc(1044037),
    from_axis: true,
}];
const SKILLS_61: &[CraftSkillReq] = &[CraftSkillReq {
    skill: Skill::Blacksmith,
    min: 750,
    max: 1250,
}];
const RES_61: &[CraftRes] = &[CraftRes {
    graphic: Graphic(0x1BF2),
    hue: Hue(0x0000),
    amount: 15,
    name: Text::Cliloc(1044036),
    message: Text::Cliloc(1044037),
    from_axis: true,
}];
const SKILLS_62: &[CraftSkillReq] = &[CraftSkillReq {
    skill: Skill::Blacksmith,
    min: 700,
    max: 1200,
}];
const RES_62: &[CraftRes] = &[CraftRes {
    graphic: Graphic(0x1BF2),
    hue: Hue(0x0000),
    amount: 18,
    name: Text::Cliloc(1044036),
    message: Text::Cliloc(1044037),
    from_axis: true,
}];
const SKILLS_63: &[CraftSkillReq] = &[CraftSkillReq {
    skill: Skill::Blacksmith,
    min: 700,
    max: 1200,
}];
const RES_63: &[CraftRes] = &[CraftRes {
    graphic: Graphic(0x1BF2),
    hue: Hue(0x0000),
    amount: 14,
    name: Text::Cliloc(1044036),
    message: Text::Cliloc(1044037),
    from_axis: true,
}];
const SKILLS_64: &[CraftSkillReq] = &[CraftSkillReq {
    skill: Skill::Blacksmith,
    min: 700,
    max: 1200,
}];
const RES_64: &[CraftRes] = &[CraftRes {
    graphic: Graphic(0x1BF2),
    hue: Hue(0x0000),
    amount: 9,
    name: Text::Cliloc(1044036),
    message: Text::Cliloc(1044037),
    from_axis: true,
}];
const SKILLS_65: &[CraftSkillReq] = &[CraftSkillReq {
    skill: Skill::Blacksmith,
    min: 700,
    max: 1200,
}];
const RES_65: &[CraftRes] = &[CraftRes {
    graphic: Graphic(0x1BF2),
    hue: Hue(0x0000),
    amount: 12,
    name: Text::Cliloc(1044036),
    message: Text::Cliloc(1044037),
    from_axis: true,
}];
const SKILLS_66: &[CraftSkillReq] = &[CraftSkillReq {
    skill: Skill::Blacksmith,
    min: 700,
    max: 1200,
}];
const RES_66: &[CraftRes] = &[CraftRes {
    graphic: Graphic(0x1BF2),
    hue: Hue(0x0000),
    amount: 15,
    name: Text::Cliloc(1044036),
    message: Text::Cliloc(1044037),
    from_axis: true,
}];
const SKILLS_67: &[CraftSkillReq] = &[CraftSkillReq {
    skill: Skill::Blacksmith,
    min: 700,
    max: 1200,
}];
const RES_67: &[CraftRes] = &[CraftRes {
    graphic: Graphic(0x1BF2),
    hue: Hue(0x0000),
    amount: 14,
    name: Text::Cliloc(1044036),
    message: Text::Cliloc(1044037),
    from_axis: true,
}];
const SKILLS_68: &[CraftSkillReq] = &[CraftSkillReq {
    skill: Skill::Blacksmith,
    min: 342,
    max: 842,
}];
const RES_68: &[CraftRes] = &[CraftRes {
    graphic: Graphic(0x1BF2),
    hue: Hue(0x0000),
    amount: 14,
    name: Text::Cliloc(1044036),
    message: Text::Cliloc(1044037),
    from_axis: true,
}];
const SKILLS_69: &[CraftSkillReq] = &[CraftSkillReq {
    skill: Skill::Blacksmith,
    min: 305,
    max: 805,
}];
const RES_69: &[CraftRes] = &[CraftRes {
    graphic: Graphic(0x1BF2),
    hue: Hue(0x0000),
    amount: 14,
    name: Text::Cliloc(1044036),
    message: Text::Cliloc(1044037),
    from_axis: true,
}];
const SKILLS_70: &[CraftSkillReq] = &[CraftSkillReq {
    skill: Skill::Blacksmith,
    min: 293,
    max: 793,
}];
const RES_70: &[CraftRes] = &[CraftRes {
    graphic: Graphic(0x1BF2),
    hue: Hue(0x0000),
    amount: 12,
    name: Text::Cliloc(1044036),
    message: Text::Cliloc(1044037),
    from_axis: true,
}];
const SKILLS_71: &[CraftSkillReq] = &[CraftSkillReq {
    skill: Skill::Blacksmith,
    min: 342,
    max: 842,
}];
const RES_71: &[CraftRes] = &[CraftRes {
    graphic: Graphic(0x1BF2),
    hue: Hue(0x0000),
    amount: 14,
    name: Text::Cliloc(1044036),
    message: Text::Cliloc(1044037),
    from_axis: true,
}];
const SKILLS_72: &[CraftSkillReq] = &[CraftSkillReq {
    skill: Skill::Blacksmith,
    min: 280,
    max: 780,
}];
const RES_72: &[CraftRes] = &[CraftRes {
    graphic: Graphic(0x1BF2),
    hue: Hue(0x0000),
    amount: 12,
    name: Text::Cliloc(1044036),
    message: Text::Cliloc(1044037),
    from_axis: true,
}];
const SKILLS_73: &[CraftSkillReq] = &[CraftSkillReq {
    skill: Skill::Blacksmith,
    min: 330,
    max: 830,
}];
const RES_73: &[CraftRes] = &[CraftRes {
    graphic: Graphic(0x1BF2),
    hue: Hue(0x0000),
    amount: 16,
    name: Text::Cliloc(1044036),
    message: Text::Cliloc(1044037),
    from_axis: true,
}];
const SKILLS_74: &[CraftSkillReq] = &[CraftSkillReq {
    skill: Skill::Blacksmith,
    min: 391,
    max: 891,
}];
const RES_74: &[CraftRes] = &[CraftRes {
    graphic: Graphic(0x1BF2),
    hue: Hue(0x0000),
    amount: 16,
    name: Text::Cliloc(1044036),
    message: Text::Cliloc(1044037),
    from_axis: true,
}];
const SKILLS_75: &[CraftSkillReq] = &[CraftSkillReq {
    skill: Skill::Blacksmith,
    min: 700,
    max: 1200,
}];
const RES_75: &[CraftRes] = &[CraftRes {
    graphic: Graphic(0x1BF2),
    hue: Hue(0x0000),
    amount: 18,
    name: Text::Cliloc(1044036),
    message: Text::Cliloc(1044037),
    from_axis: true,
}];
const SKILLS_76: &[CraftSkillReq] = &[CraftSkillReq {
    skill: Skill::Blacksmith,
    min: 317,
    max: 817,
}];
const RES_76: &[CraftRes] = &[CraftRes {
    graphic: Graphic(0x1BF2),
    hue: Hue(0x0000),
    amount: 18,
    name: Text::Cliloc(1044036),
    message: Text::Cliloc(1044037),
    from_axis: true,
}];
const SKILLS_77: &[CraftSkillReq] = &[CraftSkillReq {
    skill: Skill::Blacksmith,
    min: 400,
    max: 900,
}];
const RES_77: &[CraftRes] = &[CraftRes {
    graphic: Graphic(0x1BF2),
    hue: Hue(0x0000),
    amount: 12,
    name: Text::Cliloc(1044036),
    message: Text::Cliloc(1044037),
    from_axis: true,
}];
const SKILLS_78: &[CraftSkillReq] = &[CraftSkillReq {
    skill: Skill::Blacksmith,
    min: 450,
    max: 950,
}];
const RES_78: &[CraftRes] = &[CraftRes {
    graphic: Graphic(0x1BF2),
    hue: Hue(0x0000),
    amount: 16,
    name: Text::Cliloc(1044036),
    message: Text::Cliloc(1044037),
    from_axis: true,
}];
const SKILLS_79: &[CraftSkillReq] = &[CraftSkillReq {
    skill: Skill::Blacksmith,
    min: 391,
    max: 891,
}];
const RES_79: &[CraftRes] = &[CraftRes {
    graphic: Graphic(0x1BF2),
    hue: Hue(0x0000),
    amount: 20,
    name: Text::Cliloc(1044036),
    message: Text::Cliloc(1044037),
    from_axis: true,
}];
const SKILLS_80: &[CraftSkillReq] = &[CraftSkillReq {
    skill: Skill::Blacksmith,
    min: 480,
    max: 980,
}];
const RES_80: &[CraftRes] = &[CraftRes {
    graphic: Graphic(0x1BF2),
    hue: Hue(0x0000),
    amount: 20,
    name: Text::Cliloc(1044036),
    message: Text::Cliloc(1044037),
    from_axis: true,
}];
const SKILLS_81: &[CraftSkillReq] = &[CraftSkillReq {
    skill: Skill::Blacksmith,
    min: 470,
    max: 970,
}];
const RES_81: &[CraftRes] = &[CraftRes {
    graphic: Graphic(0x1BF2),
    hue: Hue(0x0000),
    amount: 12,
    name: Text::Cliloc(1044036),
    message: Text::Cliloc(1044037),
    from_axis: true,
}];
const SKILLS_82: &[CraftSkillReq] = &[CraftSkillReq {
    skill: Skill::Blacksmith,
    min: 453,
    max: 953,
}];
const RES_82: &[CraftRes] = &[CraftRes {
    graphic: Graphic(0x1BF2),
    hue: Hue(0x0000),
    amount: 6,
    name: Text::Cliloc(1044036),
    message: Text::Cliloc(1044037),
    from_axis: true,
}];
const SKILLS_83: &[CraftSkillReq] = &[CraftSkillReq {
    skill: Skill::Blacksmith,
    min: 390,
    max: 890,
}];
const RES_83: &[CraftRes] = &[CraftRes {
    graphic: Graphic(0x1BF2),
    hue: Hue(0x0000),
    amount: 14,
    name: Text::Cliloc(1044036),
    message: Text::Cliloc(1044037),
    from_axis: true,
}];
const SKILLS_84: &[CraftSkillReq] = &[CraftSkillReq {
    skill: Skill::Blacksmith,
    min: 490,
    max: 990,
}];
const RES_84: &[CraftRes] = &[CraftRes {
    graphic: Graphic(0x1BF2),
    hue: Hue(0x0000),
    amount: 12,
    name: Text::Cliloc(1044036),
    message: Text::Cliloc(1044037),
    from_axis: true,
}];
const SKILLS_85: &[CraftSkillReq] = &[CraftSkillReq {
    skill: Skill::Blacksmith,
    min: 429,
    max: 929,
}];
const RES_85: &[CraftRes] = &[CraftRes {
    graphic: Graphic(0x1BF2),
    hue: Hue(0x0000),
    amount: 12,
    name: Text::Cliloc(1044036),
    message: Text::Cliloc(1044037),
    from_axis: true,
}];
const SKILLS_86: &[CraftSkillReq] = &[CraftSkillReq {
    skill: Skill::Blacksmith,
    min: 342,
    max: 842,
}];
const RES_86: &[CraftRes] = &[CraftRes {
    graphic: Graphic(0x1BF2),
    hue: Hue(0x0000),
    amount: 16,
    name: Text::Cliloc(1044036),
    message: Text::Cliloc(1044037),
    from_axis: true,
}];
const SKILLS_87: &[CraftSkillReq] = &[CraftSkillReq {
    skill: Skill::Blacksmith,
    min: 145,
    max: 645,
}];
const RES_87: &[CraftRes] = &[CraftRes {
    graphic: Graphic(0x1BF2),
    hue: Hue(0x0000),
    amount: 6,
    name: Text::Cliloc(1044036),
    message: Text::Cliloc(1044037),
    from_axis: true,
}];
const SKILLS_88: &[CraftSkillReq] = &[CraftSkillReq {
    skill: Skill::Blacksmith,
    min: 194,
    max: 694,
}];
const RES_88: &[CraftRes] = &[CraftRes {
    graphic: Graphic(0x1BF2),
    hue: Hue(0x0000),
    amount: 10,
    name: Text::Cliloc(1044036),
    message: Text::Cliloc(1044037),
    from_axis: true,
}];
const SKILLS_89: &[CraftSkillReq] = &[CraftSkillReq {
    skill: Skill::Blacksmith,
    min: 214,
    max: 714,
}];
const RES_89: &[CraftRes] = &[CraftRes {
    graphic: Graphic(0x1BF2),
    hue: Hue(0x0000),
    amount: 10,
    name: Text::Cliloc(1044036),
    message: Text::Cliloc(1044037),
    from_axis: true,
}];
const SKILLS_90: &[CraftSkillReq] = &[CraftSkillReq {
    skill: Skill::Blacksmith,
    min: 280,
    max: 780,
}];
const RES_90: &[CraftRes] = &[CraftRes {
    graphic: Graphic(0x1BF2),
    hue: Hue(0x0000),
    amount: 14,
    name: Text::Cliloc(1044036),
    message: Text::Cliloc(1044037),
    from_axis: true,
}];
const SKILLS_91: &[CraftSkillReq] = &[CraftSkillReq {
    skill: Skill::Blacksmith,
    min: 342,
    max: 842,
}];
const RES_91: &[CraftRes] = &[CraftRes {
    graphic: Graphic(0x1BF2),
    hue: Hue(0x0000),
    amount: 16,
    name: Text::Cliloc(1044036),
    message: Text::Cliloc(1044037),
    from_axis: true,
}];
const SKILLS_92: &[CraftSkillReq] = &[
    CraftSkillReq {
        skill: Skill::Blacksmith,
        min: 850,
        max: 1350,
    },
    CraftSkillReq {
        skill: Skill::Tailoring,
        min: 500,
        max: 550,
    },
];
const RES_92: &[CraftRes] = &[
    CraftRes {
        graphic: Graphic(0x1BF2),
        hue: Hue(0x0000),
        amount: 16,
        name: Text::Cliloc(1044036),
        message: Text::Cliloc(1044037),
        from_axis: true,
    },
    CraftRes {
        graphic: Graphic(0x1766),
        hue: Hue(0x0000),
        amount: 10,
        name: Text::Cliloc(1044286),
        message: Text::Cliloc(1044287),
        from_axis: false,
    },
];
const SKILLS_93: &[CraftSkillReq] = &[CraftSkillReq {
    skill: Skill::Blacksmith,
    min: 700,
    max: 1200,
}];
const RES_93: &[CraftRes] = &[CraftRes {
    graphic: Graphic(0x1BF2),
    hue: Hue(0x0000),
    amount: 20,
    name: Text::Cliloc(1044036),
    message: Text::Cliloc(1044037),
    from_axis: true,
}];
const SKILLS_94: &[CraftSkillReq] = &[CraftSkillReq {
    skill: Skill::Blacksmith,
    min: 850,
    max: 1000,
}];
const RES_94: &[CraftRes] = &[CraftRes {
    graphic: Graphic(0x1BF2),
    hue: Hue(0x0000),
    amount: 25,
    name: Text::Cliloc(1044036),
    message: Text::Cliloc(1044253),
    from_axis: true,
}];

/// Everything this trade can make.
pub const RECIPES: &[Recipe] = &[
    Recipe {
        graphic: Graphic(0x13EB),
        name: Text::Cliloc(1025099),
        group: 0,
        skills: SKILLS_0,
        resources: RES_0,
        amount: 1,
        hue: Hue(0x0000),
        use_all_res: false,
        min_skill_offset: 0,
        markable: true,
        never_exceptional: false,
        always_exceptional: false,
        needs: Needs::none(),
    },
    Recipe {
        graphic: Graphic(0x13F0),
        name: Text::Cliloc(1025104),
        group: 0,
        skills: SKILLS_1,
        resources: RES_1,
        amount: 1,
        hue: Hue(0x0000),
        use_all_res: false,
        min_skill_offset: 0,
        markable: true,
        never_exceptional: false,
        always_exceptional: false,
        needs: Needs::none(),
    },
    Recipe {
        graphic: Graphic(0x13EE),
        name: Text::Cliloc(1025103),
        group: 0,
        skills: SKILLS_2,
        resources: RES_2,
        amount: 1,
        hue: Hue(0x0000),
        use_all_res: false,
        min_skill_offset: 0,
        markable: true,
        never_exceptional: false,
        always_exceptional: false,
        needs: Needs::none(),
    },
    Recipe {
        graphic: Graphic(0x13EC),
        name: Text::Cliloc(1025100),
        group: 0,
        skills: SKILLS_3,
        resources: RES_3,
        amount: 1,
        hue: Hue(0x0000),
        use_all_res: false,
        min_skill_offset: 0,
        markable: true,
        never_exceptional: false,
        always_exceptional: false,
        needs: Needs::none(),
    },
    Recipe {
        graphic: Graphic(0x13BB),
        name: Text::Cliloc(1025051),
        group: 0,
        skills: SKILLS_4,
        resources: RES_4,
        amount: 1,
        hue: Hue(0x0000),
        use_all_res: false,
        min_skill_offset: 0,
        markable: true,
        never_exceptional: false,
        always_exceptional: false,
        needs: Needs::none(),
    },
    Recipe {
        graphic: Graphic(0x13BE),
        name: Text::Cliloc(1025054),
        group: 0,
        skills: SKILLS_5,
        resources: RES_5,
        amount: 1,
        hue: Hue(0x0000),
        use_all_res: false,
        min_skill_offset: 0,
        markable: true,
        never_exceptional: false,
        always_exceptional: false,
        needs: Needs::none(),
    },
    Recipe {
        graphic: Graphic(0x13BF),
        name: Text::Cliloc(1025055),
        group: 0,
        skills: SKILLS_6,
        resources: RES_6,
        amount: 1,
        hue: Hue(0x0000),
        use_all_res: false,
        min_skill_offset: 0,
        markable: true,
        never_exceptional: false,
        always_exceptional: false,
        needs: Needs::none(),
    },
    Recipe {
        graphic: Graphic(0x1410),
        name: Text::Cliloc(1025136),
        group: 0,
        skills: SKILLS_7,
        resources: RES_7,
        amount: 1,
        hue: Hue(0x0000),
        use_all_res: false,
        min_skill_offset: 0,
        markable: true,
        never_exceptional: false,
        always_exceptional: false,
        needs: Needs::none(),
    },
    Recipe {
        graphic: Graphic(0x1414),
        name: Text::Cliloc(1025140),
        group: 0,
        skills: SKILLS_8,
        resources: RES_8,
        amount: 1,
        hue: Hue(0x0000),
        use_all_res: false,
        min_skill_offset: 0,
        markable: true,
        never_exceptional: false,
        always_exceptional: false,
        needs: Needs::none(),
    },
    Recipe {
        graphic: Graphic(0x1413),
        name: Text::Cliloc(1025139),
        group: 0,
        skills: SKILLS_9,
        resources: RES_9,
        amount: 1,
        hue: Hue(0x0000),
        use_all_res: false,
        min_skill_offset: 0,
        markable: true,
        never_exceptional: false,
        always_exceptional: false,
        needs: Needs::none(),
    },
    Recipe {
        graphic: Graphic(0x1411),
        name: Text::Cliloc(1025137),
        group: 0,
        skills: SKILLS_10,
        resources: RES_10,
        amount: 1,
        hue: Hue(0x0000),
        use_all_res: false,
        min_skill_offset: 0,
        markable: true,
        never_exceptional: false,
        always_exceptional: false,
        needs: Needs::none(),
    },
    Recipe {
        graphic: Graphic(0x1415),
        name: Text::Cliloc(1046431),
        group: 0,
        skills: SKILLS_11,
        resources: RES_11,
        amount: 1,
        hue: Hue(0x0000),
        use_all_res: false,
        min_skill_offset: 0,
        markable: true,
        never_exceptional: false,
        always_exceptional: false,
        needs: Needs::none(),
    },
    Recipe {
        graphic: Graphic(0x1C04),
        name: Text::Cliloc(1046430),
        group: 0,
        skills: SKILLS_12,
        resources: RES_12,
        amount: 1,
        hue: Hue(0x0000),
        use_all_res: false,
        min_skill_offset: 0,
        markable: true,
        never_exceptional: false,
        always_exceptional: false,
        needs: Needs::none(),
    },
    Recipe {
        graphic: Graphic(0x14F0),
        name: Text::Cliloc(1053012),
        group: 0,
        skills: SKILLS_13,
        resources: RES_13,
        amount: 1,
        hue: Hue(0x0000),
        use_all_res: false,
        min_skill_offset: 0,
        markable: true,
        never_exceptional: false,
        always_exceptional: false,
        needs: Needs::none(),
    },
    Recipe {
        graphic: Graphic(0x2779),
        name: Text::Cliloc(1030180),
        group: 0,
        skills: SKILLS_14,
        resources: RES_14,
        amount: 1,
        hue: Hue(0x0000),
        use_all_res: false,
        min_skill_offset: 0,
        markable: true,
        never_exceptional: false,
        always_exceptional: false,
        needs: Needs::none(),
    },
    Recipe {
        graphic: Graphic(0x277D),
        name: Text::Cliloc(1030184),
        group: 0,
        skills: SKILLS_15,
        resources: RES_15,
        amount: 1,
        hue: Hue(0x0000),
        use_all_res: false,
        min_skill_offset: 0,
        markable: true,
        never_exceptional: false,
        always_exceptional: false,
        needs: Needs::none(),
    },
    Recipe {
        graphic: Graphic(0x2780),
        name: Text::Cliloc(1030187),
        group: 0,
        skills: SKILLS_16,
        resources: RES_16,
        amount: 1,
        hue: Hue(0x0000),
        use_all_res: false,
        min_skill_offset: 0,
        markable: true,
        never_exceptional: false,
        always_exceptional: false,
        needs: Needs::none(),
    },
    Recipe {
        graphic: Graphic(0x2788),
        name: Text::Cliloc(1030195),
        group: 0,
        skills: SKILLS_17,
        resources: RES_17,
        amount: 1,
        hue: Hue(0x0000),
        use_all_res: false,
        min_skill_offset: 0,
        markable: true,
        never_exceptional: false,
        always_exceptional: false,
        needs: Needs::none(),
    },
    Recipe {
        graphic: Graphic(0x278D),
        name: Text::Cliloc(1030200),
        group: 0,
        skills: SKILLS_18,
        resources: RES_18,
        amount: 1,
        hue: Hue(0x0000),
        use_all_res: false,
        min_skill_offset: 0,
        markable: true,
        never_exceptional: false,
        always_exceptional: false,
        needs: Needs::none(),
    },
    Recipe {
        graphic: Graphic(0x140C),
        name: Text::Cliloc(1025132),
        group: 1,
        skills: SKILLS_19,
        resources: RES_19,
        amount: 1,
        hue: Hue(0x0000),
        use_all_res: false,
        min_skill_offset: 0,
        markable: true,
        never_exceptional: false,
        always_exceptional: false,
        needs: Needs::none(),
    },
    Recipe {
        graphic: Graphic(0x1408),
        name: Text::Cliloc(1025128),
        group: 1,
        skills: SKILLS_20,
        resources: RES_20,
        amount: 1,
        hue: Hue(0x0000),
        use_all_res: false,
        min_skill_offset: 0,
        markable: true,
        never_exceptional: false,
        always_exceptional: false,
        needs: Needs::none(),
    },
    Recipe {
        graphic: Graphic(0x140A),
        name: Text::Cliloc(1025130),
        group: 1,
        skills: SKILLS_21,
        resources: RES_21,
        amount: 1,
        hue: Hue(0x0000),
        use_all_res: false,
        min_skill_offset: 0,
        markable: true,
        never_exceptional: false,
        always_exceptional: false,
        needs: Needs::none(),
    },
    Recipe {
        graphic: Graphic(0x140E),
        name: Text::Cliloc(1025134),
        group: 1,
        skills: SKILLS_22,
        resources: RES_22,
        amount: 1,
        hue: Hue(0x0000),
        use_all_res: false,
        min_skill_offset: 0,
        markable: true,
        never_exceptional: false,
        always_exceptional: false,
        needs: Needs::none(),
    },
    Recipe {
        graphic: Graphic(0x1412),
        name: Text::Cliloc(1025138),
        group: 1,
        skills: SKILLS_23,
        resources: RES_23,
        amount: 1,
        hue: Hue(0x0000),
        use_all_res: false,
        min_skill_offset: 0,
        markable: true,
        never_exceptional: false,
        always_exceptional: false,
        needs: Needs::none(),
    },
    Recipe {
        graphic: Graphic(0x2774),
        name: Text::Cliloc(1030175),
        group: 1,
        skills: SKILLS_24,
        resources: RES_24,
        amount: 1,
        hue: Hue(0x0000),
        use_all_res: false,
        min_skill_offset: 0,
        markable: true,
        never_exceptional: false,
        always_exceptional: false,
        needs: Needs::none(),
    },
    Recipe {
        graphic: Graphic(0x2775),
        name: Text::Cliloc(1030176),
        group: 1,
        skills: SKILLS_25,
        resources: RES_25,
        amount: 1,
        hue: Hue(0x0000),
        use_all_res: false,
        min_skill_offset: 0,
        markable: true,
        never_exceptional: false,
        always_exceptional: false,
        needs: Needs::none(),
    },
    Recipe {
        graphic: Graphic(0x2777),
        name: Text::Cliloc(1030178),
        group: 1,
        skills: SKILLS_26,
        resources: RES_26,
        amount: 1,
        hue: Hue(0x0000),
        use_all_res: false,
        min_skill_offset: 0,
        markable: true,
        never_exceptional: false,
        always_exceptional: false,
        needs: Needs::none(),
    },
    Recipe {
        graphic: Graphic(0x2781),
        name: Text::Cliloc(1030188),
        group: 1,
        skills: SKILLS_27,
        resources: RES_27,
        amount: 1,
        hue: Hue(0x0000),
        use_all_res: false,
        min_skill_offset: 0,
        markable: true,
        never_exceptional: false,
        always_exceptional: false,
        needs: Needs::none(),
    },
    Recipe {
        graphic: Graphic(0x2784),
        name: Text::Cliloc(1030191),
        group: 1,
        skills: SKILLS_28,
        resources: RES_28,
        amount: 1,
        hue: Hue(0x0000),
        use_all_res: false,
        min_skill_offset: 0,
        markable: true,
        never_exceptional: false,
        always_exceptional: false,
        needs: Needs::none(),
    },
    Recipe {
        graphic: Graphic(0x2778),
        name: Text::Cliloc(1030179),
        group: 1,
        skills: SKILLS_29,
        resources: RES_29,
        amount: 1,
        hue: Hue(0x0000),
        use_all_res: false,
        min_skill_offset: 0,
        markable: true,
        never_exceptional: false,
        always_exceptional: false,
        needs: Needs::none(),
    },
    Recipe {
        graphic: Graphic(0x2785),
        name: Text::Cliloc(1030192),
        group: 1,
        skills: SKILLS_30,
        resources: RES_30,
        amount: 1,
        hue: Hue(0x0000),
        use_all_res: false,
        min_skill_offset: 0,
        markable: true,
        never_exceptional: false,
        always_exceptional: false,
        needs: Needs::none(),
    },
    Recipe {
        graphic: Graphic(0x2789),
        name: Text::Cliloc(1030196),
        group: 1,
        skills: SKILLS_31,
        resources: RES_31,
        amount: 1,
        hue: Hue(0x0000),
        use_all_res: false,
        min_skill_offset: 0,
        markable: true,
        never_exceptional: false,
        always_exceptional: false,
        needs: Needs::none(),
    },
    Recipe {
        graphic: Graphic(0x2B6E),
        name: Text::Cliloc(1032645),
        group: 1,
        skills: SKILLS_32,
        resources: RES_32,
        amount: 1,
        hue: Hue(0x0000),
        use_all_res: false,
        min_skill_offset: 0,
        markable: true,
        never_exceptional: false,
        always_exceptional: false,
        needs: Needs::none(),
    },
    Recipe {
        graphic: Graphic(0x2B6F),
        name: Text::Cliloc(1032646),
        group: 1,
        skills: SKILLS_33,
        resources: RES_33,
        amount: 1,
        hue: Hue(0x0000),
        use_all_res: false,
        min_skill_offset: 0,
        markable: true,
        never_exceptional: false,
        always_exceptional: false,
        needs: Needs::none(),
    },
    Recipe {
        graphic: Graphic(0x2B70),
        name: Text::Cliloc(1032647),
        group: 1,
        skills: SKILLS_34,
        resources: RES_34,
        amount: 1,
        hue: Hue(0x0000),
        use_all_res: false,
        min_skill_offset: 0,
        markable: true,
        never_exceptional: false,
        always_exceptional: false,
        needs: Needs::none(),
    },
    Recipe {
        graphic: Graphic(0x1B73),
        name: Text::Cliloc(1027027),
        group: 2,
        skills: SKILLS_35,
        resources: RES_35,
        amount: 1,
        hue: Hue(0x0000),
        use_all_res: false,
        min_skill_offset: 0,
        markable: true,
        never_exceptional: false,
        always_exceptional: false,
        needs: Needs::none(),
    },
    Recipe {
        graphic: Graphic(0x1B72),
        name: Text::Cliloc(1027026),
        group: 2,
        skills: SKILLS_36,
        resources: RES_36,
        amount: 1,
        hue: Hue(0x0000),
        use_all_res: false,
        min_skill_offset: 0,
        markable: true,
        never_exceptional: false,
        always_exceptional: false,
        needs: Needs::none(),
    },
    Recipe {
        graphic: Graphic(0x1B76),
        name: Text::Cliloc(1027030),
        group: 2,
        skills: SKILLS_37,
        resources: RES_37,
        amount: 1,
        hue: Hue(0x0000),
        use_all_res: false,
        min_skill_offset: 0,
        markable: true,
        never_exceptional: false,
        always_exceptional: false,
        needs: Needs::none(),
    },
    Recipe {
        graphic: Graphic(0x1B7B),
        name: Text::Cliloc(1027035),
        group: 2,
        skills: SKILLS_38,
        resources: RES_38,
        amount: 1,
        hue: Hue(0x0000),
        use_all_res: false,
        min_skill_offset: 0,
        markable: true,
        never_exceptional: false,
        always_exceptional: false,
        needs: Needs::none(),
    },
    Recipe {
        graphic: Graphic(0x1B74),
        name: Text::Cliloc(1027028),
        group: 2,
        skills: SKILLS_39,
        resources: RES_39,
        amount: 1,
        hue: Hue(0x0000),
        use_all_res: false,
        min_skill_offset: 0,
        markable: true,
        never_exceptional: false,
        always_exceptional: false,
        needs: Needs::none(),
    },
    Recipe {
        graphic: Graphic(0x1B78),
        name: Text::Cliloc(1027032),
        group: 2,
        skills: SKILLS_40,
        resources: RES_40,
        amount: 1,
        hue: Hue(0x0000),
        use_all_res: false,
        min_skill_offset: 0,
        markable: true,
        never_exceptional: false,
        always_exceptional: false,
        needs: Needs::none(),
    },
    Recipe {
        graphic: Graphic(0x1BC3),
        name: Text::Cliloc(1027107),
        group: 2,
        skills: SKILLS_41,
        resources: RES_41,
        amount: 1,
        hue: Hue(0x0000),
        use_all_res: false,
        min_skill_offset: 0,
        markable: true,
        never_exceptional: false,
        always_exceptional: false,
        needs: Needs::none(),
    },
    Recipe {
        graphic: Graphic(0x1BC4),
        name: Text::Cliloc(1027108),
        group: 2,
        skills: SKILLS_42,
        resources: RES_42,
        amount: 1,
        hue: Hue(0x0000),
        use_all_res: false,
        min_skill_offset: 0,
        markable: true,
        never_exceptional: false,
        always_exceptional: false,
        needs: Needs::none(),
    },
    Recipe {
        graphic: Graphic(0x26BB),
        name: Text::Cliloc(1029915),
        group: 3,
        skills: SKILLS_43,
        resources: RES_43,
        amount: 1,
        hue: Hue(0x0000),
        use_all_res: false,
        min_skill_offset: 0,
        markable: true,
        never_exceptional: false,
        always_exceptional: false,
        needs: Needs::none(),
    },
    Recipe {
        graphic: Graphic(0x0F5E),
        name: Text::Cliloc(1023934),
        group: 3,
        skills: SKILLS_44,
        resources: RES_44,
        amount: 1,
        hue: Hue(0x0000),
        use_all_res: false,
        min_skill_offset: 0,
        markable: true,
        never_exceptional: false,
        always_exceptional: false,
        needs: Needs::none(),
    },
    Recipe {
        graphic: Graphic(0x26C1),
        name: Text::Cliloc(1029921),
        group: 3,
        skills: SKILLS_45,
        resources: RES_45,
        amount: 1,
        hue: Hue(0x0000),
        use_all_res: false,
        min_skill_offset: 0,
        markable: true,
        never_exceptional: false,
        always_exceptional: false,
        needs: Needs::none(),
    },
    Recipe {
        graphic: Graphic(0x1441),
        name: Text::Cliloc(1025185),
        group: 3,
        skills: SKILLS_46,
        resources: RES_46,
        amount: 1,
        hue: Hue(0x0000),
        use_all_res: false,
        min_skill_offset: 0,
        markable: true,
        never_exceptional: false,
        always_exceptional: false,
        needs: Needs::none(),
    },
    Recipe {
        graphic: Graphic(0x0F52),
        name: Text::Cliloc(1023921),
        group: 3,
        skills: SKILLS_47,
        resources: RES_47,
        amount: 1,
        hue: Hue(0x0000),
        use_all_res: false,
        min_skill_offset: 0,
        markable: true,
        never_exceptional: false,
        always_exceptional: false,
        needs: Needs::none(),
    },
    Recipe {
        graphic: Graphic(0x13FF),
        name: Text::Cliloc(1025119),
        group: 3,
        skills: SKILLS_48,
        resources: RES_48,
        amount: 1,
        hue: Hue(0x0000),
        use_all_res: false,
        min_skill_offset: 0,
        markable: true,
        never_exceptional: false,
        always_exceptional: false,
        needs: Needs::none(),
    },
    Recipe {
        graphic: Graphic(0x1401),
        name: Text::Cliloc(1025121),
        group: 3,
        skills: SKILLS_49,
        resources: RES_49,
        amount: 1,
        hue: Hue(0x0000),
        use_all_res: false,
        min_skill_offset: 0,
        markable: true,
        never_exceptional: false,
        always_exceptional: false,
        needs: Needs::none(),
    },
    Recipe {
        graphic: Graphic(0x0F61),
        name: Text::Cliloc(1023937),
        group: 3,
        skills: SKILLS_50,
        resources: RES_50,
        amount: 1,
        hue: Hue(0x0000),
        use_all_res: false,
        min_skill_offset: 0,
        markable: true,
        never_exceptional: false,
        always_exceptional: false,
        needs: Needs::none(),
    },
    Recipe {
        graphic: Graphic(0x13B6),
        name: Text::Cliloc(1025046),
        group: 3,
        skills: SKILLS_51,
        resources: RES_51,
        amount: 1,
        hue: Hue(0x0000),
        use_all_res: false,
        min_skill_offset: 0,
        markable: true,
        never_exceptional: false,
        always_exceptional: false,
        needs: Needs::none(),
    },
    Recipe {
        graphic: Graphic(0x13B9),
        name: Text::Cliloc(1025049),
        group: 3,
        skills: SKILLS_52,
        resources: RES_52,
        amount: 1,
        hue: Hue(0x0000),
        use_all_res: false,
        min_skill_offset: 0,
        markable: true,
        never_exceptional: false,
        always_exceptional: false,
        needs: Needs::none(),
    },
    Recipe {
        graphic: Graphic(0x27A2),
        name: Text::Cliloc(1030221),
        group: 3,
        skills: SKILLS_53,
        resources: RES_53,
        amount: 1,
        hue: Hue(0x0000),
        use_all_res: false,
        min_skill_offset: 0,
        markable: true,
        never_exceptional: false,
        always_exceptional: false,
        needs: Needs::none(),
    },
    Recipe {
        graphic: Graphic(0x27A4),
        name: Text::Cliloc(1030223),
        group: 3,
        skills: SKILLS_54,
        resources: RES_54,
        amount: 1,
        hue: Hue(0x0000),
        use_all_res: false,
        min_skill_offset: 0,
        markable: true,
        never_exceptional: false,
        always_exceptional: false,
        needs: Needs::none(),
    },
    Recipe {
        graphic: Graphic(0x27A7),
        name: Text::Cliloc(1030226),
        group: 3,
        skills: SKILLS_55,
        resources: RES_55,
        amount: 1,
        hue: Hue(0x0000),
        use_all_res: false,
        min_skill_offset: 0,
        markable: true,
        never_exceptional: false,
        always_exceptional: false,
        needs: Needs::none(),
    },
    Recipe {
        graphic: Graphic(0x27A9),
        name: Text::Cliloc(1030228),
        group: 3,
        skills: SKILLS_56,
        resources: RES_56,
        amount: 1,
        hue: Hue(0x0000),
        use_all_res: false,
        min_skill_offset: 0,
        markable: true,
        never_exceptional: false,
        always_exceptional: false,
        needs: Needs::none(),
    },
    Recipe {
        graphic: Graphic(0x27AB),
        name: Text::Cliloc(1030230),
        group: 3,
        skills: SKILLS_57,
        resources: RES_57,
        amount: 1,
        hue: Hue(0x0000),
        use_all_res: false,
        min_skill_offset: 0,
        markable: true,
        never_exceptional: false,
        always_exceptional: false,
        needs: Needs::none(),
    },
    Recipe {
        graphic: Graphic(0x27AC),
        name: Text::Cliloc(1030231),
        group: 3,
        skills: SKILLS_58,
        resources: RES_58,
        amount: 1,
        hue: Hue(0x0000),
        use_all_res: false,
        min_skill_offset: 0,
        markable: false,
        never_exceptional: false,
        always_exceptional: false,
        needs: Needs::none(),
    },
    Recipe {
        graphic: Graphic(0x27AD),
        name: Text::Cliloc(1030232),
        group: 3,
        skills: SKILLS_59,
        resources: RES_59,
        amount: 1,
        hue: Hue(0x0000),
        use_all_res: false,
        min_skill_offset: 0,
        markable: true,
        never_exceptional: false,
        always_exceptional: false,
        needs: Needs::none(),
    },
    Recipe {
        graphic: Graphic(0x27AF),
        name: Text::Cliloc(1030234),
        group: 3,
        skills: SKILLS_60,
        resources: RES_60,
        amount: 1,
        hue: Hue(0x0000),
        use_all_res: false,
        min_skill_offset: 0,
        markable: true,
        never_exceptional: false,
        always_exceptional: false,
        needs: Needs::none(),
    },
    Recipe {
        graphic: Graphic(0x2D33),
        name: Text::Cliloc(1031571),
        group: 3,
        skills: SKILLS_61,
        resources: RES_61,
        amount: 1,
        hue: Hue(0x0000),
        use_all_res: false,
        min_skill_offset: 0,
        markable: true,
        never_exceptional: false,
        always_exceptional: false,
        needs: Needs::none(),
    },
    Recipe {
        graphic: Graphic(0x2D2F),
        name: Text::Cliloc(1031567),
        group: 3,
        skills: SKILLS_62,
        resources: RES_62,
        amount: 1,
        hue: Hue(0x0000),
        use_all_res: false,
        min_skill_offset: 0,
        markable: true,
        never_exceptional: false,
        always_exceptional: false,
        needs: Needs::none(),
    },
    Recipe {
        graphic: Graphic(0x2D20),
        name: Text::Cliloc(1031564),
        group: 3,
        skills: SKILLS_63,
        resources: RES_63,
        amount: 1,
        hue: Hue(0x0000),
        use_all_res: false,
        min_skill_offset: 0,
        markable: true,
        never_exceptional: false,
        always_exceptional: false,
        needs: Needs::none(),
    },
    Recipe {
        graphic: Graphic(0x2D21),
        name: Text::Cliloc(1031565),
        group: 3,
        skills: SKILLS_64,
        resources: RES_64,
        amount: 1,
        hue: Hue(0x0000),
        use_all_res: false,
        min_skill_offset: 0,
        markable: true,
        never_exceptional: false,
        always_exceptional: false,
        needs: Needs::none(),
    },
    Recipe {
        graphic: Graphic(0x2D22),
        name: Text::Cliloc(1031566),
        group: 3,
        skills: SKILLS_65,
        resources: RES_65,
        amount: 1,
        hue: Hue(0x0000),
        use_all_res: false,
        min_skill_offset: 0,
        markable: true,
        never_exceptional: false,
        always_exceptional: false,
        needs: Needs::none(),
    },
    Recipe {
        graphic: Graphic(0x2D32),
        name: Text::Cliloc(1031570),
        group: 3,
        skills: SKILLS_66,
        resources: RES_66,
        amount: 1,
        hue: Hue(0x0000),
        use_all_res: false,
        min_skill_offset: 0,
        markable: true,
        never_exceptional: false,
        always_exceptional: false,
        needs: Needs::none(),
    },
    Recipe {
        graphic: Graphic(0x2D35),
        name: Text::Cliloc(1031573),
        group: 3,
        skills: SKILLS_67,
        resources: RES_67,
        amount: 1,
        hue: Hue(0x0000),
        use_all_res: false,
        min_skill_offset: 0,
        markable: true,
        never_exceptional: false,
        always_exceptional: false,
        needs: Needs::none(),
    },
    Recipe {
        graphic: Graphic(0x0F49),
        name: Text::Cliloc(1023913),
        group: 4,
        skills: SKILLS_68,
        resources: RES_68,
        amount: 1,
        hue: Hue(0x0000),
        use_all_res: false,
        min_skill_offset: 0,
        markable: true,
        never_exceptional: false,
        always_exceptional: false,
        needs: Needs::none(),
    },
    Recipe {
        graphic: Graphic(0x0F47),
        name: Text::Cliloc(1023911),
        group: 4,
        skills: SKILLS_69,
        resources: RES_69,
        amount: 1,
        hue: Hue(0x0000),
        use_all_res: false,
        min_skill_offset: 0,
        markable: true,
        never_exceptional: false,
        always_exceptional: false,
        needs: Needs::none(),
    },
    Recipe {
        graphic: Graphic(0x0F4B),
        name: Text::Cliloc(1023915),
        group: 4,
        skills: SKILLS_70,
        resources: RES_70,
        amount: 1,
        hue: Hue(0x0000),
        use_all_res: false,
        min_skill_offset: 0,
        markable: true,
        never_exceptional: false,
        always_exceptional: false,
        needs: Needs::none(),
    },
    Recipe {
        graphic: Graphic(0x0F45),
        name: Text::Cliloc(1023909),
        group: 4,
        skills: SKILLS_71,
        resources: RES_71,
        amount: 1,
        hue: Hue(0x0000),
        use_all_res: false,
        min_skill_offset: 0,
        markable: true,
        never_exceptional: false,
        always_exceptional: false,
        needs: Needs::none(),
    },
    Recipe {
        graphic: Graphic(0x13FB),
        name: Text::Cliloc(1025115),
        group: 4,
        skills: SKILLS_72,
        resources: RES_72,
        amount: 1,
        hue: Hue(0x0000),
        use_all_res: false,
        min_skill_offset: 0,
        markable: true,
        never_exceptional: false,
        always_exceptional: false,
        needs: Needs::none(),
    },
    Recipe {
        graphic: Graphic(0x1443),
        name: Text::Cliloc(1025187),
        group: 4,
        skills: SKILLS_73,
        resources: RES_73,
        amount: 1,
        hue: Hue(0x0000),
        use_all_res: false,
        min_skill_offset: 0,
        markable: true,
        never_exceptional: false,
        always_exceptional: false,
        needs: Needs::none(),
    },
    Recipe {
        graphic: Graphic(0x13B0),
        name: Text::Cliloc(1025040),
        group: 4,
        skills: SKILLS_74,
        resources: RES_74,
        amount: 1,
        hue: Hue(0x0000),
        use_all_res: false,
        min_skill_offset: 0,
        markable: true,
        never_exceptional: false,
        always_exceptional: false,
        needs: Needs::none(),
    },
    Recipe {
        graphic: Graphic(0x2D28),
        name: Text::Cliloc(1031572),
        group: 4,
        skills: SKILLS_75,
        resources: RES_75,
        amount: 1,
        hue: Hue(0x0000),
        use_all_res: false,
        min_skill_offset: 0,
        markable: true,
        never_exceptional: false,
        always_exceptional: false,
        needs: Needs::none(),
    },
    Recipe {
        graphic: Graphic(0x0F4D),
        name: Text::Cliloc(1023917),
        group: 5,
        skills: SKILLS_76,
        resources: RES_76,
        amount: 1,
        hue: Hue(0x0000),
        use_all_res: false,
        min_skill_offset: 0,
        markable: true,
        never_exceptional: false,
        always_exceptional: false,
        needs: Needs::none(),
    },
    Recipe {
        graphic: Graphic(0x26BD),
        name: Text::Cliloc(1029917),
        group: 5,
        skills: SKILLS_77,
        resources: RES_77,
        amount: 1,
        hue: Hue(0x0000),
        use_all_res: false,
        min_skill_offset: 0,
        markable: true,
        never_exceptional: false,
        always_exceptional: false,
        needs: Needs::none(),
    },
    Recipe {
        graphic: Graphic(0x26BF),
        name: Text::Cliloc(1029919),
        group: 5,
        skills: SKILLS_78,
        resources: RES_78,
        amount: 1,
        hue: Hue(0x0000),
        use_all_res: false,
        min_skill_offset: 0,
        markable: true,
        never_exceptional: false,
        always_exceptional: false,
        needs: Needs::none(),
    },
    Recipe {
        graphic: Graphic(0x143E),
        name: Text::Cliloc(1025183),
        group: 5,
        skills: SKILLS_79,
        resources: RES_79,
        amount: 1,
        hue: Hue(0x0000),
        use_all_res: false,
        min_skill_offset: 0,
        markable: true,
        never_exceptional: false,
        always_exceptional: false,
        needs: Needs::none(),
    },
    Recipe {
        graphic: Graphic(0x26C0),
        name: Text::Cliloc(1029920),
        group: 5,
        skills: SKILLS_80,
        resources: RES_80,
        amount: 1,
        hue: Hue(0x0000),
        use_all_res: false,
        min_skill_offset: 0,
        markable: true,
        never_exceptional: false,
        always_exceptional: false,
        needs: Needs::none(),
    },
    Recipe {
        graphic: Graphic(0x26BE),
        name: Text::Cliloc(1029918),
        group: 5,
        skills: SKILLS_81,
        resources: RES_81,
        amount: 1,
        hue: Hue(0x0000),
        use_all_res: false,
        min_skill_offset: 0,
        markable: true,
        never_exceptional: false,
        always_exceptional: false,
        needs: Needs::none(),
    },
    Recipe {
        graphic: Graphic(0x1403),
        name: Text::Cliloc(1025123),
        group: 5,
        skills: SKILLS_82,
        resources: RES_82,
        amount: 1,
        hue: Hue(0x0000),
        use_all_res: false,
        min_skill_offset: 0,
        markable: true,
        never_exceptional: false,
        always_exceptional: false,
        needs: Needs::none(),
    },
    Recipe {
        graphic: Graphic(0x26BA),
        name: Text::Cliloc(1029914),
        group: 5,
        skills: SKILLS_83,
        resources: RES_83,
        amount: 1,
        hue: Hue(0x0000),
        use_all_res: false,
        min_skill_offset: 0,
        markable: true,
        never_exceptional: false,
        always_exceptional: false,
        needs: Needs::none(),
    },
    Recipe {
        graphic: Graphic(0x0F62),
        name: Text::Cliloc(1023938),
        group: 5,
        skills: SKILLS_84,
        resources: RES_84,
        amount: 1,
        hue: Hue(0x0000),
        use_all_res: false,
        min_skill_offset: 0,
        markable: true,
        never_exceptional: false,
        always_exceptional: false,
        needs: Needs::none(),
    },
    Recipe {
        graphic: Graphic(0x1405),
        name: Text::Cliloc(1025125),
        group: 5,
        skills: SKILLS_85,
        resources: RES_85,
        amount: 1,
        hue: Hue(0x0000),
        use_all_res: false,
        min_skill_offset: 0,
        markable: true,
        never_exceptional: false,
        always_exceptional: false,
        needs: Needs::none(),
    },
    Recipe {
        graphic: Graphic(0x143D),
        name: Text::Cliloc(1025181),
        group: 6,
        skills: SKILLS_86,
        resources: RES_86,
        amount: 1,
        hue: Hue(0x0000),
        use_all_res: false,
        min_skill_offset: 0,
        markable: true,
        never_exceptional: false,
        always_exceptional: false,
        needs: Needs::none(),
    },
    Recipe {
        graphic: Graphic(0x0F5C),
        name: Text::Cliloc(1023932),
        group: 6,
        skills: SKILLS_87,
        resources: RES_87,
        amount: 1,
        hue: Hue(0x0000),
        use_all_res: false,
        min_skill_offset: 0,
        markable: true,
        never_exceptional: false,
        always_exceptional: false,
        needs: Needs::none(),
    },
    Recipe {
        graphic: Graphic(0x143B),
        name: Text::Cliloc(1025179),
        group: 6,
        skills: SKILLS_88,
        resources: RES_88,
        amount: 1,
        hue: Hue(0x0000),
        use_all_res: false,
        min_skill_offset: 0,
        markable: true,
        never_exceptional: false,
        always_exceptional: false,
        needs: Needs::none(),
    },
    Recipe {
        graphic: Graphic(0x26BC),
        name: Text::Cliloc(1029916),
        group: 6,
        skills: SKILLS_89,
        resources: RES_89,
        amount: 1,
        hue: Hue(0x0000),
        use_all_res: false,
        min_skill_offset: 0,
        markable: true,
        never_exceptional: false,
        always_exceptional: false,
        needs: Needs::none(),
    },
    Recipe {
        graphic: Graphic(0x1407),
        name: Text::Cliloc(1025127),
        group: 6,
        skills: SKILLS_90,
        resources: RES_90,
        amount: 1,
        hue: Hue(0x0000),
        use_all_res: false,
        min_skill_offset: 0,
        markable: true,
        never_exceptional: false,
        always_exceptional: false,
        needs: Needs::none(),
    },
    Recipe {
        graphic: Graphic(0x1439),
        name: Text::Cliloc(1025177),
        group: 6,
        skills: SKILLS_91,
        resources: RES_91,
        amount: 1,
        hue: Hue(0x0000),
        use_all_res: false,
        min_skill_offset: 0,
        markable: true,
        never_exceptional: false,
        always_exceptional: false,
        needs: Needs::none(),
    },
    Recipe {
        graphic: Graphic(0x27A3),
        name: Text::Cliloc(1030222),
        group: 6,
        skills: SKILLS_92,
        resources: RES_92,
        amount: 1,
        hue: Hue(0x0000),
        use_all_res: false,
        min_skill_offset: 0,
        markable: true,
        never_exceptional: false,
        always_exceptional: false,
        needs: Needs::none(),
    },
    Recipe {
        graphic: Graphic(0x2D24),
        name: Text::Cliloc(1031568),
        group: 6,
        skills: SKILLS_93,
        resources: RES_93,
        amount: 1,
        hue: Hue(0x0000),
        use_all_res: false,
        min_skill_offset: 0,
        markable: true,
        never_exceptional: false,
        always_exceptional: false,
        needs: Needs::none(),
    },
    Recipe {
        graphic: Graphic(0x0E7F),
        name: Text::Cliloc(1150675),
        group: 7,
        skills: SKILLS_94,
        resources: RES_94,
        amount: 1,
        hue: Hue(0x0000),
        use_all_res: false,
        min_skill_offset: 0,
        markable: false,
        never_exceptional: false,
        always_exceptional: false,
        needs: Needs::none(),
    },
];

/// The material this trade is worked in.
pub const SUB_RES: SubResAxis = SubResAxis {
    graphic: Graphic(0x1BF2),
    name: Text::Cliloc(1044022),
    entries: &[
        SubRes {
            hue: Hue(0x0000),
            name: Text::Cliloc(1044022),
            req_skill: 0,
            message: Text::Cliloc(1044267),
        },
        SubRes {
            hue: Hue(0x0973),
            name: Text::Cliloc(1044023),
            req_skill: 650,
            message: Text::Cliloc(1044268),
        },
        SubRes {
            hue: Hue(0x0966),
            name: Text::Cliloc(1044024),
            req_skill: 700,
            message: Text::Cliloc(1044268),
        },
        SubRes {
            hue: Hue(0x096D),
            name: Text::Cliloc(1044025),
            req_skill: 750,
            message: Text::Cliloc(1044268),
        },
        SubRes {
            hue: Hue(0x0972),
            name: Text::Cliloc(1044026),
            req_skill: 800,
            message: Text::Cliloc(1044268),
        },
        SubRes {
            hue: Hue(0x08A5),
            name: Text::Cliloc(1044027),
            req_skill: 850,
            message: Text::Cliloc(1044268),
        },
        SubRes {
            hue: Hue(0x0979),
            name: Text::Cliloc(1044028),
            req_skill: 900,
            message: Text::Cliloc(1044268),
        },
        SubRes {
            hue: Hue(0x089F),
            name: Text::Cliloc(1044029),
            req_skill: 950,
            message: Text::Cliloc(1044268),
        },
        SubRes {
            hue: Hue(0x08AB),
            name: Text::Cliloc(1044030),
            req_skill: 990,
            message: Text::Cliloc(1044268),
        },
    ],
};
