//! DefTailoring's recipes, as core data.
//!
//! Generated once from ServUO by `tools/gen-craft-tables`, and ordinary source
//! from then on: edit it, do not regenerate it. Skills are in tenths.

use openshard_protocol::wire::{Graphic, Hue};
use openshard_state::Skill;

use crate::recipe::{CraftRes, CraftSkillReq, Recipe, SubRes, SubResAxis};
use crate::system::{Needs, Text};

/// The gump's left-hand column.
pub const GROUPS: &[Text] = &[
    Text::Cliloc(1044457),
    Text::Cliloc(1011375),
    Text::Cliloc(1111747),
    Text::Cliloc(1015283),
    Text::Cliloc(1015288),
    Text::Cliloc(1015293),
    Text::Cliloc(1015300),
    Text::Cliloc(1015306),
    Text::Cliloc(1049149),
];

const SKILLS_0: &[CraftSkillReq] = &[CraftSkillReq {
    skill: Skill::Tailoring,
    min: 0,
    max: 250,
}];
const RES_0: &[CraftRes] = &[CraftRes {
    graphic: Graphic(0x1766),
    hue: Hue(0x0000),
    amount: 2,
    name: Text::Cliloc(1044455),
    message: Text::Cliloc(1044287),
    from_axis: false,
}];
const SKILLS_1: &[CraftSkillReq] = &[CraftSkillReq {
    skill: Skill::Tailoring,
    min: 0,
    max: 250,
}];
const RES_1: &[CraftRes] = &[CraftRes {
    graphic: Graphic(0x1766),
    hue: Hue(0x0000),
    amount: 2,
    name: Text::Cliloc(1044455),
    message: Text::Cliloc(1044287),
    from_axis: false,
}];
const SKILLS_2: &[CraftSkillReq] = &[CraftSkillReq {
    skill: Skill::Tailoring,
    min: 62,
    max: 312,
}];
const RES_2: &[CraftRes] = &[CraftRes {
    graphic: Graphic(0x1766),
    hue: Hue(0x0000),
    amount: 11,
    name: Text::Cliloc(1044455),
    message: Text::Cliloc(1044287),
    from_axis: false,
}];
const SKILLS_3: &[CraftSkillReq] = &[CraftSkillReq {
    skill: Skill::Tailoring,
    min: 62,
    max: 312,
}];
const RES_3: &[CraftRes] = &[CraftRes {
    graphic: Graphic(0x1766),
    hue: Hue(0x0000),
    amount: 11,
    name: Text::Cliloc(1044455),
    message: Text::Cliloc(1044287),
    from_axis: false,
}];
const SKILLS_4: &[CraftSkillReq] = &[CraftSkillReq {
    skill: Skill::Tailoring,
    min: 62,
    max: 312,
}];
const RES_4: &[CraftRes] = &[CraftRes {
    graphic: Graphic(0x1766),
    hue: Hue(0x0000),
    amount: 12,
    name: Text::Cliloc(1044455),
    message: Text::Cliloc(1044287),
    from_axis: false,
}];
const SKILLS_5: &[CraftSkillReq] = &[CraftSkillReq {
    skill: Skill::Tailoring,
    min: 62,
    max: 312,
}];
const RES_5: &[CraftRes] = &[CraftRes {
    graphic: Graphic(0x1766),
    hue: Hue(0x0000),
    amount: 10,
    name: Text::Cliloc(1044455),
    message: Text::Cliloc(1044287),
    from_axis: false,
}];
const SKILLS_6: &[CraftSkillReq] = &[CraftSkillReq {
    skill: Skill::Tailoring,
    min: 67,
    max: 317,
}];
const RES_6: &[CraftRes] = &[CraftRes {
    graphic: Graphic(0x1766),
    hue: Hue(0x0000),
    amount: 13,
    name: Text::Cliloc(1044455),
    message: Text::Cliloc(1044287),
    from_axis: false,
}];
const SKILLS_7: &[CraftSkillReq] = &[CraftSkillReq {
    skill: Skill::Tailoring,
    min: 72,
    max: 322,
}];
const RES_7: &[CraftRes] = &[CraftRes {
    graphic: Graphic(0x1766),
    hue: Hue(0x0000),
    amount: 15,
    name: Text::Cliloc(1044455),
    message: Text::Cliloc(1044287),
    from_axis: false,
}];
const SKILLS_8: &[CraftSkillReq] = &[CraftSkillReq {
    skill: Skill::Tailoring,
    min: 62,
    max: 312,
}];
const RES_8: &[CraftRes] = &[CraftRes {
    graphic: Graphic(0x1766),
    hue: Hue(0x0000),
    amount: 11,
    name: Text::Cliloc(1044455),
    message: Text::Cliloc(1044287),
    from_axis: false,
}];
const SKILLS_9: &[CraftSkillReq] = &[CraftSkillReq {
    skill: Skill::Tailoring,
    min: 62,
    max: 312,
}];
const RES_9: &[CraftRes] = &[CraftRes {
    graphic: Graphic(0x1766),
    hue: Hue(0x0000),
    amount: 12,
    name: Text::Cliloc(1044455),
    message: Text::Cliloc(1044287),
    from_axis: false,
}];
const SKILLS_10: &[CraftSkillReq] = &[CraftSkillReq {
    skill: Skill::Tailoring,
    min: 62,
    max: 312,
}];
const RES_10: &[CraftRes] = &[CraftRes {
    graphic: Graphic(0x1766),
    hue: Hue(0x0000),
    amount: 12,
    name: Text::Cliloc(1044455),
    message: Text::Cliloc(1044287),
    from_axis: false,
}];
const SKILLS_11: &[CraftSkillReq] = &[CraftSkillReq {
    skill: Skill::Tailoring,
    min: 72,
    max: 322,
}];
const RES_11: &[CraftRes] = &[CraftRes {
    graphic: Graphic(0x1766),
    hue: Hue(0x0000),
    amount: 15,
    name: Text::Cliloc(1044455),
    message: Text::Cliloc(1044287),
    from_axis: false,
}];
const SKILLS_12: &[CraftSkillReq] = &[CraftSkillReq {
    skill: Skill::Tailoring,
    min: 100,
    max: 350,
}];
const RES_12: &[CraftRes] = &[CraftRes {
    graphic: Graphic(0x1766),
    hue: Hue(0x0000),
    amount: 5,
    name: Text::Cliloc(1044455),
    message: Text::Cliloc(1044287),
    from_axis: false,
}];
const SKILLS_13: &[CraftSkillReq] = &[CraftSkillReq {
    skill: Skill::Tailoring,
    min: 800,
    max: 1050,
}];
const RES_13: &[CraftRes] = &[CraftRes {
    graphic: Graphic(0x1766),
    hue: Hue(0x0000),
    amount: 13,
    name: Text::Cliloc(1044455),
    message: Text::Cliloc(1044287),
    from_axis: false,
}];
const SKILLS_14: &[CraftSkillReq] = &[CraftSkillReq {
    skill: Skill::Tailoring,
    min: 600,
    max: 850,
}];
const RES_14: &[CraftRes] = &[CraftRes {
    graphic: Graphic(0x1766),
    hue: Hue(0x0000),
    amount: 12,
    name: Text::Cliloc(1044455),
    message: Text::Cliloc(1044287),
    from_axis: false,
}];
const SKILLS_15: &[CraftSkillReq] = &[CraftSkillReq {
    skill: Skill::Tailoring,
    min: 750,
    max: 1000,
}];
const RES_15: &[CraftRes] = &[CraftRes {
    graphic: Graphic(0x1766),
    hue: Hue(0x0000),
    amount: 12,
    name: Text::Cliloc(1044455),
    message: Text::Cliloc(1044287),
    from_axis: false,
}];
const SKILLS_16: &[CraftSkillReq] = &[CraftSkillReq {
    skill: Skill::Tailoring,
    min: 775,
    max: 1025,
}];
const RES_16: &[CraftRes] = &[CraftRes {
    graphic: Graphic(0x1766),
    hue: Hue(0x0000),
    amount: 15,
    name: Text::Cliloc(1044455),
    message: Text::Cliloc(1044287),
    from_axis: false,
}];
const SKILLS_17: &[CraftSkillReq] = &[CraftSkillReq {
    skill: Skill::Tailoring,
    min: 775,
    max: 1025,
}];
const RES_17: &[CraftRes] = &[CraftRes {
    graphic: Graphic(0x1766),
    hue: Hue(0x0000),
    amount: 15,
    name: Text::Cliloc(1044455),
    message: Text::Cliloc(1044287),
    from_axis: false,
}];
const SKILLS_18: &[CraftSkillReq] = &[CraftSkillReq {
    skill: Skill::Tailoring,
    min: 825,
    max: 1075,
}];
const RES_18: &[CraftRes] = &[CraftRes {
    graphic: Graphic(0x1766),
    hue: Hue(0x0000),
    amount: 12,
    name: Text::Cliloc(1044455),
    message: Text::Cliloc(1044287),
    from_axis: false,
}];
const SKILLS_19: &[CraftSkillReq] = &[CraftSkillReq {
    skill: Skill::Tailoring,
    min: 825,
    max: 1075,
}];
const RES_19: &[CraftRes] = &[CraftRes {
    graphic: Graphic(0x1766),
    hue: Hue(0x0000),
    amount: 12,
    name: Text::Cliloc(1044455),
    message: Text::Cliloc(1044287),
    from_axis: false,
}];
const SKILLS_20: &[CraftSkillReq] = &[CraftSkillReq {
    skill: Skill::Tailoring,
    min: 0,
    max: 250,
}];
const RES_20: &[CraftRes] = &[CraftRes {
    graphic: Graphic(0x1766),
    hue: Hue(0x0000),
    amount: 8,
    name: Text::Cliloc(1044455),
    message: Text::Cliloc(1044287),
    from_axis: false,
}];
const SKILLS_21: &[CraftSkillReq] = &[CraftSkillReq {
    skill: Skill::Tailoring,
    min: 207,
    max: 457,
}];
const RES_21: &[CraftRes] = &[CraftRes {
    graphic: Graphic(0x1766),
    hue: Hue(0x0000),
    amount: 8,
    name: Text::Cliloc(1044455),
    message: Text::Cliloc(1044287),
    from_axis: false,
}];
const SKILLS_22: &[CraftSkillReq] = &[CraftSkillReq {
    skill: Skill::Tailoring,
    min: 248,
    max: 498,
}];
const RES_22: &[CraftRes] = &[CraftRes {
    graphic: Graphic(0x1766),
    hue: Hue(0x0000),
    amount: 8,
    name: Text::Cliloc(1044455),
    message: Text::Cliloc(1044287),
    from_axis: false,
}];
const SKILLS_23: &[CraftSkillReq] = &[CraftSkillReq {
    skill: Skill::Tailoring,
    min: 0,
    max: 250,
}];
const RES_23: &[CraftRes] = &[CraftRes {
    graphic: Graphic(0x1766),
    hue: Hue(0x0000),
    amount: 12,
    name: Text::Cliloc(1044455),
    message: Text::Cliloc(1044287),
    from_axis: false,
}];
const SKILLS_24: &[CraftSkillReq] = &[CraftSkillReq {
    skill: Skill::Tailoring,
    min: 82,
    max: 332,
}];
const RES_24: &[CraftRes] = &[CraftRes {
    graphic: Graphic(0x1766),
    hue: Hue(0x0000),
    amount: 14,
    name: Text::Cliloc(1044455),
    message: Text::Cliloc(1044287),
    from_axis: false,
}];
const SKILLS_25: &[CraftSkillReq] = &[CraftSkillReq {
    skill: Skill::Tailoring,
    min: 124,
    max: 374,
}];
const RES_25: &[CraftRes] = &[CraftRes {
    graphic: Graphic(0x1766),
    hue: Hue(0x0000),
    amount: 10,
    name: Text::Cliloc(1044455),
    message: Text::Cliloc(1044287),
    from_axis: false,
}];
const SKILLS_26: &[CraftSkillReq] = &[CraftSkillReq {
    skill: Skill::Tailoring,
    min: 331,
    max: 581,
}];
const RES_26: &[CraftRes] = &[CraftRes {
    graphic: Graphic(0x1766),
    hue: Hue(0x0000),
    amount: 12,
    name: Text::Cliloc(1044455),
    message: Text::Cliloc(1044287),
    from_axis: false,
}];
const SKILLS_27: &[CraftSkillReq] = &[CraftSkillReq {
    skill: Skill::Tailoring,
    min: 414,
    max: 664,
}];
const RES_27: &[CraftRes] = &[CraftRes {
    graphic: Graphic(0x1766),
    hue: Hue(0x0000),
    amount: 14,
    name: Text::Cliloc(1044455),
    message: Text::Cliloc(1044287),
    from_axis: false,
}];
const SKILLS_28: &[CraftSkillReq] = &[CraftSkillReq {
    skill: Skill::Tailoring,
    min: 539,
    max: 789,
}];
const RES_28: &[CraftRes] = &[CraftRes {
    graphic: Graphic(0x1766),
    hue: Hue(0x0000),
    amount: 16,
    name: Text::Cliloc(1044455),
    message: Text::Cliloc(1044287),
    from_axis: false,
}];
const SKILLS_29: &[CraftSkillReq] = &[CraftSkillReq {
    skill: Skill::Tailoring,
    min: 82,
    max: 332,
}];
const RES_29: &[CraftRes] = &[CraftRes {
    graphic: Graphic(0x1766),
    hue: Hue(0x0000),
    amount: 24,
    name: Text::Cliloc(1044455),
    message: Text::Cliloc(1044287),
    from_axis: false,
}];
const SKILLS_30: &[CraftSkillReq] = &[CraftSkillReq {
    skill: Skill::Tailoring,
    min: 350,
    max: 600,
}];
const RES_30: &[CraftRes] = &[CraftRes {
    graphic: Graphic(0x1766),
    hue: Hue(0x0000),
    amount: 13,
    name: Text::Cliloc(1044455),
    message: Text::Cliloc(1044287),
    from_axis: false,
}];
const SKILLS_31: &[CraftSkillReq] = &[CraftSkillReq {
    skill: Skill::Tailoring,
    min: 375,
    max: 625,
}];
const RES_31: &[CraftRes] = &[CraftRes {
    graphic: Graphic(0x1766),
    hue: Hue(0x0000),
    amount: 16,
    name: Text::Cliloc(1044455),
    message: Text::Cliloc(1044287),
    from_axis: false,
}];
const SKILLS_32: &[CraftSkillReq] = &[CraftSkillReq {
    skill: Skill::Tailoring,
    min: 260,
    max: 510,
}];
const RES_32: &[CraftRes] = &[CraftRes {
    graphic: Graphic(0x1766),
    hue: Hue(0x0000),
    amount: 16,
    name: Text::Cliloc(1044455),
    message: Text::Cliloc(1044287),
    from_axis: false,
}];
const SKILLS_33: &[CraftSkillReq] = &[CraftSkillReq {
    skill: Skill::Tailoring,
    min: 750,
    max: 1000,
}];
const RES_33: &[CraftRes] = &[CraftRes {
    graphic: Graphic(0x1766),
    hue: Hue(0x0000),
    amount: 12,
    name: Text::Cliloc(1044455),
    message: Text::Cliloc(1044287),
    from_axis: false,
}];
const SKILLS_34: &[CraftSkillReq] = &[CraftSkillReq {
    skill: Skill::Tailoring,
    min: 750,
    max: 1000,
}];
const RES_34: &[CraftRes] = &[CraftRes {
    graphic: Graphic(0x1766),
    hue: Hue(0x0000),
    amount: 15,
    name: Text::Cliloc(1044455),
    message: Text::Cliloc(1044287),
    from_axis: false,
}];
const SKILLS_35: &[CraftSkillReq] = &[CraftSkillReq {
    skill: Skill::Tailoring,
    min: 400,
    max: 650,
}];
const RES_35: &[CraftRes] = &[CraftRes {
    graphic: Graphic(0x1766),
    hue: Hue(0x0000),
    amount: 14,
    name: Text::Cliloc(1044455),
    message: Text::Cliloc(1044287),
    from_axis: false,
}];
const SKILLS_36: &[CraftSkillReq] = &[CraftSkillReq {
    skill: Skill::Tailoring,
    min: 500,
    max: 750,
}];
const RES_36: &[CraftRes] = &[CraftRes {
    graphic: Graphic(0x1766),
    hue: Hue(0x0000),
    amount: 16,
    name: Text::Cliloc(1044455),
    message: Text::Cliloc(1044287),
    from_axis: false,
}];
const SKILLS_37: &[CraftSkillReq] = &[CraftSkillReq {
    skill: Skill::Tailoring,
    min: 500,
    max: 750,
}];
const RES_37: &[CraftRes] = &[CraftRes {
    graphic: Graphic(0x1766),
    hue: Hue(0x0000),
    amount: 16,
    name: Text::Cliloc(1044455),
    message: Text::Cliloc(1044287),
    from_axis: false,
}];
const SKILLS_38: &[CraftSkillReq] = &[CraftSkillReq {
    skill: Skill::Tailoring,
    min: 300,
    max: 550,
}];
const RES_38: &[CraftRes] = &[CraftRes {
    graphic: Graphic(0x1766),
    hue: Hue(0x0000),
    amount: 12,
    name: Text::Cliloc(1044455),
    message: Text::Cliloc(1044287),
    from_axis: false,
}];
const SKILLS_39: &[CraftSkillReq] = &[CraftSkillReq {
    skill: Skill::Tailoring,
    min: 248,
    max: 498,
}];
const RES_39: &[CraftRes] = &[CraftRes {
    graphic: Graphic(0x1766),
    hue: Hue(0x0000),
    amount: 6,
    name: Text::Cliloc(1044455),
    message: Text::Cliloc(1044287),
    from_axis: false,
}];
const SKILLS_40: &[CraftSkillReq] = &[CraftSkillReq {
    skill: Skill::Tailoring,
    min: 248,
    max: 498,
}];
const RES_40: &[CraftRes] = &[CraftRes {
    graphic: Graphic(0x1766),
    hue: Hue(0x0000),
    amount: 8,
    name: Text::Cliloc(1044455),
    message: Text::Cliloc(1044287),
    from_axis: false,
}];
const SKILLS_41: &[CraftSkillReq] = &[CraftSkillReq {
    skill: Skill::Tailoring,
    min: 207,
    max: 457,
}];
const RES_41: &[CraftRes] = &[CraftRes {
    graphic: Graphic(0x1766),
    hue: Hue(0x0000),
    amount: 8,
    name: Text::Cliloc(1044455),
    message: Text::Cliloc(1044287),
    from_axis: false,
}];
const SKILLS_42: &[CraftSkillReq] = &[CraftSkillReq {
    skill: Skill::Tailoring,
    min: 290,
    max: 540,
}];
const RES_42: &[CraftRes] = &[CraftRes {
    graphic: Graphic(0x1766),
    hue: Hue(0x0000),
    amount: 10,
    name: Text::Cliloc(1044455),
    message: Text::Cliloc(1044287),
    from_axis: false,
}];
const SKILLS_43: &[CraftSkillReq] = &[CraftSkillReq {
    skill: Skill::Tailoring,
    min: 350,
    max: 600,
}];
const RES_43: &[CraftRes] = &[CraftRes {
    graphic: Graphic(0x1766),
    hue: Hue(0x0000),
    amount: 12,
    name: Text::Cliloc(1044455),
    message: Text::Cliloc(1044287),
    from_axis: false,
}];
const SKILLS_44: &[CraftSkillReq] = &[CraftSkillReq {
    skill: Skill::Tailoring,
    min: 500,
    max: 750,
}];
const RES_44: &[CraftRes] = &[CraftRes {
    graphic: Graphic(0x1766),
    hue: Hue(0x0000),
    amount: 16,
    name: Text::Cliloc(1044455),
    message: Text::Cliloc(1044287),
    from_axis: false,
}];
const SKILLS_45: &[CraftSkillReq] = &[CraftSkillReq {
    skill: Skill::Tailoring,
    min: 500,
    max: 750,
}];
const RES_45: &[CraftRes] = &[CraftRes {
    graphic: Graphic(0x1766),
    hue: Hue(0x0000),
    amount: 16,
    name: Text::Cliloc(1044455),
    message: Text::Cliloc(1044287),
    from_axis: false,
}];
const SKILLS_46: &[CraftSkillReq] = &[CraftSkillReq {
    skill: Skill::Tailoring,
    min: 800,
    max: 1050,
}];
const RES_46: &[CraftRes] = &[CraftRes {
    graphic: Graphic(0x1766),
    hue: Hue(0x0000),
    amount: 10,
    name: Text::Cliloc(1044455),
    message: Text::Cliloc(1044287),
    from_axis: false,
}];
const SKILLS_47: &[CraftSkillReq] = &[CraftSkillReq {
    skill: Skill::Tailoring,
    min: 800,
    max: 1050,
}];
const RES_47: &[CraftRes] = &[CraftRes {
    graphic: Graphic(0x1766),
    hue: Hue(0x0000),
    amount: 10,
    name: Text::Cliloc(1044455),
    message: Text::Cliloc(1044287),
    from_axis: false,
}];
const SKILLS_48: &[CraftSkillReq] = &[CraftSkillReq {
    skill: Skill::Tailoring,
    min: 800,
    max: 1050,
}];
const RES_48: &[CraftRes] = &[CraftRes {
    graphic: Graphic(0x1766),
    hue: Hue(0x0000),
    amount: 12,
    name: Text::Cliloc(1044455),
    message: Text::Cliloc(1044287),
    from_axis: false,
}];
const SKILLS_49: &[CraftSkillReq] = &[CraftSkillReq {
    skill: Skill::Tailoring,
    min: 800,
    max: 1050,
}];
const RES_49: &[CraftRes] = &[CraftRes {
    graphic: Graphic(0x1766),
    hue: Hue(0x0000),
    amount: 30,
    name: Text::Cliloc(1044455),
    message: Text::Cliloc(1044287),
    from_axis: false,
}];
const SKILLS_50: &[CraftSkillReq] = &[CraftSkillReq {
    skill: Skill::Tailoring,
    min: 800,
    max: 1050,
}];
const RES_50: &[CraftRes] = &[CraftRes {
    graphic: Graphic(0x1766),
    hue: Hue(0x0000),
    amount: 30,
    name: Text::Cliloc(1044455),
    message: Text::Cliloc(1044287),
    from_axis: false,
}];
const SKILLS_51: &[CraftSkillReq] = &[CraftSkillReq {
    skill: Skill::Tailoring,
    min: 800,
    max: 1050,
}];
const RES_51: &[CraftRes] = &[CraftRes {
    graphic: Graphic(0x1766),
    hue: Hue(0x0000),
    amount: 10,
    name: Text::Cliloc(1044455),
    message: Text::Cliloc(1044287),
    from_axis: false,
}];
const SKILLS_52: &[CraftSkillReq] = &[CraftSkillReq {
    skill: Skill::Tailoring,
    min: 41,
    max: 291,
}];
const RES_52: &[CraftRes] = &[CraftRes {
    graphic: Graphic(0x1766),
    hue: Hue(0x0000),
    amount: 4,
    name: Text::Cliloc(1044455),
    message: Text::Cliloc(1044287),
    from_axis: false,
}];
const SKILLS_53: &[CraftSkillReq] = &[CraftSkillReq {
    skill: Skill::Tailoring,
    min: 207,
    max: 457,
}];
const RES_53: &[CraftRes] = &[CraftRes {
    graphic: Graphic(0x1766),
    hue: Hue(0x0000),
    amount: 6,
    name: Text::Cliloc(1044455),
    message: Text::Cliloc(1044287),
    from_axis: false,
}];
const SKILLS_54: &[CraftSkillReq] = &[CraftSkillReq {
    skill: Skill::Tailoring,
    min: 290,
    max: 540,
}];
const RES_54: &[CraftRes] = &[CraftRes {
    graphic: Graphic(0x1766),
    hue: Hue(0x0000),
    amount: 10,
    name: Text::Cliloc(1044455),
    message: Text::Cliloc(1044287),
    from_axis: false,
}];
const SKILLS_55: &[CraftSkillReq] = &[CraftSkillReq {
    skill: Skill::Tailoring,
    min: 200,
    max: 450,
}];
const RES_55: &[CraftRes] = &[CraftRes {
    graphic: Graphic(0x1766),
    hue: Hue(0x0000),
    amount: 6,
    name: Text::Cliloc(1044455),
    message: Text::Cliloc(1044287),
    from_axis: false,
}];
const SKILLS_56: &[CraftSkillReq] = &[CraftSkillReq {
    skill: Skill::Tailoring,
    min: 750,
    max: 1000,
}];
const RES_56: &[CraftRes] = &[
    CraftRes {
        graphic: Graphic(0x0F7E),
        hue: Hue(0x0000),
        amount: 1,
        name: Text::Cliloc(1049064),
        message: Text::Cliloc(1049063),
        from_axis: false,
    },
    CraftRes {
        graphic: Graphic(0x1081),
        hue: Hue(0x0000),
        amount: 6,
        name: Text::Cliloc(1044462),
        message: Text::Cliloc(1044463),
        from_axis: true,
    },
    CraftRes {
        graphic: Graphic(0x0FA0),
        hue: Hue(0x0000),
        amount: 2,
        name: Text::Cliloc(1073462),
        message: Text::Cliloc(1073463),
        from_axis: false,
    },
    CraftRes {
        graphic: Graphic(0x0FA9),
        hue: Hue(0x0000),
        amount: 1,
        name: Text::Cliloc(1024009),
        message: Text::Cliloc(1044253),
        from_axis: false,
    },
];
const SKILLS_57: &[CraftSkillReq] = &[CraftSkillReq {
    skill: Skill::Tailoring,
    min: 746,
    max: 996,
}];
const RES_57: &[CraftRes] = &[CraftRes {
    graphic: Graphic(0x1766),
    hue: Hue(0x0000),
    amount: 1,
    name: Text::Cliloc(1044455),
    message: Text::Cliloc(1044287),
    from_axis: false,
}];
const SKILLS_58: &[CraftSkillReq] = &[CraftSkillReq {
    skill: Skill::Tailoring,
    min: 550,
    max: 800,
}];
const RES_58: &[CraftRes] = &[CraftRes {
    graphic: Graphic(0x1766),
    hue: Hue(0x0000),
    amount: 25,
    name: Text::Cliloc(1044455),
    message: Text::Cliloc(1044287),
    from_axis: false,
}];
const SKILLS_59: &[CraftSkillReq] = &[CraftSkillReq {
    skill: Skill::Tailoring,
    min: 550,
    max: 800,
}];
const RES_59: &[CraftRes] = &[CraftRes {
    graphic: Graphic(0x1766),
    hue: Hue(0x0000),
    amount: 25,
    name: Text::Cliloc(1044455),
    message: Text::Cliloc(1044287),
    from_axis: false,
}];
const SKILLS_60: &[CraftSkillReq] = &[CraftSkillReq {
    skill: Skill::Tailoring,
    min: 550,
    max: 800,
}];
const RES_60: &[CraftRes] = &[CraftRes {
    graphic: Graphic(0x1766),
    hue: Hue(0x0000),
    amount: 25,
    name: Text::Cliloc(1044455),
    message: Text::Cliloc(1044287),
    from_axis: false,
}];
const SKILLS_61: &[CraftSkillReq] = &[CraftSkillReq {
    skill: Skill::Tailoring,
    min: 550,
    max: 800,
}];
const RES_61: &[CraftRes] = &[CraftRes {
    graphic: Graphic(0x1766),
    hue: Hue(0x0000),
    amount: 25,
    name: Text::Cliloc(1044455),
    message: Text::Cliloc(1044287),
    from_axis: false,
}];
const SKILLS_62: &[CraftSkillReq] = &[CraftSkillReq {
    skill: Skill::Tailoring,
    min: 550,
    max: 800,
}];
const RES_62: &[CraftRes] = &[CraftRes {
    graphic: Graphic(0x1766),
    hue: Hue(0x0000),
    amount: 25,
    name: Text::Cliloc(1044455),
    message: Text::Cliloc(1044287),
    from_axis: false,
}];
const SKILLS_63: &[CraftSkillReq] = &[CraftSkillReq {
    skill: Skill::Tailoring,
    min: 550,
    max: 800,
}];
const RES_63: &[CraftRes] = &[CraftRes {
    graphic: Graphic(0x1766),
    hue: Hue(0x0000),
    amount: 25,
    name: Text::Cliloc(1044455),
    message: Text::Cliloc(1044287),
    from_axis: false,
}];
const SKILLS_64: &[CraftSkillReq] = &[CraftSkillReq {
    skill: Skill::Tailoring,
    min: 550,
    max: 800,
}];
const RES_64: &[CraftRes] = &[CraftRes {
    graphic: Graphic(0x1766),
    hue: Hue(0x0000),
    amount: 25,
    name: Text::Cliloc(1044455),
    message: Text::Cliloc(1044287),
    from_axis: false,
}];
const SKILLS_65: &[CraftSkillReq] = &[CraftSkillReq {
    skill: Skill::Tailoring,
    min: 550,
    max: 800,
}];
const RES_65: &[CraftRes] = &[CraftRes {
    graphic: Graphic(0x1766),
    hue: Hue(0x0000),
    amount: 25,
    name: Text::Cliloc(1044455),
    message: Text::Cliloc(1044287),
    from_axis: false,
}];
const SKILLS_66: &[CraftSkillReq] = &[CraftSkillReq {
    skill: Skill::Tailoring,
    min: 800,
    max: 1050,
}];
const RES_66: &[CraftRes] = &[CraftRes {
    graphic: Graphic(0x1081),
    hue: Hue(0x0000),
    amount: 15,
    name: Text::Cliloc(1044462),
    message: Text::Cliloc(1044463),
    from_axis: true,
}];
const SKILLS_67: &[CraftSkillReq] = &[CraftSkillReq {
    skill: Skill::Tailoring,
    min: 500,
    max: 750,
}];
const RES_67: &[CraftRes] = &[CraftRes {
    graphic: Graphic(0x1766),
    hue: Hue(0x0000),
    amount: 12,
    name: Text::Cliloc(1044455),
    message: Text::Cliloc(1044287),
    from_axis: false,
}];
const SKILLS_68: &[CraftSkillReq] = &[CraftSkillReq {
    skill: Skill::Tailoring,
    min: 700,
    max: 950,
}];
const RES_68: &[CraftRes] = &[CraftRes {
    graphic: Graphic(0x1766),
    hue: Hue(0x0000),
    amount: 10,
    name: Text::Cliloc(1044455),
    message: Text::Cliloc(1044287),
    from_axis: false,
}];
const SKILLS_69: &[CraftSkillReq] = &[CraftSkillReq {
    skill: Skill::Tailoring,
    min: 200,
    max: 450,
}];
const RES_69: &[CraftRes] = &[CraftRes {
    graphic: Graphic(0x1766),
    hue: Hue(0x0000),
    amount: 6,
    name: Text::Cliloc(1044455),
    message: Text::Cliloc(1044287),
    from_axis: false,
}];
const SKILLS_70: &[CraftSkillReq] = &[CraftSkillReq {
    skill: Skill::Tailoring,
    min: 124,
    max: 374,
}];
const RES_70: &[CraftRes] = &[CraftRes {
    graphic: Graphic(0x1081),
    hue: Hue(0x0000),
    amount: 4,
    name: Text::Cliloc(1044462),
    message: Text::Cliloc(1044463),
    from_axis: true,
}];
const SKILLS_71: &[CraftSkillReq] = &[CraftSkillReq {
    skill: Skill::Tailoring,
    min: 165,
    max: 415,
}];
const RES_71: &[CraftRes] = &[CraftRes {
    graphic: Graphic(0x1081),
    hue: Hue(0x0000),
    amount: 6,
    name: Text::Cliloc(1044462),
    message: Text::Cliloc(1044463),
    from_axis: true,
}];
const SKILLS_72: &[CraftSkillReq] = &[CraftSkillReq {
    skill: Skill::Tailoring,
    min: 331,
    max: 581,
}];
const RES_72: &[CraftRes] = &[CraftRes {
    graphic: Graphic(0x1081),
    hue: Hue(0x0000),
    amount: 8,
    name: Text::Cliloc(1044462),
    message: Text::Cliloc(1044463),
    from_axis: true,
}];
const SKILLS_73: &[CraftSkillReq] = &[CraftSkillReq {
    skill: Skill::Tailoring,
    min: 414,
    max: 664,
}];
const RES_73: &[CraftRes] = &[CraftRes {
    graphic: Graphic(0x1081),
    hue: Hue(0x0000),
    amount: 10,
    name: Text::Cliloc(1044462),
    message: Text::Cliloc(1044463),
    from_axis: true,
}];
const SKILLS_74: &[CraftSkillReq] = &[CraftSkillReq {
    skill: Skill::Tailoring,
    min: 539,
    max: 789,
}];
const RES_74: &[CraftRes] = &[CraftRes {
    graphic: Graphic(0x1081),
    hue: Hue(0x0000),
    amount: 4,
    name: Text::Cliloc(1044462),
    message: Text::Cliloc(1044463),
    from_axis: true,
}];
const SKILLS_75: &[CraftSkillReq] = &[CraftSkillReq {
    skill: Skill::Tailoring,
    min: 62,
    max: 312,
}];
const RES_75: &[CraftRes] = &[CraftRes {
    graphic: Graphic(0x1081),
    hue: Hue(0x0000),
    amount: 2,
    name: Text::Cliloc(1044462),
    message: Text::Cliloc(1044463),
    from_axis: true,
}];
const SKILLS_76: &[CraftSkillReq] = &[CraftSkillReq {
    skill: Skill::Tailoring,
    min: 518,
    max: 768,
}];
const RES_76: &[CraftRes] = &[CraftRes {
    graphic: Graphic(0x1081),
    hue: Hue(0x0000),
    amount: 3,
    name: Text::Cliloc(1044462),
    message: Text::Cliloc(1044463),
    from_axis: true,
}];
const SKILLS_77: &[CraftSkillReq] = &[CraftSkillReq {
    skill: Skill::Tailoring,
    min: 539,
    max: 789,
}];
const RES_77: &[CraftRes] = &[CraftRes {
    graphic: Graphic(0x1081),
    hue: Hue(0x0000),
    amount: 4,
    name: Text::Cliloc(1044462),
    message: Text::Cliloc(1044463),
    from_axis: true,
}];
const SKILLS_78: &[CraftSkillReq] = &[CraftSkillReq {
    skill: Skill::Tailoring,
    min: 663,
    max: 913,
}];
const RES_78: &[CraftRes] = &[CraftRes {
    graphic: Graphic(0x1081),
    hue: Hue(0x0000),
    amount: 10,
    name: Text::Cliloc(1044462),
    message: Text::Cliloc(1044463),
    from_axis: true,
}];
const SKILLS_79: &[CraftSkillReq] = &[CraftSkillReq {
    skill: Skill::Tailoring,
    min: 705,
    max: 955,
}];
const RES_79: &[CraftRes] = &[CraftRes {
    graphic: Graphic(0x1081),
    hue: Hue(0x0000),
    amount: 12,
    name: Text::Cliloc(1044462),
    message: Text::Cliloc(1044463),
    from_axis: true,
}];
const SKILLS_80: &[CraftSkillReq] = &[CraftSkillReq {
    skill: Skill::Tailoring,
    min: 450,
    max: 700,
}];
const RES_80: &[CraftRes] = &[CraftRes {
    graphic: Graphic(0x1081),
    hue: Hue(0x0000),
    amount: 4,
    name: Text::Cliloc(1044462),
    message: Text::Cliloc(1044463),
    from_axis: true,
}];
const SKILLS_81: &[CraftSkillReq] = &[CraftSkillReq {
    skill: Skill::Tailoring,
    min: 800,
    max: 1050,
}];
const RES_81: &[CraftRes] = &[CraftRes {
    graphic: Graphic(0x1081),
    hue: Hue(0x0000),
    amount: 8,
    name: Text::Cliloc(1044462),
    message: Text::Cliloc(1044463),
    from_axis: true,
}];
const SKILLS_82: &[CraftSkillReq] = &[CraftSkillReq {
    skill: Skill::Tailoring,
    min: 750,
    max: 1000,
}];
const RES_82: &[CraftRes] = &[CraftRes {
    graphic: Graphic(0x1081),
    hue: Hue(0x0000),
    amount: 12,
    name: Text::Cliloc(1044462),
    message: Text::Cliloc(1044463),
    from_axis: true,
}];
const SKILLS_83: &[CraftSkillReq] = &[CraftSkillReq {
    skill: Skill::Tailoring,
    min: 550,
    max: 800,
}];
const RES_83: &[CraftRes] = &[CraftRes {
    graphic: Graphic(0x1081),
    hue: Hue(0x0000),
    amount: 5,
    name: Text::Cliloc(1044462),
    message: Text::Cliloc(1044463),
    from_axis: true,
}];
const SKILLS_84: &[CraftSkillReq] = &[CraftSkillReq {
    skill: Skill::Tailoring,
    min: 680,
    max: 930,
}];
const RES_84: &[CraftRes] = &[CraftRes {
    graphic: Graphic(0x1081),
    hue: Hue(0x0000),
    amount: 12,
    name: Text::Cliloc(1044462),
    message: Text::Cliloc(1044463),
    from_axis: true,
}];
const SKILLS_85: &[CraftSkillReq] = &[CraftSkillReq {
    skill: Skill::Tailoring,
    min: 680,
    max: 930,
}];
const RES_85: &[CraftRes] = &[CraftRes {
    graphic: Graphic(0x1081),
    hue: Hue(0x0000),
    amount: 12,
    name: Text::Cliloc(1044462),
    message: Text::Cliloc(1044463),
    from_axis: true,
}];
const SKILLS_86: &[CraftSkillReq] = &[CraftSkillReq {
    skill: Skill::Tailoring,
    min: 800,
    max: 1050,
}];
const RES_86: &[CraftRes] = &[CraftRes {
    graphic: Graphic(0x1081),
    hue: Hue(0x0000),
    amount: 13,
    name: Text::Cliloc(1044462),
    message: Text::Cliloc(1044463),
    from_axis: true,
}];
const SKILLS_87: &[CraftSkillReq] = &[CraftSkillReq {
    skill: Skill::Tailoring,
    min: 850,
    max: 1100,
}];
const RES_87: &[CraftRes] = &[CraftRes {
    graphic: Graphic(0x1081),
    hue: Hue(0x0000),
    amount: 13,
    name: Text::Cliloc(1044462),
    message: Text::Cliloc(1044463),
    from_axis: true,
}];
const SKILLS_88: &[CraftSkillReq] = &[CraftSkillReq {
    skill: Skill::Tailoring,
    min: 500,
    max: 750,
}];
const RES_88: &[CraftRes] = &[CraftRes {
    graphic: Graphic(0x1081),
    hue: Hue(0x0000),
    amount: 5,
    name: Text::Cliloc(1044462),
    message: Text::Cliloc(1044463),
    from_axis: true,
}];
const SKILLS_89: &[CraftSkillReq] = &[CraftSkillReq {
    skill: Skill::Tailoring,
    min: 650,
    max: 900,
}];
const RES_89: &[CraftRes] = &[CraftRes {
    graphic: Graphic(0x1081),
    hue: Hue(0x0000),
    amount: 12,
    name: Text::Cliloc(1044462),
    message: Text::Cliloc(1044463),
    from_axis: true,
}];
const SKILLS_90: &[CraftSkillReq] = &[CraftSkillReq {
    skill: Skill::Tailoring,
    min: 900,
    max: 1150,
}];
const RES_90: &[CraftRes] = &[CraftRes {
    graphic: Graphic(0x1081),
    hue: Hue(0x0000),
    amount: 14,
    name: Text::Cliloc(1044462),
    message: Text::Cliloc(1044463),
    from_axis: true,
}];
const SKILLS_91: &[CraftSkillReq] = &[CraftSkillReq {
    skill: Skill::Tailoring,
    min: 750,
    max: 1000,
}];
const RES_91: &[CraftRes] = &[CraftRes {
    graphic: Graphic(0x1081),
    hue: Hue(0x0000),
    amount: 15,
    name: Text::Cliloc(1044462),
    message: Text::Cliloc(1044463),
    from_axis: true,
}];
const SKILLS_92: &[CraftSkillReq] = &[CraftSkillReq {
    skill: Skill::Tailoring,
    min: 600,
    max: 850,
}];
const RES_92: &[CraftRes] = &[CraftRes {
    graphic: Graphic(0x1081),
    hue: Hue(0x0000),
    amount: 12,
    name: Text::Cliloc(1044462),
    message: Text::Cliloc(1044463),
    from_axis: true,
}];
const SKILLS_93: &[CraftSkillReq] = &[CraftSkillReq {
    skill: Skill::Tailoring,
    min: 600,
    max: 850,
}];
const RES_93: &[CraftRes] = &[CraftRes {
    graphic: Graphic(0x1081),
    hue: Hue(0x0000),
    amount: 10,
    name: Text::Cliloc(1044462),
    message: Text::Cliloc(1044463),
    from_axis: true,
}];
const SKILLS_94: &[CraftSkillReq] = &[CraftSkillReq {
    skill: Skill::Tailoring,
    min: 750,
    max: 1000,
}];
const RES_94: &[CraftRes] = &[CraftRes {
    graphic: Graphic(0x1081),
    hue: Hue(0x0000),
    amount: 15,
    name: Text::Cliloc(1044462),
    message: Text::Cliloc(1044463),
    from_axis: true,
}];
const SKILLS_95: &[CraftSkillReq] = &[CraftSkillReq {
    skill: Skill::Tailoring,
    min: 650,
    max: 900,
}];
const RES_95: &[CraftRes] = &[CraftRes {
    graphic: Graphic(0x1081),
    hue: Hue(0x0000),
    amount: 12,
    name: Text::Cliloc(1044462),
    message: Text::Cliloc(1044463),
    from_axis: true,
}];
const SKILLS_96: &[CraftSkillReq] = &[CraftSkillReq {
    skill: Skill::Tailoring,
    min: 700,
    max: 950,
}];
const RES_96: &[CraftRes] = &[CraftRes {
    graphic: Graphic(0x1081),
    hue: Hue(0x0000),
    amount: 12,
    name: Text::Cliloc(1044462),
    message: Text::Cliloc(1044463),
    from_axis: true,
}];
const SKILLS_97: &[CraftSkillReq] = &[CraftSkillReq {
    skill: Skill::Tailoring,
    min: 788,
    max: 1038,
}];
const RES_97: &[CraftRes] = &[CraftRes {
    graphic: Graphic(0x1081),
    hue: Hue(0x0000),
    amount: 6,
    name: Text::Cliloc(1044462),
    message: Text::Cliloc(1044463),
    from_axis: true,
}];
const SKILLS_98: &[CraftSkillReq] = &[CraftSkillReq {
    skill: Skill::Tailoring,
    min: 829,
    max: 1079,
}];
const RES_98: &[CraftRes] = &[CraftRes {
    graphic: Graphic(0x1081),
    hue: Hue(0x0000),
    amount: 8,
    name: Text::Cliloc(1044462),
    message: Text::Cliloc(1044463),
    from_axis: true,
}];
const SKILLS_99: &[CraftSkillReq] = &[CraftSkillReq {
    skill: Skill::Tailoring,
    min: 871,
    max: 1121,
}];
const RES_99: &[CraftRes] = &[CraftRes {
    graphic: Graphic(0x1081),
    hue: Hue(0x0000),
    amount: 10,
    name: Text::Cliloc(1044462),
    message: Text::Cliloc(1044463),
    from_axis: true,
}];
const SKILLS_100: &[CraftSkillReq] = &[CraftSkillReq {
    skill: Skill::Tailoring,
    min: 912,
    max: 1162,
}];
const RES_100: &[CraftRes] = &[CraftRes {
    graphic: Graphic(0x1081),
    hue: Hue(0x0000),
    amount: 12,
    name: Text::Cliloc(1044462),
    message: Text::Cliloc(1044463),
    from_axis: true,
}];
const SKILLS_101: &[CraftSkillReq] = &[CraftSkillReq {
    skill: Skill::Tailoring,
    min: 940,
    max: 1190,
}];
const RES_101: &[CraftRes] = &[CraftRes {
    graphic: Graphic(0x1081),
    hue: Hue(0x0000),
    amount: 14,
    name: Text::Cliloc(1044462),
    message: Text::Cliloc(1044463),
    from_axis: true,
}];
const SKILLS_102: &[CraftSkillReq] = &[CraftSkillReq {
    skill: Skill::Tailoring,
    min: 800,
    max: 1050,
}];
const RES_102: &[CraftRes] = &[CraftRes {
    graphic: Graphic(0x1081),
    hue: Hue(0x0000),
    amount: 8,
    name: Text::Cliloc(1044462),
    message: Text::Cliloc(1044463),
    from_axis: true,
}];
const SKILLS_103: &[CraftSkillReq] = &[CraftSkillReq {
    skill: Skill::Tailoring,
    min: 950,
    max: 1200,
}];
const RES_103: &[CraftRes] = &[CraftRes {
    graphic: Graphic(0x1081),
    hue: Hue(0x0000),
    amount: 14,
    name: Text::Cliloc(1044462),
    message: Text::Cliloc(1044463),
    from_axis: true,
}];
const SKILLS_104: &[CraftSkillReq] = &[CraftSkillReq {
    skill: Skill::Tailoring,
    min: 850,
    max: 1100,
}];
const RES_104: &[CraftRes] = &[CraftRes {
    graphic: Graphic(0x1081),
    hue: Hue(0x0000),
    amount: 8,
    name: Text::Cliloc(1044462),
    message: Text::Cliloc(1044463),
    from_axis: true,
}];
const SKILLS_105: &[CraftSkillReq] = &[CraftSkillReq {
    skill: Skill::Tailoring,
    min: 920,
    max: 1170,
}];
const RES_105: &[CraftRes] = &[CraftRes {
    graphic: Graphic(0x1081),
    hue: Hue(0x0000),
    amount: 14,
    name: Text::Cliloc(1044462),
    message: Text::Cliloc(1044463),
    from_axis: true,
}];
const SKILLS_106: &[CraftSkillReq] = &[CraftSkillReq {
    skill: Skill::Tailoring,
    min: 920,
    max: 1170,
}];
const RES_106: &[CraftRes] = &[CraftRes {
    graphic: Graphic(0x1081),
    hue: Hue(0x0000),
    amount: 14,
    name: Text::Cliloc(1044462),
    message: Text::Cliloc(1044463),
    from_axis: true,
}];
const SKILLS_107: &[CraftSkillReq] = &[CraftSkillReq {
    skill: Skill::Tailoring,
    min: 850,
    max: 1100,
}];
const RES_107: &[CraftRes] = &[CraftRes {
    graphic: Graphic(0x1081),
    hue: Hue(0x0000),
    amount: 15,
    name: Text::Cliloc(1044462),
    message: Text::Cliloc(1044463),
    from_axis: true,
}];
const SKILLS_108: &[CraftSkillReq] = &[CraftSkillReq {
    skill: Skill::Tailoring,
    min: 750,
    max: 1000,
}];
const RES_108: &[CraftRes] = &[CraftRes {
    graphic: Graphic(0x1081),
    hue: Hue(0x0000),
    amount: 12,
    name: Text::Cliloc(1044462),
    message: Text::Cliloc(1044463),
    from_axis: true,
}];
const SKILLS_109: &[CraftSkillReq] = &[CraftSkillReq {
    skill: Skill::Tailoring,
    min: 750,
    max: 1000,
}];
const RES_109: &[CraftRes] = &[CraftRes {
    graphic: Graphic(0x1081),
    hue: Hue(0x0000),
    amount: 10,
    name: Text::Cliloc(1044462),
    message: Text::Cliloc(1044463),
    from_axis: true,
}];
const SKILLS_110: &[CraftSkillReq] = &[CraftSkillReq {
    skill: Skill::Tailoring,
    min: 920,
    max: 1170,
}];
const RES_110: &[CraftRes] = &[CraftRes {
    graphic: Graphic(0x1081),
    hue: Hue(0x0000),
    amount: 15,
    name: Text::Cliloc(1044462),
    message: Text::Cliloc(1044463),
    from_axis: true,
}];
const SKILLS_111: &[CraftSkillReq] = &[CraftSkillReq {
    skill: Skill::Tailoring,
    min: 900,
    max: 1150,
}];
const RES_111: &[CraftRes] = &[CraftRes {
    graphic: Graphic(0x1081),
    hue: Hue(0x0000),
    amount: 12,
    name: Text::Cliloc(1044462),
    message: Text::Cliloc(1044463),
    from_axis: true,
}];
const SKILLS_112: &[CraftSkillReq] = &[CraftSkillReq {
    skill: Skill::Tailoring,
    min: 622,
    max: 872,
}];
const RES_112: &[CraftRes] = &[CraftRes {
    graphic: Graphic(0x1081),
    hue: Hue(0x0000),
    amount: 8,
    name: Text::Cliloc(1044462),
    message: Text::Cliloc(1044463),
    from_axis: true,
}];
const SKILLS_113: &[CraftSkillReq] = &[CraftSkillReq {
    skill: Skill::Tailoring,
    min: 580,
    max: 830,
}];
const RES_113: &[CraftRes] = &[CraftRes {
    graphic: Graphic(0x1081),
    hue: Hue(0x0000),
    amount: 6,
    name: Text::Cliloc(1044462),
    message: Text::Cliloc(1044463),
    from_axis: true,
}];
const SKILLS_114: &[CraftSkillReq] = &[CraftSkillReq {
    skill: Skill::Tailoring,
    min: 580,
    max: 830,
}];
const RES_114: &[CraftRes] = &[CraftRes {
    graphic: Graphic(0x1081),
    hue: Hue(0x0000),
    amount: 6,
    name: Text::Cliloc(1044462),
    message: Text::Cliloc(1044463),
    from_axis: true,
}];
const SKILLS_115: &[CraftSkillReq] = &[CraftSkillReq {
    skill: Skill::Tailoring,
    min: 829,
    max: 1079,
}];
const RES_115: &[CraftRes] = &[CraftRes {
    graphic: Graphic(0x1081),
    hue: Hue(0x0000),
    amount: 8,
    name: Text::Cliloc(1044462),
    message: Text::Cliloc(1044463),
    from_axis: true,
}];
const SKILLS_116: &[CraftSkillReq] = &[CraftSkillReq {
    skill: Skill::Tailoring,
    min: 622,
    max: 872,
}];
const RES_116: &[CraftRes] = &[CraftRes {
    graphic: Graphic(0x1081),
    hue: Hue(0x0000),
    amount: 8,
    name: Text::Cliloc(1044462),
    message: Text::Cliloc(1044463),
    from_axis: true,
}];
const SKILLS_117: &[CraftSkillReq] = &[CraftSkillReq {
    skill: Skill::Tailoring,
    min: 871,
    max: 1121,
}];
const RES_117: &[CraftRes] = &[CraftRes {
    graphic: Graphic(0x1081),
    hue: Hue(0x0000),
    amount: 10,
    name: Text::Cliloc(1044462),
    message: Text::Cliloc(1044463),
    from_axis: true,
}];
const SKILLS_118: &[CraftSkillReq] = &[CraftSkillReq {
    skill: Skill::Tailoring,
    min: 850,
    max: 1100,
}];
const RES_118: &[CraftRes] = &[
    CraftRes {
        graphic: Graphic(0x1081),
        hue: Hue(0x0000),
        amount: 4,
        name: Text::Cliloc(1044462),
        message: Text::Cliloc(1044463),
        from_axis: true,
    },
    CraftRes {
        graphic: Graphic(0x0F7E),
        hue: Hue(0x0000),
        amount: 2,
        name: Text::Cliloc(1049064),
        message: Text::Cliloc(1049063),
        from_axis: false,
    },
];
const SKILLS_119: &[CraftSkillReq] = &[CraftSkillReq {
    skill: Skill::Tailoring,
    min: 890,
    max: 1140,
}];
const RES_119: &[CraftRes] = &[
    CraftRes {
        graphic: Graphic(0x1081),
        hue: Hue(0x0000),
        amount: 6,
        name: Text::Cliloc(1044462),
        message: Text::Cliloc(1044463),
        from_axis: true,
    },
    CraftRes {
        graphic: Graphic(0x0F7E),
        hue: Hue(0x0000),
        amount: 2,
        name: Text::Cliloc(1049064),
        message: Text::Cliloc(1049063),
        from_axis: false,
    },
];
const SKILLS_120: &[CraftSkillReq] = &[CraftSkillReq {
    skill: Skill::Tailoring,
    min: 920,
    max: 1170,
}];
const RES_120: &[CraftRes] = &[
    CraftRes {
        graphic: Graphic(0x1081),
        hue: Hue(0x0000),
        amount: 8,
        name: Text::Cliloc(1044462),
        message: Text::Cliloc(1044463),
        from_axis: true,
    },
    CraftRes {
        graphic: Graphic(0x0F7E),
        hue: Hue(0x0000),
        amount: 4,
        name: Text::Cliloc(1049064),
        message: Text::Cliloc(1049063),
        from_axis: false,
    },
];
const SKILLS_121: &[CraftSkillReq] = &[CraftSkillReq {
    skill: Skill::Tailoring,
    min: 950,
    max: 1200,
}];
const RES_121: &[CraftRes] = &[
    CraftRes {
        graphic: Graphic(0x1081),
        hue: Hue(0x0000),
        amount: 10,
        name: Text::Cliloc(1044462),
        message: Text::Cliloc(1044463),
        from_axis: true,
    },
    CraftRes {
        graphic: Graphic(0x0F7E),
        hue: Hue(0x0000),
        amount: 6,
        name: Text::Cliloc(1049064),
        message: Text::Cliloc(1049063),
        from_axis: false,
    },
];
const SKILLS_122: &[CraftSkillReq] = &[CraftSkillReq {
    skill: Skill::Tailoring,
    min: 960,
    max: 1210,
}];
const RES_122: &[CraftRes] = &[
    CraftRes {
        graphic: Graphic(0x1081),
        hue: Hue(0x0000),
        amount: 12,
        name: Text::Cliloc(1044462),
        message: Text::Cliloc(1044463),
        from_axis: true,
    },
    CraftRes {
        graphic: Graphic(0x0F7E),
        hue: Hue(0x0000),
        amount: 10,
        name: Text::Cliloc(1049064),
        message: Text::Cliloc(1049063),
        from_axis: false,
    },
];
const SKILLS_123: &[CraftSkillReq] = &[CraftSkillReq {
    skill: Skill::Tailoring,
    min: 900,
    max: 1150,
}];
const RES_123: &[CraftRes] = &[
    CraftRes {
        graphic: Graphic(0x1081),
        hue: Hue(0x0000),
        amount: 6,
        name: Text::Cliloc(1044462),
        message: Text::Cliloc(1044463),
        from_axis: true,
    },
    CraftRes {
        graphic: Graphic(0x0F7E),
        hue: Hue(0x0000),
        amount: 4,
        name: Text::Cliloc(1049064),
        message: Text::Cliloc(1049063),
        from_axis: false,
    },
];

/// Everything this trade can make.
pub const RECIPES: &[Recipe] = &[
    Recipe {
        graphic: Graphic(0x1544),
        name: Text::Cliloc(1025444),
        group: 1,
        skills: SKILLS_0,
        resources: RES_0,
        amount: 1,
        hue: Hue(0x0000),
        use_all_res: false,
        min_skill_offset: 0,
        markable: true,
        never_exceptional: false,
        always_exceptional: false,
        needs: Needs::none(),
    },
    Recipe {
        graphic: Graphic(0x1540),
        name: Text::Cliloc(1025440),
        group: 1,
        skills: SKILLS_1,
        resources: RES_1,
        amount: 1,
        hue: Hue(0x0000),
        use_all_res: false,
        min_skill_offset: 0,
        markable: true,
        never_exceptional: false,
        always_exceptional: false,
        needs: Needs::none(),
    },
    Recipe {
        graphic: Graphic(0x1713),
        name: Text::Cliloc(1025907),
        group: 1,
        skills: SKILLS_2,
        resources: RES_2,
        amount: 1,
        hue: Hue(0x0000),
        use_all_res: false,
        min_skill_offset: 0,
        markable: true,
        never_exceptional: false,
        always_exceptional: false,
        needs: Needs::none(),
    },
    Recipe {
        graphic: Graphic(0x1715),
        name: Text::Cliloc(1025909),
        group: 1,
        skills: SKILLS_3,
        resources: RES_3,
        amount: 1,
        hue: Hue(0x0000),
        use_all_res: false,
        min_skill_offset: 0,
        markable: true,
        never_exceptional: false,
        always_exceptional: false,
        needs: Needs::none(),
    },
    Recipe {
        graphic: Graphic(0x1714),
        name: Text::Cliloc(1025908),
        group: 1,
        skills: SKILLS_4,
        resources: RES_4,
        amount: 1,
        hue: Hue(0x0000),
        use_all_res: false,
        min_skill_offset: 0,
        markable: true,
        never_exceptional: false,
        always_exceptional: false,
        needs: Needs::none(),
    },
    Recipe {
        graphic: Graphic(0x1717),
        name: Text::Cliloc(1025911),
        group: 1,
        skills: SKILLS_5,
        resources: RES_5,
        amount: 1,
        hue: Hue(0x0000),
        use_all_res: false,
        min_skill_offset: 0,
        markable: true,
        never_exceptional: false,
        always_exceptional: false,
        needs: Needs::none(),
    },
    Recipe {
        graphic: Graphic(0x1716),
        name: Text::Cliloc(1025910),
        group: 1,
        skills: SKILLS_6,
        resources: RES_6,
        amount: 1,
        hue: Hue(0x0000),
        use_all_res: false,
        min_skill_offset: 0,
        markable: true,
        never_exceptional: false,
        always_exceptional: false,
        needs: Needs::none(),
    },
    Recipe {
        graphic: Graphic(0x1718),
        name: Text::Cliloc(1025912),
        group: 1,
        skills: SKILLS_7,
        resources: RES_7,
        amount: 1,
        hue: Hue(0x0000),
        use_all_res: false,
        min_skill_offset: 0,
        markable: true,
        never_exceptional: false,
        always_exceptional: false,
        needs: Needs::none(),
    },
    Recipe {
        graphic: Graphic(0x1719),
        name: Text::Cliloc(1025913),
        group: 1,
        skills: SKILLS_8,
        resources: RES_8,
        amount: 1,
        hue: Hue(0x0000),
        use_all_res: false,
        min_skill_offset: 0,
        markable: true,
        never_exceptional: false,
        always_exceptional: false,
        needs: Needs::none(),
    },
    Recipe {
        graphic: Graphic(0x171A),
        name: Text::Cliloc(1025914),
        group: 1,
        skills: SKILLS_9,
        resources: RES_9,
        amount: 1,
        hue: Hue(0x0000),
        use_all_res: false,
        min_skill_offset: 0,
        markable: true,
        never_exceptional: false,
        always_exceptional: false,
        needs: Needs::none(),
    },
    Recipe {
        graphic: Graphic(0x171B),
        name: Text::Cliloc(1025915),
        group: 1,
        skills: SKILLS_10,
        resources: RES_10,
        amount: 1,
        hue: Hue(0x0000),
        use_all_res: false,
        min_skill_offset: 0,
        markable: true,
        never_exceptional: false,
        always_exceptional: false,
        needs: Needs::none(),
    },
    Recipe {
        graphic: Graphic(0x171C),
        name: Text::Cliloc(1025916),
        group: 1,
        skills: SKILLS_11,
        resources: RES_11,
        amount: 1,
        hue: Hue(0x0000),
        use_all_res: false,
        min_skill_offset: 0,
        markable: true,
        never_exceptional: false,
        always_exceptional: false,
        needs: Needs::none(),
    },
    Recipe {
        graphic: Graphic(0x2306),
        name: Text::Cliloc(1028965),
        group: 1,
        skills: SKILLS_12,
        resources: RES_12,
        amount: 1,
        hue: Hue(0x0000),
        use_all_res: false,
        min_skill_offset: 0,
        markable: true,
        never_exceptional: false,
        always_exceptional: false,
        needs: Needs::none(),
    },
    Recipe {
        graphic: Graphic(0x278F),
        name: Text::Cliloc(1030202),
        group: 1,
        skills: SKILLS_13,
        resources: RES_13,
        amount: 1,
        hue: Hue(0x0000),
        use_all_res: false,
        min_skill_offset: 0,
        markable: true,
        never_exceptional: false,
        always_exceptional: false,
        needs: Needs::none(),
    },
    Recipe {
        graphic: Graphic(0x2798),
        name: Text::Cliloc(1030211),
        group: 1,
        skills: SKILLS_14,
        resources: RES_14,
        amount: 1,
        hue: Hue(0x0000),
        use_all_res: false,
        min_skill_offset: 0,
        markable: true,
        never_exceptional: false,
        always_exceptional: false,
        needs: Needs::none(),
    },
    Recipe {
        graphic: Graphic(0x141B),
        name: Text::Cliloc(1025147),
        group: 1,
        skills: SKILLS_15,
        resources: RES_15,
        amount: 1,
        hue: Hue(0x0000),
        use_all_res: false,
        min_skill_offset: 0,
        markable: true,
        never_exceptional: false,
        always_exceptional: false,
        needs: Needs::none(),
    },
    Recipe {
        graphic: Graphic(0x1545),
        name: Text::Cliloc(1025445),
        group: 1,
        skills: SKILLS_16,
        resources: RES_16,
        amount: 1,
        hue: Hue(0x0000),
        use_all_res: false,
        min_skill_offset: 0,
        markable: true,
        never_exceptional: false,
        always_exceptional: false,
        needs: Needs::none(),
    },
    Recipe {
        graphic: Graphic(0x1547),
        name: Text::Cliloc(1025447),
        group: 1,
        skills: SKILLS_17,
        resources: RES_17,
        amount: 1,
        hue: Hue(0x0000),
        use_all_res: false,
        min_skill_offset: 0,
        markable: true,
        never_exceptional: false,
        always_exceptional: false,
        needs: Needs::none(),
    },
    Recipe {
        graphic: Graphic(0x154B),
        name: Text::Cliloc(1025449),
        group: 1,
        skills: SKILLS_18,
        resources: RES_18,
        amount: 1,
        hue: Hue(0x0000),
        use_all_res: false,
        min_skill_offset: 0,
        markable: true,
        never_exceptional: false,
        always_exceptional: false,
        needs: Needs::none(),
    },
    Recipe {
        graphic: Graphic(0x1549),
        name: Text::Cliloc(1025451),
        group: 1,
        skills: SKILLS_19,
        resources: RES_19,
        amount: 1,
        hue: Hue(0x0000),
        use_all_res: false,
        min_skill_offset: 0,
        markable: true,
        never_exceptional: false,
        always_exceptional: false,
        needs: Needs::none(),
    },
    Recipe {
        graphic: Graphic(0x1F7B),
        name: Text::Cliloc(1028059),
        group: 2,
        skills: SKILLS_20,
        resources: RES_20,
        amount: 1,
        hue: Hue(0x0000),
        use_all_res: false,
        min_skill_offset: 0,
        markable: true,
        never_exceptional: false,
        always_exceptional: false,
        needs: Needs::none(),
    },
    Recipe {
        graphic: Graphic(0x1517),
        name: Text::Cliloc(1025399),
        group: 2,
        skills: SKILLS_21,
        resources: RES_21,
        amount: 1,
        hue: Hue(0x0000),
        use_all_res: false,
        min_skill_offset: 0,
        markable: true,
        never_exceptional: false,
        always_exceptional: false,
        needs: Needs::none(),
    },
    Recipe {
        graphic: Graphic(0x1EFD),
        name: Text::Cliloc(1027933),
        group: 2,
        skills: SKILLS_22,
        resources: RES_22,
        amount: 1,
        hue: Hue(0x0000),
        use_all_res: false,
        min_skill_offset: 0,
        markable: true,
        never_exceptional: false,
        always_exceptional: false,
        needs: Needs::none(),
    },
    Recipe {
        graphic: Graphic(0x1FA1),
        name: Text::Cliloc(1028097),
        group: 2,
        skills: SKILLS_23,
        resources: RES_23,
        amount: 1,
        hue: Hue(0x0000),
        use_all_res: false,
        min_skill_offset: 0,
        markable: true,
        never_exceptional: false,
        always_exceptional: false,
        needs: Needs::none(),
    },
    Recipe {
        graphic: Graphic(0x1FFD),
        name: Text::Cliloc(1028189),
        group: 2,
        skills: SKILLS_24,
        resources: RES_24,
        amount: 1,
        hue: Hue(0x0000),
        use_all_res: false,
        min_skill_offset: 0,
        markable: true,
        never_exceptional: false,
        always_exceptional: false,
        needs: Needs::none(),
    },
    Recipe {
        graphic: Graphic(0x1F01),
        name: Text::Cliloc(1027937),
        group: 2,
        skills: SKILLS_25,
        resources: RES_25,
        amount: 1,
        hue: Hue(0x0000),
        use_all_res: false,
        min_skill_offset: 0,
        markable: true,
        never_exceptional: false,
        always_exceptional: false,
        needs: Needs::none(),
    },
    Recipe {
        graphic: Graphic(0x1F00),
        name: Text::Cliloc(1027935),
        group: 2,
        skills: SKILLS_26,
        resources: RES_26,
        amount: 1,
        hue: Hue(0x0000),
        use_all_res: false,
        min_skill_offset: 0,
        markable: true,
        never_exceptional: false,
        always_exceptional: false,
        needs: Needs::none(),
    },
    Recipe {
        graphic: Graphic(0x1515),
        name: Text::Cliloc(1025397),
        group: 2,
        skills: SKILLS_27,
        resources: RES_27,
        amount: 1,
        hue: Hue(0x0000),
        use_all_res: false,
        min_skill_offset: 0,
        markable: true,
        never_exceptional: false,
        always_exceptional: false,
        needs: Needs::none(),
    },
    Recipe {
        graphic: Graphic(0x1F03),
        name: Text::Cliloc(1027939),
        group: 2,
        skills: SKILLS_28,
        resources: RES_28,
        amount: 1,
        hue: Hue(0x0000),
        use_all_res: false,
        min_skill_offset: 0,
        markable: true,
        never_exceptional: false,
        always_exceptional: false,
        needs: Needs::none(),
    },
    Recipe {
        graphic: Graphic(0x1F9F),
        name: Text::Cliloc(1028095),
        group: 2,
        skills: SKILLS_29,
        resources: RES_29,
        amount: 1,
        hue: Hue(0x0000),
        use_all_res: false,
        min_skill_offset: 0,
        markable: true,
        never_exceptional: false,
        always_exceptional: false,
        needs: Needs::none(),
    },
    Recipe {
        graphic: Graphic(0x230A),
        name: Text::Cliloc(1028969),
        group: 2,
        skills: SKILLS_30,
        resources: RES_30,
        amount: 1,
        hue: Hue(0x0000),
        use_all_res: false,
        min_skill_offset: 0,
        markable: true,
        never_exceptional: false,
        always_exceptional: false,
        needs: Needs::none(),
    },
    Recipe {
        graphic: Graphic(0x230E),
        name: Text::Cliloc(1028973),
        group: 2,
        skills: SKILLS_31,
        resources: RES_31,
        amount: 1,
        hue: Hue(0x0000),
        use_all_res: false,
        min_skill_offset: 0,
        markable: true,
        never_exceptional: false,
        always_exceptional: false,
        needs: Needs::none(),
    },
    Recipe {
        graphic: Graphic(0x2310),
        name: Text::Cliloc(1028975),
        group: 2,
        skills: SKILLS_32,
        resources: RES_32,
        amount: 1,
        hue: Hue(0x0000),
        use_all_res: false,
        min_skill_offset: 0,
        markable: true,
        never_exceptional: false,
        always_exceptional: false,
        needs: Needs::none(),
    },
    Recipe {
        graphic: Graphic(0x2794),
        name: Text::Cliloc(1030207),
        group: 2,
        skills: SKILLS_33,
        resources: RES_33,
        amount: 1,
        hue: Hue(0x0000),
        use_all_res: false,
        min_skill_offset: 0,
        markable: true,
        never_exceptional: false,
        always_exceptional: false,
        needs: Needs::none(),
    },
    Recipe {
        graphic: Graphic(0x2799),
        name: Text::Cliloc(1030212),
        group: 2,
        skills: SKILLS_34,
        resources: RES_34,
        amount: 1,
        hue: Hue(0x0000),
        use_all_res: false,
        min_skill_offset: 0,
        markable: true,
        never_exceptional: false,
        always_exceptional: false,
        needs: Needs::none(),
    },
    Recipe {
        graphic: Graphic(0x279C),
        name: Text::Cliloc(1030215),
        group: 2,
        skills: SKILLS_35,
        resources: RES_35,
        amount: 1,
        hue: Hue(0x0000),
        use_all_res: false,
        min_skill_offset: 0,
        markable: true,
        never_exceptional: false,
        always_exceptional: false,
        needs: Needs::none(),
    },
    Recipe {
        graphic: Graphic(0x2782),
        name: Text::Cliloc(1030189),
        group: 2,
        skills: SKILLS_36,
        resources: RES_36,
        amount: 1,
        hue: Hue(0x0000),
        use_all_res: false,
        min_skill_offset: 0,
        markable: true,
        never_exceptional: false,
        always_exceptional: false,
        needs: Needs::none(),
    },
    Recipe {
        graphic: Graphic(0x2783),
        name: Text::Cliloc(1030190),
        group: 2,
        skills: SKILLS_37,
        resources: RES_37,
        amount: 1,
        hue: Hue(0x0000),
        use_all_res: false,
        min_skill_offset: 0,
        markable: true,
        never_exceptional: false,
        always_exceptional: false,
        needs: Needs::none(),
    },
    Recipe {
        graphic: Graphic(0x27A1),
        name: Text::Cliloc(1030220),
        group: 2,
        skills: SKILLS_38,
        resources: RES_38,
        amount: 1,
        hue: Hue(0x0000),
        use_all_res: false,
        min_skill_offset: 0,
        markable: true,
        never_exceptional: false,
        always_exceptional: false,
        needs: Needs::none(),
    },
    Recipe {
        graphic: Graphic(0x152E),
        name: Text::Cliloc(1025422),
        group: 2,
        skills: SKILLS_39,
        resources: RES_39,
        amount: 1,
        hue: Hue(0x0000),
        use_all_res: false,
        min_skill_offset: 0,
        markable: true,
        never_exceptional: false,
        always_exceptional: false,
        needs: Needs::none(),
    },
    Recipe {
        graphic: Graphic(0x1539),
        name: Text::Cliloc(1025433),
        group: 2,
        skills: SKILLS_40,
        resources: RES_40,
        amount: 1,
        hue: Hue(0x0000),
        use_all_res: false,
        min_skill_offset: 0,
        markable: true,
        never_exceptional: false,
        always_exceptional: false,
        needs: Needs::none(),
    },
    Recipe {
        graphic: Graphic(0x1537),
        name: Text::Cliloc(1025431),
        group: 2,
        skills: SKILLS_41,
        resources: RES_41,
        amount: 1,
        hue: Hue(0x0000),
        use_all_res: false,
        min_skill_offset: 0,
        markable: true,
        never_exceptional: false,
        always_exceptional: false,
        needs: Needs::none(),
    },
    Recipe {
        graphic: Graphic(0x1516),
        name: Text::Cliloc(1025398),
        group: 2,
        skills: SKILLS_42,
        resources: RES_42,
        amount: 1,
        hue: Hue(0x0000),
        use_all_res: false,
        min_skill_offset: 0,
        markable: true,
        never_exceptional: false,
        always_exceptional: false,
        needs: Needs::none(),
    },
    Recipe {
        graphic: Graphic(0x230C),
        name: Text::Cliloc(1028971),
        group: 2,
        skills: SKILLS_43,
        resources: RES_43,
        amount: 1,
        hue: Hue(0x0000),
        use_all_res: false,
        min_skill_offset: 0,
        markable: true,
        never_exceptional: false,
        always_exceptional: false,
        needs: Needs::none(),
    },
    Recipe {
        graphic: Graphic(0x279A),
        name: Text::Cliloc(1030213),
        group: 2,
        skills: SKILLS_44,
        resources: RES_44,
        amount: 1,
        hue: Hue(0x0000),
        use_all_res: false,
        min_skill_offset: 0,
        markable: true,
        never_exceptional: false,
        always_exceptional: false,
        needs: Needs::none(),
    },
    Recipe {
        graphic: Graphic(0x279B),
        name: Text::Cliloc(1030214),
        group: 2,
        skills: SKILLS_45,
        resources: RES_45,
        amount: 1,
        hue: Hue(0x0000),
        use_all_res: false,
        min_skill_offset: 0,
        markable: true,
        never_exceptional: false,
        always_exceptional: false,
        needs: Needs::none(),
    },
    Recipe {
        graphic: Graphic(0x3175),
        name: Text::Cliloc(1032661),
        group: 2,
        skills: SKILLS_46,
        resources: RES_46,
        amount: 1,
        hue: Hue(0x0000),
        use_all_res: false,
        min_skill_offset: 0,
        markable: true,
        never_exceptional: false,
        always_exceptional: false,
        needs: Needs::none(),
    },
    Recipe {
        graphic: Graphic(0x3176),
        name: Text::Cliloc(1032662),
        group: 2,
        skills: SKILLS_47,
        resources: RES_47,
        amount: 1,
        hue: Hue(0x0000),
        use_all_res: false,
        min_skill_offset: 0,
        markable: true,
        never_exceptional: false,
        always_exceptional: false,
        needs: Needs::none(),
    },
    Recipe {
        graphic: Graphic(0x2FC3),
        name: Text::Cliloc(1032665),
        group: 2,
        skills: SKILLS_48,
        resources: RES_48,
        amount: 1,
        hue: Hue(0x0000),
        use_all_res: false,
        min_skill_offset: 0,
        markable: true,
        never_exceptional: false,
        always_exceptional: false,
        needs: Needs::none(),
    },
    Recipe {
        graphic: Graphic(0x2FB9),
        name: Text::Cliloc(1032659),
        group: 2,
        skills: SKILLS_49,
        resources: RES_49,
        amount: 1,
        hue: Hue(0x0000),
        use_all_res: false,
        min_skill_offset: 0,
        markable: true,
        never_exceptional: false,
        always_exceptional: false,
        needs: Needs::none(),
    },
    Recipe {
        graphic: Graphic(0x2FBA),
        name: Text::Cliloc(1032660),
        group: 2,
        skills: SKILLS_50,
        resources: RES_50,
        amount: 1,
        hue: Hue(0x0000),
        use_all_res: false,
        min_skill_offset: 0,
        markable: true,
        never_exceptional: false,
        always_exceptional: false,
        needs: Needs::none(),
    },
    Recipe {
        graphic: Graphic(0x2B68),
        name: Text::Cliloc(1032639),
        group: 2,
        skills: SKILLS_51,
        resources: RES_51,
        amount: 1,
        hue: Hue(0x0000),
        use_all_res: false,
        min_skill_offset: 0,
        markable: true,
        never_exceptional: false,
        always_exceptional: false,
        needs: Needs::none(),
    },
    Recipe {
        graphic: Graphic(0x1541),
        name: Text::Cliloc(1025441),
        group: 3,
        skills: SKILLS_52,
        resources: RES_52,
        amount: 1,
        hue: Hue(0x0000),
        use_all_res: false,
        min_skill_offset: 0,
        markable: true,
        never_exceptional: false,
        always_exceptional: false,
        needs: Needs::none(),
    },
    Recipe {
        graphic: Graphic(0x153B),
        name: Text::Cliloc(1025435),
        group: 3,
        skills: SKILLS_53,
        resources: RES_53,
        amount: 1,
        hue: Hue(0x0000),
        use_all_res: false,
        min_skill_offset: 0,
        markable: true,
        never_exceptional: false,
        always_exceptional: false,
        needs: Needs::none(),
    },
    Recipe {
        graphic: Graphic(0x153D),
        name: Text::Cliloc(1025437),
        group: 3,
        skills: SKILLS_54,
        resources: RES_54,
        amount: 1,
        hue: Hue(0x0000),
        use_all_res: false,
        min_skill_offset: 0,
        markable: true,
        never_exceptional: false,
        always_exceptional: false,
        needs: Needs::none(),
    },
    Recipe {
        graphic: Graphic(0x27A0),
        name: Text::Cliloc(1030219),
        group: 3,
        skills: SKILLS_55,
        resources: RES_55,
        amount: 1,
        hue: Hue(0x0000),
        use_all_res: false,
        min_skill_offset: 0,
        markable: true,
        never_exceptional: false,
        always_exceptional: false,
        needs: Needs::none(),
    },
    Recipe {
        graphic: Graphic(0x0F9D),
        name: Text::Cliloc(1072152),
        group: 3,
        skills: SKILLS_56,
        resources: RES_56,
        amount: 1,
        hue: Hue(0x0000),
        use_all_res: false,
        min_skill_offset: 0,
        markable: false,
        never_exceptional: false,
        always_exceptional: false,
        needs: Needs::none(),
    },
    Recipe {
        graphic: Graphic(0x175D),
        name: Text::Cliloc(1041498),
        group: 3,
        skills: SKILLS_57,
        resources: RES_57,
        amount: 1,
        hue: Hue(0x0000),
        use_all_res: false,
        min_skill_offset: 0,
        markable: false,
        never_exceptional: false,
        always_exceptional: false,
        needs: Needs::none(),
    },
    Recipe {
        graphic: Graphic(0x14F0),
        name: Text::Cliloc(1030404),
        group: 3,
        skills: SKILLS_58,
        resources: RES_58,
        amount: 1,
        hue: Hue(0x0000),
        use_all_res: false,
        min_skill_offset: 0,
        markable: false,
        never_exceptional: false,
        always_exceptional: false,
        needs: Needs::none(),
    },
    Recipe {
        graphic: Graphic(0x14F0),
        name: Text::Cliloc(1030405),
        group: 3,
        skills: SKILLS_59,
        resources: RES_59,
        amount: 1,
        hue: Hue(0x0000),
        use_all_res: false,
        min_skill_offset: 0,
        markable: false,
        never_exceptional: false,
        always_exceptional: false,
        needs: Needs::none(),
    },
    Recipe {
        graphic: Graphic(0x14F0),
        name: Text::Cliloc(1030407),
        group: 3,
        skills: SKILLS_60,
        resources: RES_60,
        amount: 1,
        hue: Hue(0x0000),
        use_all_res: false,
        min_skill_offset: 0,
        markable: false,
        never_exceptional: false,
        always_exceptional: false,
        needs: Needs::none(),
    },
    Recipe {
        graphic: Graphic(0x14F0),
        name: Text::Cliloc(1030406),
        group: 3,
        skills: SKILLS_61,
        resources: RES_61,
        amount: 1,
        hue: Hue(0x0000),
        use_all_res: false,
        min_skill_offset: 0,
        markable: false,
        never_exceptional: false,
        always_exceptional: false,
        needs: Needs::none(),
    },
    Recipe {
        graphic: Graphic(0x14F0),
        name: Text::Cliloc(1030408),
        group: 3,
        skills: SKILLS_62,
        resources: RES_62,
        amount: 1,
        hue: Hue(0x0000),
        use_all_res: false,
        min_skill_offset: 0,
        markable: false,
        never_exceptional: false,
        always_exceptional: false,
        needs: Needs::none(),
    },
    Recipe {
        graphic: Graphic(0x14F0),
        name: Text::Cliloc(1030409),
        group: 3,
        skills: SKILLS_63,
        resources: RES_63,
        amount: 1,
        hue: Hue(0x0000),
        use_all_res: false,
        min_skill_offset: 0,
        markable: false,
        never_exceptional: false,
        always_exceptional: false,
        needs: Needs::none(),
    },
    Recipe {
        graphic: Graphic(0x14F0),
        name: Text::Cliloc(1030411),
        group: 3,
        skills: SKILLS_64,
        resources: RES_64,
        amount: 1,
        hue: Hue(0x0000),
        use_all_res: false,
        min_skill_offset: 0,
        markable: false,
        never_exceptional: false,
        always_exceptional: false,
        needs: Needs::none(),
    },
    Recipe {
        graphic: Graphic(0x14F0),
        name: Text::Cliloc(1030410),
        group: 3,
        skills: SKILLS_65,
        resources: RES_65,
        amount: 1,
        hue: Hue(0x0000),
        use_all_res: false,
        min_skill_offset: 0,
        markable: false,
        never_exceptional: false,
        always_exceptional: false,
        needs: Needs::none(),
    },
    Recipe {
        graphic: Graphic(0x2FC4),
        name: Text::Cliloc(1072902),
        group: 4,
        skills: SKILLS_66,
        resources: RES_66,
        amount: 1,
        hue: Hue(0x0000),
        use_all_res: false,
        min_skill_offset: 0,
        markable: true,
        never_exceptional: false,
        always_exceptional: false,
        needs: Needs::none(),
    },
    Recipe {
        graphic: Graphic(0x2307),
        name: Text::Cliloc(1028967),
        group: 4,
        skills: SKILLS_67,
        resources: RES_67,
        amount: 1,
        hue: Hue(0x0000),
        use_all_res: false,
        min_skill_offset: 0,
        markable: true,
        never_exceptional: false,
        always_exceptional: false,
        needs: Needs::none(),
    },
    Recipe {
        graphic: Graphic(0x2797),
        name: Text::Cliloc(1030210),
        group: 4,
        skills: SKILLS_68,
        resources: RES_68,
        amount: 1,
        hue: Hue(0x0000),
        use_all_res: false,
        min_skill_offset: 0,
        markable: true,
        never_exceptional: false,
        always_exceptional: false,
        needs: Needs::none(),
    },
    Recipe {
        graphic: Graphic(0x2796),
        name: Text::Cliloc(1030209),
        group: 4,
        skills: SKILLS_69,
        resources: RES_69,
        amount: 1,
        hue: Hue(0x0000),
        use_all_res: false,
        min_skill_offset: 0,
        markable: true,
        never_exceptional: false,
        always_exceptional: false,
        needs: Needs::none(),
    },
    Recipe {
        graphic: Graphic(0x170D),
        name: Text::Cliloc(1025901),
        group: 4,
        skills: SKILLS_70,
        resources: RES_70,
        amount: 1,
        hue: Hue(0x0000),
        use_all_res: false,
        min_skill_offset: 0,
        markable: true,
        never_exceptional: false,
        always_exceptional: false,
        needs: Needs::none(),
    },
    Recipe {
        graphic: Graphic(0x170F),
        name: Text::Cliloc(1025904),
        group: 4,
        skills: SKILLS_71,
        resources: RES_71,
        amount: 1,
        hue: Hue(0x0000),
        use_all_res: false,
        min_skill_offset: 0,
        markable: true,
        never_exceptional: false,
        always_exceptional: false,
        needs: Needs::none(),
    },
    Recipe {
        graphic: Graphic(0x170B),
        name: Text::Cliloc(1025899),
        group: 4,
        skills: SKILLS_72,
        resources: RES_72,
        amount: 1,
        hue: Hue(0x0000),
        use_all_res: false,
        min_skill_offset: 0,
        markable: true,
        never_exceptional: false,
        always_exceptional: false,
        needs: Needs::none(),
    },
    Recipe {
        graphic: Graphic(0x1711),
        name: Text::Cliloc(1025906),
        group: 4,
        skills: SKILLS_73,
        resources: RES_73,
        amount: 1,
        hue: Hue(0x0000),
        use_all_res: false,
        min_skill_offset: 0,
        markable: true,
        never_exceptional: false,
        always_exceptional: false,
        needs: Needs::none(),
    },
    Recipe {
        graphic: Graphic(0x13C7),
        name: Text::Cliloc(1025063),
        group: 5,
        skills: SKILLS_74,
        resources: RES_74,
        amount: 1,
        hue: Hue(0x0000),
        use_all_res: false,
        min_skill_offset: 0,
        markable: true,
        never_exceptional: false,
        always_exceptional: false,
        needs: Needs::none(),
    },
    Recipe {
        graphic: Graphic(0x1DB9),
        name: Text::Cliloc(1027609),
        group: 5,
        skills: SKILLS_75,
        resources: RES_75,
        amount: 1,
        hue: Hue(0x0000),
        use_all_res: false,
        min_skill_offset: 0,
        markable: true,
        never_exceptional: false,
        always_exceptional: false,
        needs: Needs::none(),
    },
    Recipe {
        graphic: Graphic(0x13C6),
        name: Text::Cliloc(1025062),
        group: 5,
        skills: SKILLS_76,
        resources: RES_76,
        amount: 1,
        hue: Hue(0x0000),
        use_all_res: false,
        min_skill_offset: 0,
        markable: true,
        never_exceptional: false,
        always_exceptional: false,
        needs: Needs::none(),
    },
    Recipe {
        graphic: Graphic(0x13CD),
        name: Text::Cliloc(1025061),
        group: 5,
        skills: SKILLS_77,
        resources: RES_77,
        amount: 1,
        hue: Hue(0x0000),
        use_all_res: false,
        min_skill_offset: 0,
        markable: true,
        never_exceptional: false,
        always_exceptional: false,
        needs: Needs::none(),
    },
    Recipe {
        graphic: Graphic(0x13CB),
        name: Text::Cliloc(1025067),
        group: 5,
        skills: SKILLS_78,
        resources: RES_78,
        amount: 1,
        hue: Hue(0x0000),
        use_all_res: false,
        min_skill_offset: 0,
        markable: true,
        never_exceptional: false,
        always_exceptional: false,
        needs: Needs::none(),
    },
    Recipe {
        graphic: Graphic(0x13CC),
        name: Text::Cliloc(1025068),
        group: 5,
        skills: SKILLS_79,
        resources: RES_79,
        amount: 1,
        hue: Hue(0x0000),
        use_all_res: false,
        min_skill_offset: 0,
        markable: true,
        never_exceptional: false,
        always_exceptional: false,
        needs: Needs::none(),
    },
    Recipe {
        graphic: Graphic(0x2776),
        name: Text::Cliloc(1030177),
        group: 5,
        skills: SKILLS_80,
        resources: RES_80,
        amount: 1,
        hue: Hue(0x0000),
        use_all_res: false,
        min_skill_offset: 0,
        markable: true,
        never_exceptional: false,
        always_exceptional: false,
        needs: Needs::none(),
    },
    Recipe {
        graphic: Graphic(0x277A),
        name: Text::Cliloc(1030181),
        group: 5,
        skills: SKILLS_81,
        resources: RES_81,
        amount: 1,
        hue: Hue(0x0000),
        use_all_res: false,
        min_skill_offset: 0,
        markable: true,
        never_exceptional: false,
        always_exceptional: false,
        needs: Needs::none(),
    },
    Recipe {
        graphic: Graphic(0x27C6),
        name: Text::Cliloc(1030182),
        group: 5,
        skills: SKILLS_82,
        resources: RES_82,
        amount: 1,
        hue: Hue(0x0000),
        use_all_res: false,
        min_skill_offset: 0,
        markable: true,
        never_exceptional: false,
        always_exceptional: false,
        needs: Needs::none(),
    },
    Recipe {
        graphic: Graphic(0x277E),
        name: Text::Cliloc(1030185),
        group: 5,
        skills: SKILLS_83,
        resources: RES_83,
        amount: 1,
        hue: Hue(0x0000),
        use_all_res: false,
        min_skill_offset: 0,
        markable: true,
        never_exceptional: false,
        always_exceptional: false,
        needs: Needs::none(),
    },
    Recipe {
        graphic: Graphic(0x2786),
        name: Text::Cliloc(1030193),
        group: 5,
        skills: SKILLS_84,
        resources: RES_84,
        amount: 1,
        hue: Hue(0x0000),
        use_all_res: false,
        min_skill_offset: 0,
        markable: true,
        never_exceptional: false,
        always_exceptional: false,
        needs: Needs::none(),
    },
    Recipe {
        graphic: Graphic(0x278A),
        name: Text::Cliloc(1030197),
        group: 5,
        skills: SKILLS_85,
        resources: RES_85,
        amount: 1,
        hue: Hue(0x0000),
        use_all_res: false,
        min_skill_offset: 0,
        markable: true,
        never_exceptional: false,
        always_exceptional: false,
        needs: Needs::none(),
    },
    Recipe {
        graphic: Graphic(0x2791),
        name: Text::Cliloc(1030204),
        group: 5,
        skills: SKILLS_86,
        resources: RES_86,
        amount: 1,
        hue: Hue(0x0000),
        use_all_res: false,
        min_skill_offset: 0,
        markable: true,
        never_exceptional: false,
        always_exceptional: false,
        needs: Needs::none(),
    },
    Recipe {
        graphic: Graphic(0x2793),
        name: Text::Cliloc(1030206),
        group: 5,
        skills: SKILLS_87,
        resources: RES_87,
        amount: 1,
        hue: Hue(0x0000),
        use_all_res: false,
        min_skill_offset: 0,
        markable: true,
        never_exceptional: false,
        always_exceptional: false,
        needs: Needs::none(),
    },
    Recipe {
        graphic: Graphic(0x2790),
        name: Text::Cliloc(1030203),
        group: 5,
        skills: SKILLS_88,
        resources: RES_88,
        amount: 1,
        hue: Hue(0x0000),
        use_all_res: false,
        min_skill_offset: 0,
        markable: true,
        never_exceptional: false,
        always_exceptional: false,
        needs: Needs::none(),
    },
    Recipe {
        graphic: Graphic(0x2792),
        name: Text::Cliloc(1030205),
        group: 5,
        skills: SKILLS_89,
        resources: RES_89,
        amount: 1,
        hue: Hue(0x0000),
        use_all_res: false,
        min_skill_offset: 0,
        markable: true,
        never_exceptional: false,
        always_exceptional: false,
        needs: Needs::none(),
    },
    Recipe {
        graphic: Graphic(0x278E),
        name: Text::Cliloc(1030201),
        group: 5,
        skills: SKILLS_90,
        resources: RES_90,
        amount: 1,
        hue: Hue(0x0000),
        use_all_res: false,
        min_skill_offset: 0,
        markable: true,
        never_exceptional: false,
        always_exceptional: false,
        needs: Needs::none(),
    },
    Recipe {
        graphic: Graphic(0x2FC5),
        name: Text::Cliloc(1032667),
        group: 5,
        skills: SKILLS_91,
        resources: RES_91,
        amount: 1,
        hue: Hue(0x0000),
        use_all_res: false,
        min_skill_offset: 0,
        markable: true,
        never_exceptional: false,
        always_exceptional: false,
        needs: Needs::none(),
    },
    Recipe {
        graphic: Graphic(0x2FC8),
        name: Text::Cliloc(1032670),
        group: 5,
        skills: SKILLS_92,
        resources: RES_92,
        amount: 1,
        hue: Hue(0x0000),
        use_all_res: false,
        min_skill_offset: 0,
        markable: true,
        never_exceptional: false,
        always_exceptional: false,
        needs: Needs::none(),
    },
    Recipe {
        graphic: Graphic(0x2FC6),
        name: Text::Cliloc(1032668),
        group: 5,
        skills: SKILLS_93,
        resources: RES_93,
        amount: 1,
        hue: Hue(0x0000),
        use_all_res: false,
        min_skill_offset: 0,
        markable: true,
        never_exceptional: false,
        always_exceptional: false,
        needs: Needs::none(),
    },
    Recipe {
        graphic: Graphic(0x2FC9),
        name: Text::Cliloc(1032671),
        group: 5,
        skills: SKILLS_94,
        resources: RES_94,
        amount: 1,
        hue: Hue(0x0000),
        use_all_res: false,
        min_skill_offset: 0,
        markable: true,
        never_exceptional: false,
        always_exceptional: false,
        needs: Needs::none(),
    },
    Recipe {
        graphic: Graphic(0x2FC7),
        name: Text::Cliloc(1032669),
        group: 5,
        skills: SKILLS_95,
        resources: RES_95,
        amount: 1,
        hue: Hue(0x0000),
        use_all_res: false,
        min_skill_offset: 0,
        markable: true,
        never_exceptional: false,
        always_exceptional: false,
        needs: Needs::none(),
    },
    Recipe {
        graphic: Graphic(0x2FCA),
        name: Text::Cliloc(1032672),
        group: 5,
        skills: SKILLS_96,
        resources: RES_96,
        amount: 1,
        hue: Hue(0x0000),
        use_all_res: false,
        min_skill_offset: 0,
        markable: true,
        never_exceptional: false,
        always_exceptional: false,
        needs: Needs::none(),
    },
    Recipe {
        graphic: Graphic(0x13D6),
        name: Text::Cliloc(1025078),
        group: 6,
        skills: SKILLS_97,
        resources: RES_97,
        amount: 1,
        hue: Hue(0x0000),
        use_all_res: false,
        min_skill_offset: 0,
        markable: true,
        never_exceptional: false,
        always_exceptional: false,
        needs: Needs::none(),
    },
    Recipe {
        graphic: Graphic(0x13D5),
        name: Text::Cliloc(1025077),
        group: 6,
        skills: SKILLS_98,
        resources: RES_98,
        amount: 1,
        hue: Hue(0x0000),
        use_all_res: false,
        min_skill_offset: 0,
        markable: true,
        never_exceptional: false,
        always_exceptional: false,
        needs: Needs::none(),
    },
    Recipe {
        graphic: Graphic(0x13DC),
        name: Text::Cliloc(1025076),
        group: 6,
        skills: SKILLS_99,
        resources: RES_99,
        amount: 1,
        hue: Hue(0x0000),
        use_all_res: false,
        min_skill_offset: 0,
        markable: true,
        never_exceptional: false,
        always_exceptional: false,
        needs: Needs::none(),
    },
    Recipe {
        graphic: Graphic(0x13DA),
        name: Text::Cliloc(1025082),
        group: 6,
        skills: SKILLS_100,
        resources: RES_100,
        amount: 1,
        hue: Hue(0x0000),
        use_all_res: false,
        min_skill_offset: 0,
        markable: true,
        never_exceptional: false,
        always_exceptional: false,
        needs: Needs::none(),
    },
    Recipe {
        graphic: Graphic(0x13DB),
        name: Text::Cliloc(1025083),
        group: 6,
        skills: SKILLS_101,
        resources: RES_101,
        amount: 1,
        hue: Hue(0x0000),
        use_all_res: false,
        min_skill_offset: 0,
        markable: true,
        never_exceptional: false,
        always_exceptional: false,
        needs: Needs::none(),
    },
    Recipe {
        graphic: Graphic(0x279D),
        name: Text::Cliloc(1030216),
        group: 6,
        skills: SKILLS_102,
        resources: RES_102,
        amount: 1,
        hue: Hue(0x0000),
        use_all_res: false,
        min_skill_offset: 0,
        markable: true,
        never_exceptional: false,
        always_exceptional: false,
        needs: Needs::none(),
    },
    Recipe {
        graphic: Graphic(0x27C7),
        name: Text::Cliloc(1030183),
        group: 6,
        skills: SKILLS_103,
        resources: RES_103,
        amount: 1,
        hue: Hue(0x0000),
        use_all_res: false,
        min_skill_offset: 0,
        markable: true,
        never_exceptional: false,
        always_exceptional: false,
        needs: Needs::none(),
    },
    Recipe {
        graphic: Graphic(0x277F),
        name: Text::Cliloc(1030186),
        group: 6,
        skills: SKILLS_104,
        resources: RES_104,
        amount: 1,
        hue: Hue(0x0000),
        use_all_res: false,
        min_skill_offset: 0,
        markable: true,
        never_exceptional: false,
        always_exceptional: false,
        needs: Needs::none(),
    },
    Recipe {
        graphic: Graphic(0x27D2),
        name: Text::Cliloc(1030194),
        group: 6,
        skills: SKILLS_105,
        resources: RES_105,
        amount: 1,
        hue: Hue(0x0000),
        use_all_res: false,
        min_skill_offset: 0,
        markable: true,
        never_exceptional: false,
        always_exceptional: false,
        needs: Needs::none(),
    },
    Recipe {
        graphic: Graphic(0x278B),
        name: Text::Cliloc(1030198),
        group: 6,
        skills: SKILLS_106,
        resources: RES_106,
        amount: 1,
        hue: Hue(0x0000),
        use_all_res: false,
        min_skill_offset: 0,
        markable: true,
        never_exceptional: false,
        always_exceptional: false,
        needs: Needs::none(),
    },
    Recipe {
        graphic: Graphic(0x2B74),
        name: Text::Cliloc(1032651),
        group: 6,
        skills: SKILLS_107,
        resources: RES_107,
        amount: 1,
        hue: Hue(0x0000),
        use_all_res: false,
        min_skill_offset: 0,
        markable: true,
        never_exceptional: false,
        always_exceptional: false,
        needs: Needs::none(),
    },
    Recipe {
        graphic: Graphic(0x2B77),
        name: Text::Cliloc(1032654),
        group: 6,
        skills: SKILLS_108,
        resources: RES_108,
        amount: 1,
        hue: Hue(0x0000),
        use_all_res: false,
        min_skill_offset: 0,
        markable: true,
        never_exceptional: false,
        always_exceptional: false,
        needs: Needs::none(),
    },
    Recipe {
        graphic: Graphic(0x2B75),
        name: Text::Cliloc(1032652),
        group: 6,
        skills: SKILLS_109,
        resources: RES_109,
        amount: 1,
        hue: Hue(0x0000),
        use_all_res: false,
        min_skill_offset: 0,
        markable: true,
        never_exceptional: false,
        always_exceptional: false,
        needs: Needs::none(),
    },
    Recipe {
        graphic: Graphic(0x2B78),
        name: Text::Cliloc(1032655),
        group: 6,
        skills: SKILLS_110,
        resources: RES_110,
        amount: 1,
        hue: Hue(0x0000),
        use_all_res: false,
        min_skill_offset: 0,
        markable: true,
        never_exceptional: false,
        always_exceptional: false,
        needs: Needs::none(),
    },
    Recipe {
        graphic: Graphic(0x2B76),
        name: Text::Cliloc(1032653),
        group: 6,
        skills: SKILLS_111,
        resources: RES_111,
        amount: 1,
        hue: Hue(0x0000),
        use_all_res: false,
        min_skill_offset: 0,
        markable: true,
        never_exceptional: false,
        always_exceptional: false,
        needs: Needs::none(),
    },
    Recipe {
        graphic: Graphic(0x1C00),
        name: Text::Cliloc(1027168),
        group: 7,
        skills: SKILLS_112,
        resources: RES_112,
        amount: 1,
        hue: Hue(0x0000),
        use_all_res: false,
        min_skill_offset: 0,
        markable: true,
        never_exceptional: false,
        always_exceptional: false,
        needs: Needs::none(),
    },
    Recipe {
        graphic: Graphic(0x1C08),
        name: Text::Cliloc(1027176),
        group: 7,
        skills: SKILLS_113,
        resources: RES_113,
        amount: 1,
        hue: Hue(0x0000),
        use_all_res: false,
        min_skill_offset: 0,
        markable: true,
        never_exceptional: false,
        always_exceptional: false,
        needs: Needs::none(),
    },
    Recipe {
        graphic: Graphic(0x1C0A),
        name: Text::Cliloc(1027178),
        group: 7,
        skills: SKILLS_114,
        resources: RES_114,
        amount: 1,
        hue: Hue(0x0000),
        use_all_res: false,
        min_skill_offset: 0,
        markable: true,
        never_exceptional: false,
        always_exceptional: false,
        needs: Needs::none(),
    },
    Recipe {
        graphic: Graphic(0x1C0C),
        name: Text::Cliloc(1027180),
        group: 7,
        skills: SKILLS_115,
        resources: RES_115,
        amount: 1,
        hue: Hue(0x0000),
        use_all_res: false,
        min_skill_offset: 0,
        markable: true,
        never_exceptional: false,
        always_exceptional: false,
        needs: Needs::none(),
    },
    Recipe {
        graphic: Graphic(0x1C06),
        name: Text::Cliloc(1027174),
        group: 7,
        skills: SKILLS_116,
        resources: RES_116,
        amount: 1,
        hue: Hue(0x0000),
        use_all_res: false,
        min_skill_offset: 0,
        markable: true,
        never_exceptional: false,
        always_exceptional: false,
        needs: Needs::none(),
    },
    Recipe {
        graphic: Graphic(0x1C02),
        name: Text::Cliloc(1027170),
        group: 7,
        skills: SKILLS_117,
        resources: RES_117,
        amount: 1,
        hue: Hue(0x0000),
        use_all_res: false,
        min_skill_offset: 0,
        markable: true,
        never_exceptional: false,
        always_exceptional: false,
        needs: Needs::none(),
    },
    Recipe {
        graphic: Graphic(0x1451),
        name: Text::Cliloc(1025206),
        group: 8,
        skills: SKILLS_118,
        resources: RES_118,
        amount: 1,
        hue: Hue(0x0000),
        use_all_res: false,
        min_skill_offset: 0,
        markable: true,
        never_exceptional: false,
        always_exceptional: false,
        needs: Needs::none(),
    },
    Recipe {
        graphic: Graphic(0x1450),
        name: Text::Cliloc(1025205),
        group: 8,
        skills: SKILLS_119,
        resources: RES_119,
        amount: 1,
        hue: Hue(0x0000),
        use_all_res: false,
        min_skill_offset: 0,
        markable: true,
        never_exceptional: false,
        always_exceptional: false,
        needs: Needs::none(),
    },
    Recipe {
        graphic: Graphic(0x144E),
        name: Text::Cliloc(1025203),
        group: 8,
        skills: SKILLS_120,
        resources: RES_120,
        amount: 1,
        hue: Hue(0x0000),
        use_all_res: false,
        min_skill_offset: 0,
        markable: true,
        never_exceptional: false,
        always_exceptional: false,
        needs: Needs::none(),
    },
    Recipe {
        graphic: Graphic(0x1452),
        name: Text::Cliloc(1025202),
        group: 8,
        skills: SKILLS_121,
        resources: RES_121,
        amount: 1,
        hue: Hue(0x0000),
        use_all_res: false,
        min_skill_offset: 0,
        markable: true,
        never_exceptional: false,
        always_exceptional: false,
        needs: Needs::none(),
    },
    Recipe {
        graphic: Graphic(0x144F),
        name: Text::Cliloc(1025199),
        group: 8,
        skills: SKILLS_122,
        resources: RES_122,
        amount: 1,
        hue: Hue(0x0000),
        use_all_res: false,
        min_skill_offset: 0,
        markable: true,
        never_exceptional: false,
        always_exceptional: false,
        needs: Needs::none(),
    },
    Recipe {
        graphic: Graphic(0x1F0B),
        name: Text::Cliloc(1027947),
        group: 8,
        skills: SKILLS_123,
        resources: RES_123,
        amount: 1,
        hue: Hue(0x0000),
        use_all_res: false,
        min_skill_offset: 0,
        markable: true,
        never_exceptional: false,
        always_exceptional: false,
        needs: Needs::none(),
    },
];

/// The material this trade is worked in.
pub const SUB_RES: SubResAxis = SubResAxis {
    graphic: Graphic(0x1081),
    name: Text::Cliloc(1049150),
    entries: &[
        SubRes {
            hue: Hue(0x0000),
            name: Text::Cliloc(1049150),
            req_skill: 0,
            message: Text::Cliloc(1049311),
        },
        SubRes {
            hue: Hue(0x08AC),
            name: Text::Cliloc(1049151),
            req_skill: 650,
            message: Text::Cliloc(1049311),
        },
        SubRes {
            hue: Hue(0x0845),
            name: Text::Cliloc(1049152),
            req_skill: 800,
            message: Text::Cliloc(1049311),
        },
        SubRes {
            hue: Hue(0x0851),
            name: Text::Cliloc(1049153),
            req_skill: 990,
            message: Text::Cliloc(1049311),
        },
    ],
};
