//! DefTinkering's recipes, as core data.
//!
//! Generated once from ServUO by `tools/gen-craft-tables`, and ordinary source
//! from then on: edit it, do not regenerate it. Skills are in tenths.

use openshard_protocol::wire::{Graphic, Hue};
use openshard_state::Skill;

use crate::recipe::{CraftRes, CraftSkillReq, Recipe, SubRes, SubResAxis};
use crate::system::{Needs, Text};

/// The gump's left-hand column.
pub const GROUPS: &[Text] = &[
    Text::Cliloc(1044049),
    Text::Cliloc(1044042),
    Text::Cliloc(1044046),
    Text::Cliloc(1044047),
    Text::Cliloc(1044048),
    Text::Cliloc(1044050),
    Text::Cliloc(1044051),
    Text::Cliloc(1044052),
    Text::Cliloc(1073107),
];

const SKILLS_0: &[CraftSkillReq] = &[CraftSkillReq {
    skill: Skill::Tinkering,
    min: 650,
    max: 1150,
}];
const RES_0: &[CraftRes] = &[CraftRes {
    graphic: Graphic(0x1BF2),
    hue: Hue(0x0000),
    amount: 3,
    name: Text::Cliloc(1044036),
    message: Text::Cliloc(1044037),
    from_axis: true,
}];
const SKILLS_1: &[CraftSkillReq] = &[CraftSkillReq {
    skill: Skill::Tinkering,
    min: 550,
    max: 1050,
}];
const RES_1: &[CraftRes] = &[CraftRes {
    graphic: Graphic(0x1BF2),
    hue: Hue(0x0000),
    amount: 3,
    name: Text::Cliloc(1044036),
    message: Text::Cliloc(1044037),
    from_axis: true,
}];
const SKILLS_2: &[CraftSkillReq] = &[CraftSkillReq {
    skill: Skill::Tinkering,
    min: 700,
    max: 1200,
}];
const RES_2: &[CraftRes] = &[
    CraftRes {
        graphic: Graphic(0x1BF2),
        hue: Hue(0x0000),
        amount: 3,
        name: Text::Cliloc(1044036),
        message: Text::Cliloc(1044037),
        from_axis: true,
    },
    CraftRes {
        graphic: Graphic(0x1BD7),
        hue: Hue(0x0000),
        amount: 8,
        name: Text::Cliloc(1044041),
        message: Text::Cliloc(1044351),
        from_axis: false,
    },
];
const SKILLS_3: &[CraftSkillReq] = &[CraftSkillReq {
    skill: Skill::Tinkering,
    min: 0,
    max: 500,
}];
const RES_3: &[CraftRes] = &[CraftRes {
    graphic: Graphic(0x1BD7),
    hue: Hue(0x0000),
    amount: 4,
    name: Text::Cliloc(1044041),
    message: Text::Cliloc(1044351),
    from_axis: false,
}];
const SKILLS_4: &[CraftSkillReq] = &[CraftSkillReq {
    skill: Skill::Tinkering,
    min: 0,
    max: 500,
}];
const RES_4: &[CraftRes] = &[CraftRes {
    graphic: Graphic(0x1BD7),
    hue: Hue(0x0000),
    amount: 4,
    name: Text::Cliloc(1044041),
    message: Text::Cliloc(1044351),
    from_axis: false,
}];
const SKILLS_5: &[CraftSkillReq] = &[CraftSkillReq {
    skill: Skill::Tinkering,
    min: 0,
    max: 500,
}];
const RES_5: &[CraftRes] = &[CraftRes {
    graphic: Graphic(0x1BD7),
    hue: Hue(0x0000),
    amount: 4,
    name: Text::Cliloc(1044041),
    message: Text::Cliloc(1044351),
    from_axis: false,
}];
const SKILLS_6: &[CraftSkillReq] = &[CraftSkillReq {
    skill: Skill::Tinkering,
    min: 0,
    max: 500,
}];
const RES_6: &[CraftRes] = &[CraftRes {
    graphic: Graphic(0x1BD7),
    hue: Hue(0x0000),
    amount: 6,
    name: Text::Cliloc(1044041),
    message: Text::Cliloc(1044351),
    from_axis: false,
}];
const SKILLS_7: &[CraftSkillReq] = &[CraftSkillReq {
    skill: Skill::Tinkering,
    min: -250,
    max: 250,
}];
const RES_7: &[CraftRes] = &[CraftRes {
    graphic: Graphic(0x1BD7),
    hue: Hue(0x0000),
    amount: 2,
    name: Text::Cliloc(1044041),
    message: Text::Cliloc(1044351),
    from_axis: false,
}];
const SKILLS_8: &[CraftSkillReq] = &[CraftSkillReq {
    skill: Skill::Tinkering,
    min: 0,
    max: 500,
}];
const RES_8: &[CraftRes] = &[CraftRes {
    graphic: Graphic(0x1BD7),
    hue: Hue(0x0000),
    amount: 5,
    name: Text::Cliloc(1044041),
    message: Text::Cliloc(1044351),
    from_axis: false,
}];
const SKILLS_9: &[CraftSkillReq] = &[CraftSkillReq {
    skill: Skill::Tinkering,
    min: 50,
    max: 550,
}];
const RES_9: &[CraftRes] = &[CraftRes {
    graphic: Graphic(0x1BF2),
    hue: Hue(0x0000),
    amount: 2,
    name: Text::Cliloc(1044036),
    message: Text::Cliloc(1044037),
    from_axis: true,
}];
const SKILLS_10: &[CraftSkillReq] = &[CraftSkillReq {
    skill: Skill::Tinkering,
    min: 200,
    max: 700,
}];
const RES_10: &[CraftRes] = &[CraftRes {
    graphic: Graphic(0x1BF2),
    hue: Hue(0x0000),
    amount: 3,
    name: Text::Cliloc(1044036),
    message: Text::Cliloc(1044037),
    from_axis: true,
}];
const SKILLS_11: &[CraftSkillReq] = &[CraftSkillReq {
    skill: Skill::Tinkering,
    min: 300,
    max: 800,
}];
const RES_11: &[CraftRes] = &[CraftRes {
    graphic: Graphic(0x1BF2),
    hue: Hue(0x0000),
    amount: 2,
    name: Text::Cliloc(1044036),
    message: Text::Cliloc(1044037),
    from_axis: true,
}];
const SKILLS_12: &[CraftSkillReq] = &[CraftSkillReq {
    skill: Skill::Tinkering,
    min: 100,
    max: 600,
}];
const RES_12: &[CraftRes] = &[CraftRes {
    graphic: Graphic(0x1BF2),
    hue: Hue(0x0000),
    amount: 2,
    name: Text::Cliloc(1044036),
    message: Text::Cliloc(1044037),
    from_axis: true,
}];
const SKILLS_13: &[CraftSkillReq] = &[CraftSkillReq {
    skill: Skill::Tinkering,
    min: 300,
    max: 800,
}];
const RES_13: &[CraftRes] = &[CraftRes {
    graphic: Graphic(0x1BF2),
    hue: Hue(0x0000),
    amount: 4,
    name: Text::Cliloc(1044036),
    message: Text::Cliloc(1044037),
    from_axis: true,
}];
const SKILLS_14: &[CraftSkillReq] = &[CraftSkillReq {
    skill: Skill::Tinkering,
    min: 300,
    max: 800,
}];
const RES_14: &[CraftRes] = &[CraftRes {
    graphic: Graphic(0x1BF2),
    hue: Hue(0x0000),
    amount: 2,
    name: Text::Cliloc(1044036),
    message: Text::Cliloc(1044037),
    from_axis: true,
}];
const SKILLS_15: &[CraftSkillReq] = &[CraftSkillReq {
    skill: Skill::Tinkering,
    min: 100,
    max: 700,
}];
const RES_15: &[CraftRes] = &[CraftRes {
    graphic: Graphic(0x1BF2),
    hue: Hue(0x0000),
    amount: 2,
    name: Text::Cliloc(1044036),
    message: Text::Cliloc(1044037),
    from_axis: true,
}];
const SKILLS_16: &[CraftSkillReq] = &[CraftSkillReq {
    skill: Skill::Tinkering,
    min: 300,
    max: 800,
}];
const RES_16: &[CraftRes] = &[CraftRes {
    graphic: Graphic(0x1BF2),
    hue: Hue(0x0000),
    amount: 4,
    name: Text::Cliloc(1044036),
    message: Text::Cliloc(1044037),
    from_axis: true,
}];
const SKILLS_17: &[CraftSkillReq] = &[CraftSkillReq {
    skill: Skill::Tinkering,
    min: 300,
    max: 800,
}];
const RES_17: &[CraftRes] = &[CraftRes {
    graphic: Graphic(0x1BF2),
    hue: Hue(0x0000),
    amount: 4,
    name: Text::Cliloc(1044036),
    message: Text::Cliloc(1044037),
    from_axis: true,
}];
const SKILLS_18: &[CraftSkillReq] = &[CraftSkillReq {
    skill: Skill::Tinkering,
    min: 300,
    max: 800,
}];
const RES_18: &[CraftRes] = &[CraftRes {
    graphic: Graphic(0x1BF2),
    hue: Hue(0x0000),
    amount: 2,
    name: Text::Cliloc(1044036),
    message: Text::Cliloc(1044037),
    from_axis: true,
}];
const SKILLS_19: &[CraftSkillReq] = &[CraftSkillReq {
    skill: Skill::Tinkering,
    min: 400,
    max: 900,
}];
const RES_19: &[CraftRes] = &[CraftRes {
    graphic: Graphic(0x1BF2),
    hue: Hue(0x0000),
    amount: 4,
    name: Text::Cliloc(1044036),
    message: Text::Cliloc(1044037),
    from_axis: true,
}];
const SKILLS_20: &[CraftSkillReq] = &[CraftSkillReq {
    skill: Skill::Tinkering,
    min: 300,
    max: 800,
}];
const RES_20: &[CraftRes] = &[CraftRes {
    graphic: Graphic(0x1BF2),
    hue: Hue(0x0000),
    amount: 1,
    name: Text::Cliloc(1044036),
    message: Text::Cliloc(1044037),
    from_axis: true,
}];
const SKILLS_21: &[CraftSkillReq] = &[CraftSkillReq {
    skill: Skill::Tinkering,
    min: 350,
    max: 850,
}];
const RES_21: &[CraftRes] = &[CraftRes {
    graphic: Graphic(0x1BF2),
    hue: Hue(0x0000),
    amount: 1,
    name: Text::Cliloc(1044036),
    message: Text::Cliloc(1044037),
    from_axis: true,
}];
const SKILLS_22: &[CraftSkillReq] = &[CraftSkillReq {
    skill: Skill::Tinkering,
    min: 400,
    max: 900,
}];
const RES_22: &[CraftRes] = &[CraftRes {
    graphic: Graphic(0x1BF2),
    hue: Hue(0x0000),
    amount: 4,
    name: Text::Cliloc(1044036),
    message: Text::Cliloc(1044037),
    from_axis: true,
}];
const SKILLS_23: &[CraftSkillReq] = &[CraftSkillReq {
    skill: Skill::Tinkering,
    min: 400,
    max: 900,
}];
const RES_23: &[CraftRes] = &[CraftRes {
    graphic: Graphic(0x1BF2),
    hue: Hue(0x0000),
    amount: 4,
    name: Text::Cliloc(1044036),
    message: Text::Cliloc(1044037),
    from_axis: true,
}];
const SKILLS_24: &[CraftSkillReq] = &[CraftSkillReq {
    skill: Skill::Tinkering,
    min: 300,
    max: 800,
}];
const RES_24: &[CraftRes] = &[CraftRes {
    graphic: Graphic(0x1BF2),
    hue: Hue(0x0000),
    amount: 2,
    name: Text::Cliloc(1044036),
    message: Text::Cliloc(1044037),
    from_axis: true,
}];
const SKILLS_25: &[CraftSkillReq] = &[CraftSkillReq {
    skill: Skill::Tinkering,
    min: 400,
    max: 900,
}];
const RES_25: &[CraftRes] = &[CraftRes {
    graphic: Graphic(0x1BF2),
    hue: Hue(0x0000),
    amount: 4,
    name: Text::Cliloc(1044036),
    message: Text::Cliloc(1044037),
    from_axis: true,
}];
const SKILLS_26: &[CraftSkillReq] = &[CraftSkillReq {
    skill: Skill::Tinkering,
    min: 450,
    max: 950,
}];
const RES_26: &[CraftRes] = &[CraftRes {
    graphic: Graphic(0x1BF2),
    hue: Hue(0x0000),
    amount: 1,
    name: Text::Cliloc(1044036),
    message: Text::Cliloc(1044037),
    from_axis: true,
}];
const SKILLS_27: &[CraftSkillReq] = &[CraftSkillReq {
    skill: Skill::Tinkering,
    min: 300,
    max: 800,
}];
const RES_27: &[CraftRes] = &[CraftRes {
    graphic: Graphic(0x1BF2),
    hue: Hue(0x0000),
    amount: 4,
    name: Text::Cliloc(1044036),
    message: Text::Cliloc(1044037),
    from_axis: true,
}];
const SKILLS_28: &[CraftSkillReq] = &[CraftSkillReq {
    skill: Skill::Tinkering,
    min: 500,
    max: 1000,
}];
const RES_28: &[CraftRes] = &[CraftRes {
    graphic: Graphic(0x1BF2),
    hue: Hue(0x0000),
    amount: 3,
    name: Text::Cliloc(1044036),
    message: Text::Cliloc(1044037),
    from_axis: true,
}];
const SKILLS_29: &[CraftSkillReq] = &[CraftSkillReq {
    skill: Skill::Tinkering,
    min: 350,
    max: 850,
}];
const RES_29: &[CraftRes] = &[CraftRes {
    graphic: Graphic(0x1BF2),
    hue: Hue(0x0000),
    amount: 3,
    name: Text::Cliloc(1044036),
    message: Text::Cliloc(1044037),
    from_axis: true,
}];
const SKILLS_30: &[CraftSkillReq] = &[CraftSkillReq {
    skill: Skill::Tinkering,
    min: 250,
    max: 750,
}];
const RES_30: &[CraftRes] = &[CraftRes {
    graphic: Graphic(0x1BF2),
    hue: Hue(0x0000),
    amount: 1,
    name: Text::Cliloc(1044036),
    message: Text::Cliloc(1044037),
    from_axis: true,
}];
const SKILLS_31: &[CraftSkillReq] = &[CraftSkillReq {
    skill: Skill::Tinkering,
    min: 250,
    max: 750,
}];
const RES_31: &[CraftRes] = &[CraftRes {
    graphic: Graphic(0x1BF2),
    hue: Hue(0x0000),
    amount: 1,
    name: Text::Cliloc(1044036),
    message: Text::Cliloc(1044037),
    from_axis: true,
}];
const SKILLS_32: &[CraftSkillReq] = &[CraftSkillReq {
    skill: Skill::Tinkering,
    min: 500,
    max: 500,
}];
const RES_32: &[CraftRes] = &[CraftRes {
    graphic: Graphic(0x1BF2),
    hue: Hue(0x0000),
    amount: 4,
    name: Text::Cliloc(1044036),
    message: Text::Cliloc(1044037),
    from_axis: true,
}];
const SKILLS_33: &[CraftSkillReq] = &[CraftSkillReq {
    skill: Skill::Tinkering,
    min: 750,
    max: 1000,
}];
const RES_33: &[CraftRes] = &[
    CraftRes {
        graphic: Graphic(0x1BF2),
        hue: Hue(0x0000),
        amount: 4,
        name: Text::Cliloc(1044036),
        message: Text::Cliloc(1044037),
        from_axis: true,
    },
    CraftRes {
        graphic: Graphic(0x105D),
        hue: Hue(0x0000),
        amount: 1,
        name: Text::Cliloc(1044171),
        message: Text::Cliloc(1044253),
        from_axis: false,
    },
    CraftRes {
        graphic: Graphic(0x1053),
        hue: Hue(0x0000),
        amount: 2,
        name: Text::Cliloc(1044254),
        message: Text::Cliloc(1044253),
        from_axis: false,
    },
    CraftRes {
        graphic: Graphic(0x0F26),
        hue: Hue(0x0000),
        amount: 1,
        name: Text::Cliloc(1062608),
        message: Text::Cliloc(1044240),
        from_axis: false,
    },
];
const SKILLS_34: &[CraftSkillReq] = &[CraftSkillReq {
    skill: Skill::Tinkering,
    min: 400,
    max: 900,
}];
const RES_34: &[CraftRes] = &[CraftRes {
    graphic: Graphic(0x1BF2),
    hue: Hue(0x0000),
    amount: 4,
    name: Text::Cliloc(1044036),
    message: Text::Cliloc(1044037),
    from_axis: true,
}];
const SKILLS_35: &[CraftSkillReq] = &[CraftSkillReq {
    skill: Skill::Tinkering,
    min: 50,
    max: 550,
}];
const RES_35: &[CraftRes] = &[CraftRes {
    graphic: Graphic(0x1BF2),
    hue: Hue(0x0000),
    amount: 2,
    name: Text::Cliloc(1044036),
    message: Text::Cliloc(1044037),
    from_axis: true,
}];
const SKILLS_36: &[CraftSkillReq] = &[CraftSkillReq {
    skill: Skill::Tinkering,
    min: 250,
    max: 750,
}];
const RES_36: &[CraftRes] = &[CraftRes {
    graphic: Graphic(0x1BF2),
    hue: Hue(0x0000),
    amount: 1,
    name: Text::Cliloc(1044036),
    message: Text::Cliloc(1044037),
    from_axis: true,
}];
const SKILLS_37: &[CraftSkillReq] = &[CraftSkillReq {
    skill: Skill::Tinkering,
    min: 350,
    max: 850,
}];
const RES_37: &[CraftRes] = &[CraftRes {
    graphic: Graphic(0x1BF2),
    hue: Hue(0x0000),
    amount: 2,
    name: Text::Cliloc(1044036),
    message: Text::Cliloc(1044037),
    from_axis: true,
}];
const SKILLS_38: &[CraftSkillReq] = &[CraftSkillReq {
    skill: Skill::Tinkering,
    min: 50,
    max: 550,
}];
const RES_38: &[CraftRes] = &[CraftRes {
    graphic: Graphic(0x1BF2),
    hue: Hue(0x0000),
    amount: 2,
    name: Text::Cliloc(1044036),
    message: Text::Cliloc(1044037),
    from_axis: true,
}];
const SKILLS_39: &[CraftSkillReq] = &[CraftSkillReq {
    skill: Skill::Tinkering,
    min: 300,
    max: 800,
}];
const RES_39: &[CraftRes] = &[CraftRes {
    graphic: Graphic(0x1BF2),
    hue: Hue(0x0000),
    amount: 4,
    name: Text::Cliloc(1044036),
    message: Text::Cliloc(1044037),
    from_axis: true,
}];
const SKILLS_40: &[CraftSkillReq] = &[CraftSkillReq {
    skill: Skill::Tinkering,
    min: -150,
    max: 350,
}];
const RES_40: &[CraftRes] = &[CraftRes {
    graphic: Graphic(0x1BF2),
    hue: Hue(0x0000),
    amount: 5,
    name: Text::Cliloc(1044036),
    message: Text::Cliloc(1044037),
    from_axis: true,
}];
const SKILLS_41: &[CraftSkillReq] = &[CraftSkillReq {
    skill: Skill::Tinkering,
    min: 50,
    max: 550,
}];
const RES_41: &[CraftRes] = &[CraftRes {
    graphic: Graphic(0x1BF2),
    hue: Hue(0x0000),
    amount: 2,
    name: Text::Cliloc(1044036),
    message: Text::Cliloc(1044037),
    from_axis: true,
}];
const SKILLS_42: &[CraftSkillReq] = &[CraftSkillReq {
    skill: Skill::Tinkering,
    min: 450,
    max: 950,
}];
const RES_42: &[CraftRes] = &[CraftRes {
    graphic: Graphic(0x1BF2),
    hue: Hue(0x0000),
    amount: 10,
    name: Text::Cliloc(1044036),
    message: Text::Cliloc(1044037),
    from_axis: true,
}];
const SKILLS_43: &[CraftSkillReq] = &[CraftSkillReq {
    skill: Skill::Tinkering,
    min: 700,
    max: 1100,
}];
const RES_43: &[CraftRes] = &[
    CraftRes {
        graphic: Graphic(0x1BF2),
        hue: Hue(0x0000),
        amount: 2,
        name: Text::Cliloc(1044036),
        message: Text::Cliloc(1044037),
        from_axis: true,
    },
    CraftRes {
        graphic: Graphic(0x0F0F),
        hue: Hue(0x0000),
        amount: 1,
        name: Text::Cliloc(1044231),
        message: Text::Cliloc(1044253),
        from_axis: false,
    },
    CraftRes {
        graphic: Graphic(0x0F13),
        hue: Hue(0x0000),
        amount: 1,
        name: Text::Cliloc(1044234),
        message: Text::Cliloc(1044253),
        from_axis: false,
    },
];
const SKILLS_44: &[CraftSkillReq] = &[CraftSkillReq {
    skill: Skill::Tinkering,
    min: 250,
    max: 750,
}];
const RES_44: &[CraftRes] = &[CraftRes {
    graphic: Graphic(0x1BF2),
    hue: Hue(0x0000),
    amount: 2,
    name: Text::Cliloc(1044036),
    message: Text::Cliloc(1044037),
    from_axis: true,
}];
const SKILLS_45: &[CraftSkillReq] = &[CraftSkillReq {
    skill: Skill::Tinkering,
    min: 0,
    max: 500,
}];
const RES_45: &[CraftRes] = &[CraftRes {
    graphic: Graphic(0x1BF2),
    hue: Hue(0x0000),
    amount: 1,
    name: Text::Cliloc(1044036),
    message: Text::Cliloc(1044037),
    from_axis: true,
}];
const SKILLS_46: &[CraftSkillReq] = &[CraftSkillReq {
    skill: Skill::Tinkering,
    min: 0,
    max: 500,
}];
const RES_46: &[CraftRes] = &[CraftRes {
    graphic: Graphic(0x1BF2),
    hue: Hue(0x0000),
    amount: 1,
    name: Text::Cliloc(1044036),
    message: Text::Cliloc(1044037),
    from_axis: true,
}];
const SKILLS_47: &[CraftSkillReq] = &[CraftSkillReq {
    skill: Skill::Tinkering,
    min: 0,
    max: 500,
}];
const RES_47: &[CraftRes] = &[CraftRes {
    graphic: Graphic(0x1BF2),
    hue: Hue(0x0000),
    amount: 2,
    name: Text::Cliloc(1044036),
    message: Text::Cliloc(1044037),
    from_axis: true,
}];
const SKILLS_48: &[CraftSkillReq] = &[CraftSkillReq {
    skill: Skill::Tinkering,
    min: 0,
    max: 500,
}];
const RES_48: &[CraftRes] = &[CraftRes {
    graphic: Graphic(0x1BF2),
    hue: Hue(0x0000),
    amount: 1,
    name: Text::Cliloc(1044036),
    message: Text::Cliloc(1044037),
    from_axis: true,
}];
const SKILLS_49: &[CraftSkillReq] = &[CraftSkillReq {
    skill: Skill::Tinkering,
    min: 0,
    max: 500,
}];
const RES_49: &[CraftRes] = &[CraftRes {
    graphic: Graphic(0x1BF2),
    hue: Hue(0x0000),
    amount: 1,
    name: Text::Cliloc(1044036),
    message: Text::Cliloc(1044037),
    from_axis: true,
}];
const SKILLS_50: &[CraftSkillReq] = &[CraftSkillReq {
    skill: Skill::Tinkering,
    min: 200,
    max: 700,
}];
const RES_50: &[CraftRes] = &[CraftRes {
    graphic: Graphic(0x1BF2),
    hue: Hue(0x0000),
    amount: 3,
    name: Text::Cliloc(1044036),
    message: Text::Cliloc(1044037),
    from_axis: true,
}];
const SKILLS_51: &[CraftSkillReq] = &[CraftSkillReq {
    skill: Skill::Tinkering,
    min: 0,
    max: 500,
}];
const RES_51: &[CraftRes] = &[CraftRes {
    graphic: Graphic(0x1BF2),
    hue: Hue(0x0000),
    amount: 1,
    name: Text::Cliloc(1044036),
    message: Text::Cliloc(1044037),
    from_axis: true,
}];
const SKILLS_52: &[CraftSkillReq] = &[CraftSkillReq {
    skill: Skill::Tinkering,
    min: 0,
    max: 500,
}];
const RES_52: &[CraftRes] = &[CraftRes {
    graphic: Graphic(0x1BF2),
    hue: Hue(0x0000),
    amount: 1,
    name: Text::Cliloc(1044036),
    message: Text::Cliloc(1044037),
    from_axis: true,
}];
const SKILLS_53: &[CraftSkillReq] = &[CraftSkillReq {
    skill: Skill::Tinkering,
    min: 100,
    max: 600,
}];
const RES_53: &[CraftRes] = &[CraftRes {
    graphic: Graphic(0x1BF2),
    hue: Hue(0x0000),
    amount: 2,
    name: Text::Cliloc(1044036),
    message: Text::Cliloc(1044037),
    from_axis: true,
}];
const SKILLS_54: &[CraftSkillReq] = &[CraftSkillReq {
    skill: Skill::Tinkering,
    min: 100,
    max: 600,
}];
const RES_54: &[CraftRes] = &[CraftRes {
    graphic: Graphic(0x1BF2),
    hue: Hue(0x0000),
    amount: 2,
    name: Text::Cliloc(1044036),
    message: Text::Cliloc(1044037),
    from_axis: true,
}];
const SKILLS_55: &[CraftSkillReq] = &[CraftSkillReq {
    skill: Skill::Tinkering,
    min: 250,
    max: 750,
}];
const RES_55: &[CraftRes] = &[CraftRes {
    graphic: Graphic(0x1BF2),
    hue: Hue(0x0000),
    amount: 2,
    name: Text::Cliloc(1044036),
    message: Text::Cliloc(1044037),
    from_axis: true,
}];
const SKILLS_56: &[CraftSkillReq] = &[CraftSkillReq {
    skill: Skill::Tinkering,
    min: 100,
    max: 600,
}];
const RES_56: &[CraftRes] = &[CraftRes {
    graphic: Graphic(0x1BF2),
    hue: Hue(0x0000),
    amount: 2,
    name: Text::Cliloc(1044036),
    message: Text::Cliloc(1044037),
    from_axis: true,
}];
const SKILLS_57: &[CraftSkillReq] = &[CraftSkillReq {
    skill: Skill::Tinkering,
    min: 550,
    max: 1050,
}];
const RES_57: &[CraftRes] = &[CraftRes {
    graphic: Graphic(0x1BF2),
    hue: Hue(0x0000),
    amount: 4,
    name: Text::Cliloc(1044036),
    message: Text::Cliloc(1044037),
    from_axis: true,
}];
const SKILLS_58: &[CraftSkillReq] = &[CraftSkillReq {
    skill: Skill::Tinkering,
    min: 600,
    max: 1100,
}];
const RES_58: &[CraftRes] = &[CraftRes {
    graphic: Graphic(0x1BF2),
    hue: Hue(0x0000),
    amount: 4,
    name: Text::Cliloc(1044036),
    message: Text::Cliloc(1044037),
    from_axis: true,
}];
const SKILLS_59: &[CraftSkillReq] = &[CraftSkillReq {
    skill: Skill::Tinkering,
    min: 200,
    max: 700,
}];
const RES_59: &[CraftRes] = &[CraftRes {
    graphic: Graphic(0x1BF2),
    hue: Hue(0x0000),
    amount: 3,
    name: Text::Cliloc(1044036),
    message: Text::Cliloc(1044037),
    from_axis: true,
}];
const SKILLS_60: &[CraftSkillReq] = &[CraftSkillReq {
    skill: Skill::Tinkering,
    min: 550,
    max: 1050,
}];
const RES_60: &[CraftRes] = &[CraftRes {
    graphic: Graphic(0x1BF2),
    hue: Hue(0x0000),
    amount: 4,
    name: Text::Cliloc(1044036),
    message: Text::Cliloc(1044037),
    from_axis: true,
}];
const SKILLS_61: &[CraftSkillReq] = &[CraftSkillReq {
    skill: Skill::Tinkering,
    min: 600,
    max: 1100,
}];
const RES_61: &[CraftRes] = &[CraftRes {
    graphic: Graphic(0x1BF2),
    hue: Hue(0x0000),
    amount: 4,
    name: Text::Cliloc(1044036),
    message: Text::Cliloc(1044037),
    from_axis: true,
}];
const SKILLS_62: &[CraftSkillReq] = &[CraftSkillReq {
    skill: Skill::Tinkering,
    min: 300,
    max: 800,
}];
const RES_62: &[CraftRes] = &[CraftRes {
    graphic: Graphic(0x1BF2),
    hue: Hue(0x0000),
    amount: 2,
    name: Text::Cliloc(1044036),
    message: Text::Cliloc(1044037),
    from_axis: true,
}];
const SKILLS_63: &[CraftSkillReq] = &[CraftSkillReq {
    skill: Skill::Tinkering,
    min: 600,
    max: 1100,
}];
const RES_63: &[CraftRes] = &[CraftRes {
    graphic: Graphic(0x1BF2),
    hue: Hue(0x0000),
    amount: 4,
    name: Text::Cliloc(1044036),
    message: Text::Cliloc(1044037),
    from_axis: true,
}];
const SKILLS_64: &[CraftSkillReq] = &[CraftSkillReq {
    skill: Skill::Tinkering,
    min: 650,
    max: 1150,
}];
const RES_64: &[CraftRes] = &[
    CraftRes {
        graphic: Graphic(0x1BF2),
        hue: Hue(0x0000),
        amount: 10,
        name: Text::Cliloc(1044036),
        message: Text::Cliloc(1044037),
        from_axis: true,
    },
    CraftRes {
        graphic: Graphic(0x1BD7),
        hue: Hue(0x0000),
        amount: 5,
        name: Text::Cliloc(1044041),
        message: Text::Cliloc(1044351),
        from_axis: false,
    },
];
const SKILLS_65: &[CraftSkillReq] = &[CraftSkillReq {
    skill: Skill::Tinkering,
    min: 650,
    max: 1150,
}];
const RES_65: &[CraftRes] = &[
    CraftRes {
        graphic: Graphic(0x1BF2),
        hue: Hue(0x0000),
        amount: 10,
        name: Text::Cliloc(1044036),
        message: Text::Cliloc(1044037),
        from_axis: true,
    },
    CraftRes {
        graphic: Graphic(0x1BD7),
        hue: Hue(0x0000),
        amount: 5,
        name: Text::Cliloc(1044041),
        message: Text::Cliloc(1044351),
        from_axis: false,
    },
];
const SKILLS_66: &[CraftSkillReq] = &[CraftSkillReq {
    skill: Skill::Tinkering,
    min: 650,
    max: 1150,
}];
const RES_66: &[CraftRes] = &[
    CraftRes {
        graphic: Graphic(0x1BF2),
        hue: Hue(0x0000),
        amount: 10,
        name: Text::Cliloc(1044036),
        message: Text::Cliloc(1044037),
        from_axis: true,
    },
    CraftRes {
        graphic: Graphic(0x1BD7),
        hue: Hue(0x0000),
        amount: 5,
        name: Text::Cliloc(1044041),
        message: Text::Cliloc(1044351),
        from_axis: false,
    },
];
const SKILLS_67: &[CraftSkillReq] = &[CraftSkillReq {
    skill: Skill::Tinkering,
    min: 800,
    max: 1300,
}];
const RES_67: &[CraftRes] = &[CraftRes {
    graphic: Graphic(0x1BF2),
    hue: Hue(0x0000),
    amount: 15,
    name: Text::Cliloc(1044036),
    message: Text::Cliloc(1044037),
    from_axis: true,
}];
const SKILLS_68: &[CraftSkillReq] = &[CraftSkillReq {
    skill: Skill::Tinkering,
    min: 800,
    max: 1300,
}];
const RES_68: &[CraftRes] = &[CraftRes {
    graphic: Graphic(0x1BF2),
    hue: Hue(0x0000),
    amount: 15,
    name: Text::Cliloc(1044036),
    message: Text::Cliloc(1044037),
    from_axis: true,
}];
const SKILLS_69: &[CraftSkillReq] = &[CraftSkillReq {
    skill: Skill::Tinkering,
    min: 800,
    max: 1300,
}];
const RES_69: &[CraftRes] = &[
    CraftRes {
        graphic: Graphic(0x1BF2),
        hue: Hue(0x0000),
        amount: 20,
        name: Text::Cliloc(1044036),
        message: Text::Cliloc(1044037),
        from_axis: true,
    },
    CraftRes {
        graphic: Graphic(0x0F10),
        hue: Hue(0x0000),
        amount: 10,
        name: Text::Cliloc(1062601),
        message: Text::Cliloc(1044240),
        from_axis: false,
    },
    CraftRes {
        graphic: Graphic(0x0F13),
        hue: Hue(0x0000),
        amount: 10,
        name: Text::Cliloc(1062603),
        message: Text::Cliloc(1044240),
        from_axis: false,
    },
    CraftRes {
        graphic: Graphic(0x1879),
        hue: Hue(0x0000),
        amount: 1,
        name: Text::Cliloc(1026265),
        message: Text::Cliloc(1150700),
        from_axis: false,
    },
];
const SKILLS_70: &[CraftSkillReq] = &[CraftSkillReq {
    skill: Skill::Tinkering,
    min: 0,
    max: 0,
}];
const RES_70: &[CraftRes] = &[
    CraftRes {
        graphic: Graphic(0x105B),
        hue: Hue(0x0000),
        amount: 1,
        name: Text::Cliloc(1044169),
        message: Text::Cliloc(1044253),
        from_axis: false,
    },
    CraftRes {
        graphic: Graphic(0x1053),
        hue: Hue(0x0000),
        amount: 1,
        name: Text::Cliloc(1044254),
        message: Text::Cliloc(1044253),
        from_axis: false,
    },
];
const SKILLS_71: &[CraftSkillReq] = &[CraftSkillReq {
    skill: Skill::Tinkering,
    min: 0,
    max: 0,
}];
const RES_71: &[CraftRes] = &[
    CraftRes {
        graphic: Graphic(0x1051),
        hue: Hue(0x0000),
        amount: 1,
        name: Text::Cliloc(1044170),
        message: Text::Cliloc(1044253),
        from_axis: false,
    },
    CraftRes {
        graphic: Graphic(0x105D),
        hue: Hue(0x0000),
        amount: 1,
        name: Text::Cliloc(1044171),
        message: Text::Cliloc(1044253),
        from_axis: false,
    },
];
const SKILLS_72: &[CraftSkillReq] = &[CraftSkillReq {
    skill: Skill::Tinkering,
    min: 0,
    max: 0,
}];
const RES_72: &[CraftRes] = &[
    CraftRes {
        graphic: Graphic(0x1051),
        hue: Hue(0x0000),
        amount: 1,
        name: Text::Cliloc(1044170),
        message: Text::Cliloc(1044253),
        from_axis: false,
    },
    CraftRes {
        graphic: Graphic(0x1055),
        hue: Hue(0x0000),
        amount: 1,
        name: Text::Cliloc(1044172),
        message: Text::Cliloc(1044253),
        from_axis: false,
    },
];
const SKILLS_73: &[CraftSkillReq] = &[CraftSkillReq {
    skill: Skill::Tinkering,
    min: 0,
    max: 0,
}];
const RES_73: &[CraftRes] = &[
    CraftRes {
        graphic: Graphic(0x104D),
        hue: Hue(0x0000),
        amount: 1,
        name: Text::Cliloc(1044174),
        message: Text::Cliloc(1044253),
        from_axis: false,
    },
    CraftRes {
        graphic: Graphic(0x104F),
        hue: Hue(0x0000),
        amount: 1,
        name: Text::Cliloc(1044173),
        message: Text::Cliloc(1044253),
        from_axis: false,
    },
];
const SKILLS_74: &[CraftSkillReq] = &[CraftSkillReq {
    skill: Skill::Tinkering,
    min: 0,
    max: 0,
}];
const RES_74: &[CraftRes] = &[
    CraftRes {
        graphic: Graphic(0x104D),
        hue: Hue(0x0000),
        amount: 1,
        name: Text::Cliloc(1044174),
        message: Text::Cliloc(1044253),
        from_axis: false,
    },
    CraftRes {
        graphic: Graphic(0x104F),
        hue: Hue(0x0000),
        amount: 1,
        name: Text::Cliloc(1044173),
        message: Text::Cliloc(1044253),
        from_axis: false,
    },
];
const SKILLS_75: &[CraftSkillReq] = &[CraftSkillReq {
    skill: Skill::Tinkering,
    min: 0,
    max: 0,
}];
const RES_75: &[CraftRes] = &[CraftRes {
    graphic: Graphic(0x1059),
    hue: Hue(0x0000),
    amount: 1,
    name: Text::Cliloc(1044175),
    message: Text::Cliloc(1044253),
    from_axis: false,
}];
const SKILLS_76: &[CraftSkillReq] = &[CraftSkillReq {
    skill: Skill::Tinkering,
    min: 600,
    max: 800,
}];
const RES_76: &[CraftRes] = &[
    CraftRes {
        graphic: Graphic(0x0E73),
        hue: Hue(0x0000),
        amount: 4,
        name: Text::Cliloc(1046440),
        message: Text::Cliloc(1042613),
        from_axis: false,
    },
    CraftRes {
        graphic: Graphic(0x1081),
        hue: Hue(0x0000),
        amount: 3,
        name: Text::Cliloc(1044462),
        message: Text::Cliloc(1044463),
        from_axis: false,
    },
];
const SKILLS_77: &[CraftSkillReq] = &[CraftSkillReq {
    skill: Skill::Tinkering,
    min: 750,
    max: 1000,
}];
const RES_77: &[CraftRes] = &[
    CraftRes {
        graphic: Graphic(0x0E7F),
        hue: Hue(0x0000),
        amount: 1,
        name: Text::Cliloc(1044255),
        message: Text::Cliloc(1044253),
        from_axis: false,
    },
    CraftRes {
        graphic: Graphic(0x0F0E),
        hue: Hue(0x0000),
        amount: 10,
        name: Text::Cliloc(1044250),
        message: Text::Cliloc(1044253),
        from_axis: false,
    },
    CraftRes {
        graphic: Graphic(0x1DB8),
        hue: Hue(0x0000),
        amount: 1,
        name: Text::Cliloc(1044251),
        message: Text::Cliloc(1044253),
        from_axis: false,
    },
    CraftRes {
        graphic: Graphic(0x1004),
        hue: Hue(0x0000),
        amount: 1,
        name: Text::Cliloc(1044252),
        message: Text::Cliloc(1044253),
        from_axis: false,
    },
];
const SKILLS_78: &[CraftSkillReq] = &[
    CraftSkillReq {
        skill: Skill::Tinkering,
        min: 600,
        max: 1200,
    },
    CraftSkillReq {
        skill: Skill::AnimalLore,
        min: 150,
        max: 1000,
    },
];
const RES_78: &[CraftRes] = &[
    CraftRes {
        graphic: Graphic(0x14F8),
        hue: Hue(0x0000),
        amount: 1,
        name: Text::Cliloc(1020934),
        message: Text::Cliloc(1044253),
        from_axis: false,
    },
    CraftRes {
        graphic: Graphic(0x1374),
        hue: Hue(0x0000),
        amount: 1,
        name: Text::Cliloc(1074761),
        message: Text::Cliloc(1044253),
        from_axis: false,
    },
];
const SKILLS_79: &[CraftSkillReq] = &[CraftSkillReq {
    skill: Skill::Tinkering,
    min: 900,
    max: 1100,
}];
const RES_79: &[CraftRes] = &[
    CraftRes {
        graphic: Graphic(0x0E7F),
        hue: Hue(0x0000),
        amount: 2,
        name: Text::Cliloc(1150675),
        message: Text::Cliloc(1044253),
        from_axis: false,
    },
    CraftRes {
        graphic: Graphic(0x1849),
        hue: Hue(0x0000),
        amount: 4,
        name: Text::Cliloc(1011224),
        message: Text::Cliloc(1044253),
        from_axis: false,
    },
    CraftRes {
        graphic: Graphic(0x1879),
        hue: Hue(0x0000),
        amount: 1,
        name: Text::Cliloc(1026265),
        message: Text::Cliloc(1044253),
        from_axis: false,
    },
];
const SKILLS_80: &[CraftSkillReq] = &[CraftSkillReq {
    skill: Skill::Tinkering,
    min: 900,
    max: 1100,
}];
const RES_80: &[CraftRes] = &[
    CraftRes {
        graphic: Graphic(0x0E7F),
        hue: Hue(0x0000),
        amount: 2,
        name: Text::Cliloc(1150675),
        message: Text::Cliloc(1044253),
        from_axis: false,
    },
    CraftRes {
        graphic: Graphic(0x1849),
        hue: Hue(0x0000),
        amount: 4,
        name: Text::Cliloc(1011224),
        message: Text::Cliloc(1044253),
        from_axis: false,
    },
    CraftRes {
        graphic: Graphic(0x1879),
        hue: Hue(0x0000),
        amount: 1,
        name: Text::Cliloc(1026265),
        message: Text::Cliloc(1044253),
        from_axis: false,
    },
];
const SKILLS_81: &[CraftSkillReq] = &[CraftSkillReq {
    skill: Skill::Tinkering,
    min: 650,
    max: 1150,
}];
const RES_81: &[CraftRes] = &[
    CraftRes {
        graphic: Graphic(0x0EF0),
        hue: Hue(0x0000),
        amount: 250,
        name: Text::Cliloc(1044572),
        message: Text::Cliloc(1044253),
        from_axis: false,
    },
    CraftRes {
        graphic: Graphic(0x1BF2),
        hue: Hue(0x0000),
        amount: 10,
        name: Text::Cliloc(1044036),
        message: Text::Cliloc(1044037),
        from_axis: true,
    },
    CraftRes {
        graphic: Graphic(0x0F0A),
        hue: Hue(0x0000),
        amount: 1,
        name: Text::Cliloc(1044571),
        message: Text::Cliloc(1044253),
        from_axis: false,
    },
];
const SKILLS_82: &[CraftSkillReq] = &[CraftSkillReq {
    skill: Skill::Tinkering,
    min: 650,
    max: 1150,
}];
const RES_82: &[CraftRes] = &[
    CraftRes {
        graphic: Graphic(0x0EF0),
        hue: Hue(0x0000),
        amount: 250,
        name: Text::Cliloc(1044572),
        message: Text::Cliloc(1044253),
        from_axis: false,
    },
    CraftRes {
        graphic: Graphic(0x1BF2),
        hue: Hue(0x0000),
        amount: 10,
        name: Text::Cliloc(1044036),
        message: Text::Cliloc(1044037),
        from_axis: true,
    },
    CraftRes {
        graphic: Graphic(0x0F0D),
        hue: Hue(0x0000),
        amount: 1,
        name: Text::Cliloc(1044569),
        message: Text::Cliloc(1044253),
        from_axis: false,
    },
];
const SKILLS_83: &[CraftSkillReq] = &[CraftSkillReq {
    skill: Skill::Tinkering,
    min: 650,
    max: 1150,
}];
const RES_83: &[CraftRes] = &[
    CraftRes {
        graphic: Graphic(0x0EF0),
        hue: Hue(0x0000),
        amount: 250,
        name: Text::Cliloc(1044572),
        message: Text::Cliloc(1044253),
        from_axis: false,
    },
    CraftRes {
        graphic: Graphic(0x1BF2),
        hue: Hue(0x0000),
        amount: 10,
        name: Text::Cliloc(1044036),
        message: Text::Cliloc(1044037),
        from_axis: true,
    },
    CraftRes {
        graphic: Graphic(0x1053),
        hue: Hue(0x0000),
        amount: 1,
        name: Text::Cliloc(1044254),
        message: Text::Cliloc(1044253),
        from_axis: false,
    },
];
const SKILLS_84: &[CraftSkillReq] = &[CraftSkillReq {
    skill: Skill::Tinkering,
    min: 650,
    max: 1150,
}];
const RES_84: &[CraftRes] = &[
    CraftRes {
        graphic: Graphic(0x0EF0),
        hue: Hue(0x0000),
        amount: 250,
        name: Text::Cliloc(1044572),
        message: Text::Cliloc(1044253),
        from_axis: false,
    },
    CraftRes {
        graphic: Graphic(0x1BF2),
        hue: Hue(0x0000),
        amount: 10,
        name: Text::Cliloc(1044036),
        message: Text::Cliloc(1044037),
        from_axis: true,
    },
    CraftRes {
        graphic: Graphic(0x105D),
        hue: Hue(0x0000),
        amount: 1,
        name: Text::Cliloc(1044171),
        message: Text::Cliloc(1044253),
        from_axis: false,
    },
];
const SKILLS_85: &[CraftSkillReq] = &[CraftSkillReq {
    skill: Skill::Tinkering,
    min: 900,
    max: 1150,
}];
const RES_85: &[CraftRes] = &[
    CraftRes {
        graphic: Graphic(0x0EF0),
        hue: Hue(0x0000),
        amount: 500,
        name: Text::Cliloc(1044572),
        message: Text::Cliloc(1044253),
        from_axis: false,
    },
    CraftRes {
        graphic: Graphic(0x1BF2),
        hue: Hue(0x0000),
        amount: 10,
        name: Text::Cliloc(1044036),
        message: Text::Cliloc(1044037),
        from_axis: true,
    },
];
const SKILLS_86: &[CraftSkillReq] = &[CraftSkillReq {
    skill: Skill::Tinkering,
    min: 750,
    max: 1250,
}];
const RES_86: &[CraftRes] = &[
    CraftRes {
        graphic: Graphic(0x1BF2),
        hue: Hue(0x0000),
        amount: 5,
        name: Text::Cliloc(1044036),
        message: Text::Cliloc(1044037),
        from_axis: true,
    },
    CraftRes {
        graphic: Graphic(0x0F25),
        hue: Hue(0x0000),
        amount: 20,
        name: Text::Cliloc(1062607),
        message: Text::Cliloc(1044240),
        from_axis: false,
    },
    CraftRes {
        graphic: Graphic(0x3199),
        hue: Hue(0x0000),
        amount: 10,
        name: Text::Cliloc(1032697),
        message: Text::Cliloc(1044240),
        from_axis: false,
    },
];
const SKILLS_87: &[CraftSkillReq] = &[CraftSkillReq {
    skill: Skill::Tinkering,
    min: 750,
    max: 1250,
}];
const RES_87: &[CraftRes] = &[
    CraftRes {
        graphic: Graphic(0x1BF2),
        hue: Hue(0x0000),
        amount: 5,
        name: Text::Cliloc(1044036),
        message: Text::Cliloc(1044037),
        from_axis: true,
    },
    CraftRes {
        graphic: Graphic(0x0F13),
        hue: Hue(0x0000),
        amount: 20,
        name: Text::Cliloc(1062603),
        message: Text::Cliloc(1044240),
        from_axis: false,
    },
    CraftRes {
        graphic: Graphic(0x3197),
        hue: Hue(0x0000),
        amount: 10,
        name: Text::Cliloc(1032695),
        message: Text::Cliloc(1044240),
        from_axis: false,
    },
];
const SKILLS_88: &[CraftSkillReq] = &[CraftSkillReq {
    skill: Skill::Tinkering,
    min: 750,
    max: 1250,
}];
const RES_88: &[CraftRes] = &[
    CraftRes {
        graphic: Graphic(0x1BF2),
        hue: Hue(0x0000),
        amount: 5,
        name: Text::Cliloc(1044036),
        message: Text::Cliloc(1044037),
        from_axis: true,
    },
    CraftRes {
        graphic: Graphic(0x0F11),
        hue: Hue(0x0000),
        amount: 20,
        name: Text::Cliloc(1062602),
        message: Text::Cliloc(1044240),
        from_axis: false,
    },
    CraftRes {
        graphic: Graphic(0x3192),
        hue: Hue(0x0000),
        amount: 10,
        name: Text::Cliloc(1032690),
        message: Text::Cliloc(1044240),
        from_axis: false,
    },
];
const SKILLS_89: &[CraftSkillReq] = &[CraftSkillReq {
    skill: Skill::Tinkering,
    min: 750,
    max: 1250,
}];
const RES_89: &[CraftRes] = &[
    CraftRes {
        graphic: Graphic(0x1BF2),
        hue: Hue(0x0000),
        amount: 5,
        name: Text::Cliloc(1044036),
        message: Text::Cliloc(1044037),
        from_axis: true,
    },
    CraftRes {
        graphic: Graphic(0x0F18),
        hue: Hue(0x0000),
        amount: 20,
        name: Text::Cliloc(1062606),
        message: Text::Cliloc(1044240),
        from_axis: false,
    },
    CraftRes {
        graphic: Graphic(0x3196),
        hue: Hue(0x0000),
        amount: 10,
        name: Text::Cliloc(1032694),
        message: Text::Cliloc(1044240),
        from_axis: false,
    },
];
const SKILLS_90: &[CraftSkillReq] = &[CraftSkillReq {
    skill: Skill::Tinkering,
    min: 750,
    max: 1250,
}];
const RES_90: &[CraftRes] = &[
    CraftRes {
        graphic: Graphic(0x1BF2),
        hue: Hue(0x0000),
        amount: 5,
        name: Text::Cliloc(1044036),
        message: Text::Cliloc(1044037),
        from_axis: true,
    },
    CraftRes {
        graphic: Graphic(0x0F15),
        hue: Hue(0x0000),
        amount: 20,
        name: Text::Cliloc(1062604),
        message: Text::Cliloc(1044240),
        from_axis: false,
    },
    CraftRes {
        graphic: Graphic(0x3195),
        hue: Hue(0x0000),
        amount: 10,
        name: Text::Cliloc(1032693),
        message: Text::Cliloc(1044240),
        from_axis: false,
    },
];
const SKILLS_91: &[CraftSkillReq] = &[CraftSkillReq {
    skill: Skill::Tinkering,
    min: 750,
    max: 1250,
}];
const RES_91: &[CraftRes] = &[
    CraftRes {
        graphic: Graphic(0x1BF2),
        hue: Hue(0x0000),
        amount: 5,
        name: Text::Cliloc(1044036),
        message: Text::Cliloc(1044037),
        from_axis: true,
    },
    CraftRes {
        graphic: Graphic(0x0F26),
        hue: Hue(0x0000),
        amount: 20,
        name: Text::Cliloc(1062608),
        message: Text::Cliloc(1044240),
        from_axis: false,
    },
    CraftRes {
        graphic: Graphic(0x3198),
        hue: Hue(0x0000),
        amount: 10,
        name: Text::Cliloc(1032696),
        message: Text::Cliloc(1044240),
        from_axis: false,
    },
];
const SKILLS_92: &[CraftSkillReq] = &[CraftSkillReq {
    skill: Skill::Tinkering,
    min: 750,
    max: 1250,
}];
const RES_92: &[CraftRes] = &[
    CraftRes {
        graphic: Graphic(0x1BF2),
        hue: Hue(0x0000),
        amount: 5,
        name: Text::Cliloc(1044036),
        message: Text::Cliloc(1044037),
        from_axis: true,
    },
    CraftRes {
        graphic: Graphic(0x0F10),
        hue: Hue(0x0000),
        amount: 20,
        name: Text::Cliloc(1062601),
        message: Text::Cliloc(1044240),
        from_axis: false,
    },
    CraftRes {
        graphic: Graphic(0x3194),
        hue: Hue(0x0000),
        amount: 10,
        name: Text::Cliloc(1032692),
        message: Text::Cliloc(1044240),
        from_axis: false,
    },
];
const SKILLS_93: &[CraftSkillReq] = &[CraftSkillReq {
    skill: Skill::Tinkering,
    min: 750,
    max: 1250,
}];
const RES_93: &[CraftRes] = &[
    CraftRes {
        graphic: Graphic(0x1BF2),
        hue: Hue(0x0000),
        amount: 5,
        name: Text::Cliloc(1044036),
        message: Text::Cliloc(1044037),
        from_axis: true,
    },
    CraftRes {
        graphic: Graphic(0x0F16),
        hue: Hue(0x0000),
        amount: 20,
        name: Text::Cliloc(1062605),
        message: Text::Cliloc(1044240),
        from_axis: false,
    },
    CraftRes {
        graphic: Graphic(0x3193),
        hue: Hue(0x0000),
        amount: 10,
        name: Text::Cliloc(1032691),
        message: Text::Cliloc(1044240),
        from_axis: false,
    },
];

/// Everything this trade can make.
pub const RECIPES: &[Recipe] = &[
    Recipe {
        graphic: Graphic(0x108A),
        name: Text::Cliloc(1024234),
        group: 0,
        skills: SKILLS_0,
        resources: RES_0,
        amount: 1,
        hue: Hue(0x0000),
        use_all_res: false,
        min_skill_offset: 0,
        markable: true,
        never_exceptional: false,
        always_exceptional: false,
        needs: Needs::none(),
    },
    Recipe {
        graphic: Graphic(0x1086),
        name: Text::Cliloc(1024230),
        group: 0,
        skills: SKILLS_1,
        resources: RES_1,
        amount: 1,
        hue: Hue(0x0000),
        use_all_res: false,
        min_skill_offset: 0,
        markable: true,
        never_exceptional: false,
        always_exceptional: false,
        needs: Needs::none(),
    },
    Recipe {
        graphic: Graphic(0x27AE),
        name: Text::Cliloc(1030158),
        group: 1,
        skills: SKILLS_2,
        resources: RES_2,
        amount: 1,
        hue: Hue(0x0000),
        use_all_res: false,
        min_skill_offset: 0,
        markable: true,
        never_exceptional: false,
        always_exceptional: false,
        needs: Needs::none(),
    },
    Recipe {
        graphic: Graphic(0x1030),
        name: Text::Cliloc(1024144),
        group: 1,
        skills: SKILLS_3,
        resources: RES_3,
        amount: 1,
        hue: Hue(0x0000),
        use_all_res: false,
        min_skill_offset: 0,
        markable: true,
        never_exceptional: false,
        always_exceptional: false,
        needs: Needs::none(),
    },
    Recipe {
        graphic: Graphic(0x102C),
        name: Text::Cliloc(1024140),
        group: 1,
        skills: SKILLS_4,
        resources: RES_4,
        amount: 1,
        hue: Hue(0x0000),
        use_all_res: false,
        min_skill_offset: 0,
        markable: true,
        never_exceptional: false,
        always_exceptional: false,
        needs: Needs::none(),
    },
    Recipe {
        graphic: Graphic(0x1032),
        name: Text::Cliloc(1024146),
        group: 1,
        skills: SKILLS_5,
        resources: RES_5,
        amount: 1,
        hue: Hue(0x0000),
        use_all_res: false,
        min_skill_offset: 0,
        markable: true,
        never_exceptional: false,
        always_exceptional: false,
        needs: Needs::none(),
    },
    Recipe {
        graphic: Graphic(0x104D),
        name: Text::Cliloc(1024173),
        group: 1,
        skills: SKILLS_6,
        resources: RES_6,
        amount: 1,
        hue: Hue(0x0000),
        use_all_res: false,
        min_skill_offset: 0,
        markable: false,
        never_exceptional: false,
        always_exceptional: false,
        needs: Needs::none(),
    },
    Recipe {
        graphic: Graphic(0x105B),
        name: Text::Cliloc(1024187),
        group: 1,
        skills: SKILLS_7,
        resources: RES_7,
        amount: 1,
        hue: Hue(0x0000),
        use_all_res: false,
        min_skill_offset: 0,
        markable: false,
        never_exceptional: false,
        always_exceptional: false,
        needs: Needs::none(),
    },
    Recipe {
        graphic: Graphic(0x1043),
        name: Text::Cliloc(1024163),
        group: 1,
        skills: SKILLS_8,
        resources: RES_8,
        amount: 1,
        hue: Hue(0x0000),
        use_all_res: false,
        min_skill_offset: 0,
        markable: true,
        never_exceptional: false,
        always_exceptional: false,
        needs: Needs::none(),
    },
    Recipe {
        graphic: Graphic(0x0F9F),
        name: Text::Cliloc(1023998),
        group: 2,
        skills: SKILLS_9,
        resources: RES_9,
        amount: 1,
        hue: Hue(0x0000),
        use_all_res: false,
        min_skill_offset: 0,
        markable: false,
        never_exceptional: false,
        always_exceptional: false,
        needs: Needs::none(),
    },
    Recipe {
        graphic: Graphic(0x0E9B),
        name: Text::Cliloc(1023739),
        group: 2,
        skills: SKILLS_10,
        resources: RES_10,
        amount: 1,
        hue: Hue(0x0000),
        use_all_res: false,
        min_skill_offset: 0,
        markable: true,
        never_exceptional: false,
        always_exceptional: false,
        needs: Needs::none(),
    },
    Recipe {
        graphic: Graphic(0x10E7),
        name: Text::Cliloc(1024327),
        group: 2,
        skills: SKILLS_11,
        resources: RES_11,
        amount: 1,
        hue: Hue(0x0000),
        use_all_res: false,
        min_skill_offset: 0,
        markable: true,
        never_exceptional: false,
        always_exceptional: false,
        needs: Needs::none(),
    },
    Recipe {
        graphic: Graphic(0x1EB8),
        name: Text::Cliloc(1044164),
        group: 2,
        skills: SKILLS_12,
        resources: RES_12,
        amount: 1,
        hue: Hue(0x0000),
        use_all_res: false,
        min_skill_offset: 0,
        markable: true,
        never_exceptional: false,
        always_exceptional: false,
        needs: Needs::none(),
    },
    Recipe {
        graphic: Graphic(0x0F43),
        name: Text::Cliloc(1023907),
        group: 2,
        skills: SKILLS_13,
        resources: RES_13,
        amount: 1,
        hue: Hue(0x0000),
        use_all_res: false,
        min_skill_offset: 0,
        markable: true,
        never_exceptional: false,
        always_exceptional: false,
        needs: Needs::none(),
    },
    Recipe {
        graphic: Graphic(0x10E4),
        name: Text::Cliloc(1024324),
        group: 2,
        skills: SKILLS_14,
        resources: RES_14,
        amount: 1,
        hue: Hue(0x0000),
        use_all_res: false,
        min_skill_offset: 0,
        markable: true,
        never_exceptional: false,
        always_exceptional: false,
        needs: Needs::none(),
    },
    Recipe {
        graphic: Graphic(0x0F9D),
        name: Text::Cliloc(1023997),
        group: 2,
        skills: SKILLS_15,
        resources: RES_15,
        amount: 1,
        hue: Hue(0x0000),
        use_all_res: false,
        min_skill_offset: 0,
        markable: true,
        never_exceptional: false,
        always_exceptional: false,
        needs: Needs::none(),
    },
    Recipe {
        graphic: Graphic(0x1034),
        name: Text::Cliloc(1024148),
        group: 2,
        skills: SKILLS_16,
        resources: RES_16,
        amount: 1,
        hue: Hue(0x0000),
        use_all_res: false,
        min_skill_offset: 0,
        markable: true,
        never_exceptional: false,
        always_exceptional: false,
        needs: Needs::none(),
    },
    Recipe {
        graphic: Graphic(0x1028),
        name: Text::Cliloc(1024136),
        group: 2,
        skills: SKILLS_17,
        resources: RES_17,
        amount: 1,
        hue: Hue(0x0000),
        use_all_res: false,
        min_skill_offset: 0,
        markable: true,
        never_exceptional: false,
        always_exceptional: false,
        needs: Needs::none(),
    },
    Recipe {
        graphic: Graphic(0x10E5),
        name: Text::Cliloc(1024325),
        group: 2,
        skills: SKILLS_18,
        resources: RES_18,
        amount: 1,
        hue: Hue(0x0000),
        use_all_res: false,
        min_skill_offset: 0,
        markable: true,
        never_exceptional: false,
        always_exceptional: false,
        needs: Needs::none(),
    },
    Recipe {
        graphic: Graphic(0x0F39),
        name: Text::Cliloc(1023898),
        group: 2,
        skills: SKILLS_19,
        resources: RES_19,
        amount: 1,
        hue: Hue(0x0000),
        use_all_res: false,
        min_skill_offset: 0,
        markable: true,
        never_exceptional: false,
        always_exceptional: false,
        needs: Needs::none(),
    },
    Recipe {
        graphic: Graphic(0x102A),
        name: Text::Cliloc(1024138),
        group: 2,
        skills: SKILLS_20,
        resources: RES_20,
        amount: 1,
        hue: Hue(0x0000),
        use_all_res: false,
        min_skill_offset: 0,
        markable: true,
        never_exceptional: false,
        always_exceptional: false,
        needs: Needs::none(),
    },
    Recipe {
        graphic: Graphic(0x0FBB),
        name: Text::Cliloc(1024028),
        group: 2,
        skills: SKILLS_21,
        resources: RES_21,
        amount: 1,
        hue: Hue(0x0000),
        use_all_res: false,
        min_skill_offset: 0,
        markable: true,
        never_exceptional: false,
        always_exceptional: false,
        needs: Needs::none(),
    },
    Recipe {
        graphic: Graphic(0x13E3),
        name: Text::Cliloc(1025091),
        group: 2,
        skills: SKILLS_22,
        resources: RES_22,
        amount: 1,
        hue: Hue(0x0000),
        use_all_res: false,
        min_skill_offset: 0,
        markable: true,
        never_exceptional: false,
        always_exceptional: false,
        needs: Needs::none(),
    },
    Recipe {
        graphic: Graphic(0x0FB5),
        name: Text::Cliloc(1024021),
        group: 2,
        skills: SKILLS_23,
        resources: RES_23,
        amount: 1,
        hue: Hue(0x0000),
        use_all_res: false,
        min_skill_offset: 0,
        markable: true,
        never_exceptional: false,
        always_exceptional: false,
        needs: Needs::none(),
    },
    Recipe {
        graphic: Graphic(0x10E6),
        name: Text::Cliloc(1024326),
        group: 2,
        skills: SKILLS_24,
        resources: RES_24,
        amount: 1,
        hue: Hue(0x0000),
        use_all_res: false,
        min_skill_offset: 0,
        markable: true,
        never_exceptional: false,
        always_exceptional: false,
        needs: Needs::none(),
    },
    Recipe {
        graphic: Graphic(0x0E86),
        name: Text::Cliloc(1023718),
        group: 2,
        skills: SKILLS_25,
        resources: RES_25,
        amount: 1,
        hue: Hue(0x0000),
        use_all_res: false,
        min_skill_offset: 0,
        markable: true,
        never_exceptional: false,
        always_exceptional: false,
        needs: Needs::none(),
    },
    Recipe {
        graphic: Graphic(0x14FC),
        name: Text::Cliloc(1025371),
        group: 2,
        skills: SKILLS_26,
        resources: RES_26,
        amount: 1,
        hue: Hue(0x0000),
        use_all_res: false,
        min_skill_offset: 0,
        markable: false,
        never_exceptional: false,
        always_exceptional: false,
        needs: Needs::none(),
    },
    Recipe {
        graphic: Graphic(0x097F),
        name: Text::Cliloc(1044567),
        group: 2,
        skills: SKILLS_27,
        resources: RES_27,
        amount: 1,
        hue: Hue(0x0000),
        use_all_res: false,
        min_skill_offset: 0,
        markable: true,
        never_exceptional: false,
        always_exceptional: false,
        needs: Needs::none(),
    },
    Recipe {
        graphic: Graphic(0x103E),
        name: Text::Cliloc(1024158),
        group: 2,
        skills: SKILLS_28,
        resources: RES_28,
        amount: 1,
        hue: Hue(0x0000),
        use_all_res: false,
        min_skill_offset: 0,
        markable: true,
        never_exceptional: false,
        always_exceptional: false,
        needs: Needs::none(),
    },
    Recipe {
        graphic: Graphic(0x1022),
        name: Text::Cliloc(1044166),
        group: 2,
        skills: SKILLS_29,
        resources: RES_29,
        amount: 1,
        hue: Hue(0x0000),
        use_all_res: false,
        min_skill_offset: 0,
        markable: true,
        never_exceptional: false,
        always_exceptional: false,
        needs: Needs::none(),
    },
    Recipe {
        graphic: Graphic(0x0FBF),
        name: Text::Cliloc(1044167),
        group: 2,
        skills: SKILLS_30,
        resources: RES_30,
        amount: 1,
        hue: Hue(0x0000),
        use_all_res: false,
        min_skill_offset: 0,
        markable: true,
        never_exceptional: false,
        always_exceptional: false,
        needs: Needs::none(),
    },
    Recipe {
        graphic: Graphic(0x0FBF),
        name: Text::Cliloc(1044168),
        group: 2,
        skills: SKILLS_31,
        resources: RES_31,
        amount: 1,
        hue: Hue(0x0000),
        use_all_res: false,
        min_skill_offset: 0,
        markable: true,
        never_exceptional: false,
        always_exceptional: false,
        needs: Needs::none(),
    },
    Recipe {
        graphic: Graphic(0x0DFC),
        name: Text::Cliloc(1112117),
        group: 2,
        skills: SKILLS_32,
        resources: RES_32,
        amount: 1,
        hue: Hue(0x0000),
        use_all_res: false,
        min_skill_offset: 0,
        markable: true,
        never_exceptional: false,
        always_exceptional: false,
        needs: Needs::none(),
    },
    Recipe {
        graphic: Graphic(0x1EB8),
        name: Text::Cliloc(1072154),
        group: 2,
        skills: SKILLS_33,
        resources: RES_33,
        amount: 1,
        hue: Hue(0x0000),
        use_all_res: false,
        min_skill_offset: 0,
        markable: false,
        never_exceptional: false,
        always_exceptional: false,
        needs: Needs::none(),
    },
    Recipe {
        graphic: Graphic(0x0E87),
        name: Text::Cliloc(1023719),
        group: 2,
        skills: SKILLS_34,
        resources: RES_34,
        amount: 1,
        hue: Hue(0x0000),
        use_all_res: false,
        min_skill_offset: 0,
        markable: true,
        never_exceptional: false,
        always_exceptional: false,
        needs: Needs::none(),
    },
    Recipe {
        graphic: Graphic(0x1053),
        name: Text::Cliloc(1024179),
        group: 3,
        skills: SKILLS_35,
        resources: RES_35,
        amount: 1,
        hue: Hue(0x0000),
        use_all_res: false,
        min_skill_offset: 0,
        markable: false,
        never_exceptional: false,
        always_exceptional: false,
        needs: Needs::none(),
    },
    Recipe {
        graphic: Graphic(0x104F),
        name: Text::Cliloc(1024175),
        group: 3,
        skills: SKILLS_36,
        resources: RES_36,
        amount: 1,
        hue: Hue(0x0000),
        use_all_res: false,
        min_skill_offset: 0,
        markable: false,
        never_exceptional: false,
        always_exceptional: false,
        needs: Needs::none(),
    },
    Recipe {
        graphic: Graphic(0x1004),
        name: Text::Cliloc(1024100),
        group: 3,
        skills: SKILLS_37,
        resources: RES_37,
        amount: 1,
        hue: Hue(0x0000),
        use_all_res: false,
        min_skill_offset: 0,
        markable: false,
        never_exceptional: false,
        always_exceptional: false,
        needs: Needs::none(),
    },
    Recipe {
        graphic: Graphic(0x105D),
        name: Text::Cliloc(1024189),
        group: 3,
        skills: SKILLS_38,
        resources: RES_38,
        amount: 1,
        hue: Hue(0x0000),
        use_all_res: false,
        min_skill_offset: 0,
        markable: false,
        never_exceptional: false,
        always_exceptional: false,
        needs: Needs::none(),
    },
    Recipe {
        graphic: Graphic(0x1059),
        name: Text::Cliloc(1024185),
        group: 3,
        skills: SKILLS_39,
        resources: RES_39,
        amount: 1,
        hue: Hue(0x0000),
        use_all_res: false,
        min_skill_offset: 0,
        markable: false,
        never_exceptional: false,
        always_exceptional: false,
        needs: Needs::none(),
    },
    Recipe {
        graphic: Graphic(0x1DB7),
        name: Text::Cliloc(1024321),
        group: 3,
        skills: SKILLS_40,
        resources: RES_40,
        amount: 1,
        hue: Hue(0x0000),
        use_all_res: false,
        min_skill_offset: 0,
        markable: false,
        never_exceptional: false,
        always_exceptional: false,
        needs: Needs::none(),
    },
    Recipe {
        graphic: Graphic(0x1055),
        name: Text::Cliloc(1024181),
        group: 3,
        skills: SKILLS_41,
        resources: RES_41,
        amount: 1,
        hue: Hue(0x0000),
        use_all_res: false,
        min_skill_offset: 0,
        markable: false,
        never_exceptional: false,
        always_exceptional: false,
        needs: Needs::none(),
    },
    Recipe {
        graphic: Graphic(0x0E73),
        name: Text::Cliloc(1023699),
        group: 3,
        skills: SKILLS_42,
        resources: RES_42,
        amount: 1,
        hue: Hue(0x0000),
        use_all_res: false,
        min_skill_offset: 0,
        markable: false,
        never_exceptional: false,
        always_exceptional: false,
        needs: Needs::none(),
    },
    Recipe {
        graphic: Graphic(0x2F5E),
        name: Text::Cliloc(1072894),
        group: 3,
        skills: SKILLS_43,
        resources: RES_43,
        amount: 1,
        hue: Hue(0x0000),
        use_all_res: false,
        min_skill_offset: 0,
        markable: false,
        never_exceptional: false,
        always_exceptional: false,
        needs: Needs::none(),
    },
    Recipe {
        graphic: Graphic(0x13F6),
        name: Text::Cliloc(1025110),
        group: 4,
        skills: SKILLS_44,
        resources: RES_44,
        amount: 1,
        hue: Hue(0x0000),
        use_all_res: false,
        min_skill_offset: 0,
        markable: true,
        never_exceptional: false,
        always_exceptional: false,
        needs: Needs::none(),
    },
    Recipe {
        graphic: Graphic(0x09F8),
        name: Text::Cliloc(1044158),
        group: 4,
        skills: SKILLS_45,
        resources: RES_45,
        amount: 1,
        hue: Hue(0x0000),
        use_all_res: false,
        min_skill_offset: 0,
        markable: false,
        never_exceptional: false,
        always_exceptional: false,
        needs: Needs::none(),
    },
    Recipe {
        graphic: Graphic(0x09F9),
        name: Text::Cliloc(1044159),
        group: 4,
        skills: SKILLS_46,
        resources: RES_46,
        amount: 1,
        hue: Hue(0x0000),
        use_all_res: false,
        min_skill_offset: 0,
        markable: false,
        never_exceptional: false,
        always_exceptional: false,
        needs: Needs::none(),
    },
    Recipe {
        graphic: Graphic(0x09D7),
        name: Text::Cliloc(1022519),
        group: 4,
        skills: SKILLS_47,
        resources: RES_47,
        amount: 1,
        hue: Hue(0x0000),
        use_all_res: false,
        min_skill_offset: 0,
        markable: false,
        never_exceptional: false,
        always_exceptional: false,
        needs: Needs::none(),
    },
    Recipe {
        graphic: Graphic(0x09F4),
        name: Text::Cliloc(1044160),
        group: 4,
        skills: SKILLS_48,
        resources: RES_48,
        amount: 1,
        hue: Hue(0x0000),
        use_all_res: false,
        min_skill_offset: 0,
        markable: false,
        never_exceptional: false,
        always_exceptional: false,
        needs: Needs::none(),
    },
    Recipe {
        graphic: Graphic(0x09F5),
        name: Text::Cliloc(1044161),
        group: 4,
        skills: SKILLS_49,
        resources: RES_49,
        amount: 1,
        hue: Hue(0x0000),
        use_all_res: false,
        min_skill_offset: 0,
        markable: false,
        never_exceptional: false,
        always_exceptional: false,
        needs: Needs::none(),
    },
    Recipe {
        graphic: Graphic(0x0EC3),
        name: Text::Cliloc(1023778),
        group: 4,
        skills: SKILLS_50,
        resources: RES_50,
        amount: 1,
        hue: Hue(0x0000),
        use_all_res: false,
        min_skill_offset: 0,
        markable: true,
        never_exceptional: false,
        always_exceptional: false,
        needs: Needs::none(),
    },
    Recipe {
        graphic: Graphic(0x09F6),
        name: Text::Cliloc(1044162),
        group: 4,
        skills: SKILLS_51,
        resources: RES_51,
        amount: 1,
        hue: Hue(0x0000),
        use_all_res: false,
        min_skill_offset: 0,
        markable: false,
        never_exceptional: false,
        always_exceptional: false,
        needs: Needs::none(),
    },
    Recipe {
        graphic: Graphic(0x09F7),
        name: Text::Cliloc(1044163),
        group: 4,
        skills: SKILLS_52,
        resources: RES_52,
        amount: 1,
        hue: Hue(0x0000),
        use_all_res: false,
        min_skill_offset: 0,
        markable: false,
        never_exceptional: false,
        always_exceptional: false,
        needs: Needs::none(),
    },
    Recipe {
        graphic: Graphic(0x099A),
        name: Text::Cliloc(1022458),
        group: 4,
        skills: SKILLS_53,
        resources: RES_53,
        amount: 1,
        hue: Hue(0x0000),
        use_all_res: false,
        min_skill_offset: 0,
        markable: false,
        never_exceptional: false,
        always_exceptional: false,
        needs: Needs::none(),
    },
    Recipe {
        graphic: Graphic(0x0FFF),
        name: Text::Cliloc(1024097),
        group: 4,
        skills: SKILLS_54,
        resources: RES_54,
        amount: 1,
        hue: Hue(0x0000),
        use_all_res: false,
        min_skill_offset: 0,
        markable: false,
        never_exceptional: false,
        always_exceptional: false,
        needs: Needs::none(),
    },
    Recipe {
        graphic: Graphic(0x0EC4),
        name: Text::Cliloc(1023781),
        group: 4,
        skills: SKILLS_55,
        resources: RES_55,
        amount: 1,
        hue: Hue(0x0000),
        use_all_res: false,
        min_skill_offset: 0,
        markable: true,
        never_exceptional: false,
        always_exceptional: false,
        needs: Needs::none(),
    },
    Recipe {
        graphic: Graphic(0x1011),
        name: Text::Cliloc(1024113),
        group: 5,
        skills: SKILLS_56,
        resources: RES_56,
        amount: 1,
        hue: Hue(0x0000),
        use_all_res: false,
        min_skill_offset: 0,
        markable: false,
        never_exceptional: false,
        always_exceptional: false,
        needs: Needs::none(),
    },
    Recipe {
        graphic: Graphic(0x0A27),
        name: Text::Cliloc(1022599),
        group: 5,
        skills: SKILLS_57,
        resources: RES_57,
        amount: 1,
        hue: Hue(0x0000),
        use_all_res: false,
        min_skill_offset: 0,
        markable: false,
        never_exceptional: false,
        always_exceptional: false,
        needs: Needs::none(),
    },
    Recipe {
        graphic: Graphic(0x1852),
        name: Text::Cliloc(1026225),
        group: 5,
        skills: SKILLS_58,
        resources: RES_58,
        amount: 1,
        hue: Hue(0x0000),
        use_all_res: false,
        min_skill_offset: 0,
        markable: false,
        never_exceptional: false,
        always_exceptional: false,
        needs: Needs::none(),
    },
    Recipe {
        graphic: Graphic(0x1010),
        name: Text::Cliloc(1024112),
        group: 5,
        skills: SKILLS_59,
        resources: RES_59,
        amount: 1,
        hue: Hue(0x0000),
        use_all_res: false,
        min_skill_offset: 0,
        markable: false,
        never_exceptional: false,
        always_exceptional: false,
        needs: Needs::none(),
    },
    Recipe {
        graphic: Graphic(0x1047),
        name: Text::Cliloc(1024167),
        group: 5,
        skills: SKILLS_60,
        resources: RES_60,
        amount: 1,
        hue: Hue(0x0000),
        use_all_res: false,
        min_skill_offset: 0,
        markable: false,
        never_exceptional: false,
        always_exceptional: false,
        needs: Needs::none(),
    },
    Recipe {
        graphic: Graphic(0x14F5),
        name: Text::Cliloc(1025365),
        group: 5,
        skills: SKILLS_61,
        resources: RES_61,
        amount: 1,
        hue: Hue(0x0000),
        use_all_res: false,
        min_skill_offset: 0,
        markable: false,
        never_exceptional: false,
        always_exceptional: false,
        needs: Needs::none(),
    },
    Recipe {
        graphic: Graphic(0x0A25),
        name: Text::Cliloc(1022597),
        group: 5,
        skills: SKILLS_62,
        resources: RES_62,
        amount: 1,
        hue: Hue(0x0000),
        use_all_res: false,
        min_skill_offset: 0,
        markable: false,
        never_exceptional: false,
        always_exceptional: false,
        needs: Needs::none(),
    },
    Recipe {
        graphic: Graphic(0x1849),
        name: Text::Cliloc(1026217),
        group: 5,
        skills: SKILLS_63,
        resources: RES_63,
        amount: 1,
        hue: Hue(0x0000),
        use_all_res: false,
        min_skill_offset: 0,
        markable: false,
        never_exceptional: false,
        always_exceptional: false,
        needs: Needs::none(),
    },
    Recipe {
        graphic: Graphic(0x24BC),
        name: Text::Cliloc(1029404),
        group: 5,
        skills: SKILLS_64,
        resources: RES_64,
        amount: 1,
        hue: Hue(0x0000),
        use_all_res: false,
        min_skill_offset: 0,
        markable: false,
        never_exceptional: false,
        always_exceptional: false,
        needs: Needs::none(),
    },
    Recipe {
        graphic: Graphic(0x24BE),
        name: Text::Cliloc(1029406),
        group: 5,
        skills: SKILLS_65,
        resources: RES_65,
        amount: 1,
        hue: Hue(0x0000),
        use_all_res: false,
        min_skill_offset: 0,
        markable: false,
        never_exceptional: false,
        always_exceptional: false,
        needs: Needs::none(),
    },
    Recipe {
        graphic: Graphic(0x24CA),
        name: Text::Cliloc(1029418),
        group: 5,
        skills: SKILLS_66,
        resources: RES_66,
        amount: 1,
        hue: Hue(0x0000),
        use_all_res: false,
        min_skill_offset: 0,
        markable: false,
        never_exceptional: false,
        always_exceptional: false,
        needs: Needs::none(),
    },
    Recipe {
        graphic: Graphic(0x2832),
        name: Text::Cliloc(1030290),
        group: 5,
        skills: SKILLS_67,
        resources: RES_67,
        amount: 1,
        hue: Hue(0x0000),
        use_all_res: false,
        min_skill_offset: 0,
        markable: false,
        never_exceptional: false,
        always_exceptional: false,
        needs: Needs::none(),
    },
    Recipe {
        graphic: Graphic(0x2833),
        name: Text::Cliloc(1030291),
        group: 5,
        skills: SKILLS_68,
        resources: RES_68,
        amount: 1,
        hue: Hue(0x0000),
        use_all_res: false,
        min_skill_offset: 0,
        markable: false,
        never_exceptional: false,
        always_exceptional: false,
        needs: Needs::none(),
    },
    Recipe {
        graphic: Graphic(0x1ED0),
        name: Text::Cliloc(1153097),
        group: 5,
        skills: SKILLS_69,
        resources: RES_69,
        amount: 1,
        hue: Hue(0x0000),
        use_all_res: false,
        min_skill_offset: 0,
        markable: false,
        never_exceptional: false,
        always_exceptional: false,
        needs: Needs::none(),
    },
    Recipe {
        graphic: Graphic(0x1051),
        name: Text::Cliloc(1024177),
        group: 6,
        skills: SKILLS_70,
        resources: RES_70,
        amount: 1,
        hue: Hue(0x0000),
        use_all_res: false,
        min_skill_offset: 0,
        markable: false,
        never_exceptional: false,
        always_exceptional: false,
        needs: Needs::none(),
    },
    Recipe {
        graphic: Graphic(0x104F),
        name: Text::Cliloc(1024175),
        group: 6,
        skills: SKILLS_71,
        resources: RES_71,
        amount: 1,
        hue: Hue(0x0000),
        use_all_res: false,
        min_skill_offset: 0,
        markable: false,
        never_exceptional: false,
        always_exceptional: false,
        needs: Needs::none(),
    },
    Recipe {
        graphic: Graphic(0x1059),
        name: Text::Cliloc(1024185),
        group: 6,
        skills: SKILLS_72,
        resources: RES_72,
        amount: 1,
        hue: Hue(0x0000),
        use_all_res: false,
        min_skill_offset: 0,
        markable: false,
        never_exceptional: false,
        always_exceptional: false,
        needs: Needs::none(),
    },
    Recipe {
        graphic: Graphic(0x104B),
        name: Text::Cliloc(1044257),
        group: 6,
        skills: SKILLS_73,
        resources: RES_73,
        amount: 1,
        hue: Hue(0x0000),
        use_all_res: false,
        min_skill_offset: 0,
        markable: false,
        never_exceptional: false,
        always_exceptional: false,
        needs: Needs::none(),
    },
    Recipe {
        graphic: Graphic(0x104C),
        name: Text::Cliloc(1044256),
        group: 6,
        skills: SKILLS_74,
        resources: RES_74,
        amount: 1,
        hue: Hue(0x0000),
        use_all_res: false,
        min_skill_offset: 0,
        markable: false,
        never_exceptional: false,
        always_exceptional: false,
        needs: Needs::none(),
    },
    Recipe {
        graphic: Graphic(0x1058),
        name: Text::Cliloc(1024183),
        group: 6,
        skills: SKILLS_75,
        resources: RES_75,
        amount: 1,
        hue: Hue(0x0000),
        use_all_res: false,
        min_skill_offset: 0,
        markable: false,
        never_exceptional: false,
        always_exceptional: false,
        needs: Needs::none(),
    },
    Recipe {
        graphic: Graphic(0x26AC),
        name: Text::Cliloc(1046441),
        group: 6,
        skills: SKILLS_76,
        resources: RES_76,
        amount: 1,
        hue: Hue(0x0000),
        use_all_res: false,
        min_skill_offset: 0,
        markable: false,
        never_exceptional: false,
        always_exceptional: false,
        needs: Needs::none(),
    },
    Recipe {
        graphic: Graphic(0x1940),
        name: Text::Cliloc(1044258),
        group: 6,
        skills: SKILLS_77,
        resources: RES_77,
        amount: 1,
        hue: Hue(0x0000),
        use_all_res: false,
        min_skill_offset: 0,
        markable: false,
        never_exceptional: false,
        always_exceptional: false,
        needs: Needs::none(),
    },
    Recipe {
        graphic: Graphic(0x14F8),
        name: Text::Cliloc(1071124),
        group: 6,
        skills: SKILLS_78,
        resources: RES_78,
        amount: 1,
        hue: Hue(0x0000),
        use_all_res: false,
        min_skill_offset: 0,
        markable: false,
        never_exceptional: false,
        always_exceptional: false,
        needs: Needs::none(),
    },
    Recipe {
        graphic: Graphic(0x14F0),
        name: Text::Cliloc(1150663),
        group: 6,
        skills: SKILLS_79,
        resources: RES_79,
        amount: 1,
        hue: Hue(0x0000),
        use_all_res: false,
        min_skill_offset: 0,
        markable: false,
        never_exceptional: true,
        always_exceptional: false,
        needs: Needs::none(),
    },
    Recipe {
        graphic: Graphic(0x14F0),
        name: Text::Cliloc(1150664),
        group: 6,
        skills: SKILLS_80,
        resources: RES_80,
        amount: 1,
        hue: Hue(0x0000),
        use_all_res: false,
        min_skill_offset: 0,
        markable: false,
        never_exceptional: true,
        always_exceptional: false,
        needs: Needs::none(),
    },
    Recipe {
        graphic: Graphic(0x11AB),
        name: Text::Cliloc(1044598),
        group: 7,
        skills: SKILLS_81,
        resources: RES_81,
        amount: 1,
        hue: Hue(0x0000),
        use_all_res: false,
        min_skill_offset: 0,
        markable: false,
        never_exceptional: false,
        always_exceptional: false,
        needs: Needs::none(),
    },
    Recipe {
        graphic: Graphic(0x36D2),
        name: Text::Cliloc(1044599),
        group: 7,
        skills: SKILLS_82,
        resources: RES_82,
        amount: 1,
        hue: Hue(0x0000),
        use_all_res: false,
        min_skill_offset: 0,
        markable: false,
        never_exceptional: false,
        always_exceptional: false,
        needs: Needs::none(),
    },
    Recipe {
        graphic: Graphic(0x1107),
        name: Text::Cliloc(1044600),
        group: 7,
        skills: SKILLS_83,
        resources: RES_83,
        amount: 1,
        hue: Hue(0x0000),
        use_all_res: false,
        min_skill_offset: 0,
        markable: false,
        never_exceptional: false,
        always_exceptional: false,
        needs: Needs::none(),
    },
    Recipe {
        graphic: Graphic(0x11A5),
        name: Text::Cliloc(1044601),
        group: 7,
        skills: SKILLS_84,
        resources: RES_84,
        amount: 1,
        hue: Hue(0x0000),
        use_all_res: false,
        min_skill_offset: 0,
        markable: false,
        never_exceptional: false,
        always_exceptional: false,
        needs: Needs::none(),
    },
    Recipe {
        graphic: Graphic(0x1EBB),
        name: Text::Cliloc(1046445),
        group: 7,
        skills: SKILLS_85,
        resources: RES_85,
        amount: 1,
        hue: Hue(0x0000),
        use_all_res: false,
        min_skill_offset: 0,
        markable: false,
        never_exceptional: false,
        always_exceptional: false,
        needs: Needs::none(),
    },
    Recipe {
        graphic: Graphic(0x1086),
        name: Text::Cliloc(1073453),
        group: 8,
        skills: SKILLS_86,
        resources: RES_86,
        amount: 1,
        hue: Hue(0x0000),
        use_all_res: false,
        min_skill_offset: 0,
        markable: true,
        never_exceptional: false,
        always_exceptional: false,
        needs: Needs::none(),
    },
    Recipe {
        graphic: Graphic(0x1086),
        name: Text::Cliloc(1073454),
        group: 8,
        skills: SKILLS_87,
        resources: RES_87,
        amount: 1,
        hue: Hue(0x0000),
        use_all_res: false,
        min_skill_offset: 0,
        markable: true,
        never_exceptional: false,
        always_exceptional: false,
        needs: Needs::none(),
    },
    Recipe {
        graphic: Graphic(0x1086),
        name: Text::Cliloc(1073455),
        group: 8,
        skills: SKILLS_88,
        resources: RES_88,
        amount: 1,
        hue: Hue(0x0000),
        use_all_res: false,
        min_skill_offset: 0,
        markable: true,
        never_exceptional: false,
        always_exceptional: false,
        needs: Needs::none(),
    },
    Recipe {
        graphic: Graphic(0x1086),
        name: Text::Cliloc(1073456),
        group: 8,
        skills: SKILLS_89,
        resources: RES_89,
        amount: 1,
        hue: Hue(0x0000),
        use_all_res: false,
        min_skill_offset: 0,
        markable: true,
        never_exceptional: false,
        always_exceptional: false,
        needs: Needs::none(),
    },
    Recipe {
        graphic: Graphic(0x108A),
        name: Text::Cliloc(1073457),
        group: 8,
        skills: SKILLS_90,
        resources: RES_90,
        amount: 1,
        hue: Hue(0x0000),
        use_all_res: false,
        min_skill_offset: 0,
        markable: true,
        never_exceptional: false,
        always_exceptional: false,
        needs: Needs::none(),
    },
    Recipe {
        graphic: Graphic(0x108A),
        name: Text::Cliloc(1073458),
        group: 8,
        skills: SKILLS_91,
        resources: RES_91,
        amount: 1,
        hue: Hue(0x0000),
        use_all_res: false,
        min_skill_offset: 0,
        markable: true,
        never_exceptional: false,
        always_exceptional: false,
        needs: Needs::none(),
    },
    Recipe {
        graphic: Graphic(0x108A),
        name: Text::Cliloc(1073459),
        group: 8,
        skills: SKILLS_92,
        resources: RES_92,
        amount: 1,
        hue: Hue(0x0000),
        use_all_res: false,
        min_skill_offset: 0,
        markable: true,
        never_exceptional: false,
        always_exceptional: false,
        needs: Needs::none(),
    },
    Recipe {
        graphic: Graphic(0x108A),
        name: Text::Cliloc(1073460),
        group: 8,
        skills: SKILLS_93,
        resources: RES_93,
        amount: 1,
        hue: Hue(0x0000),
        use_all_res: false,
        min_skill_offset: 0,
        markable: true,
        never_exceptional: false,
        always_exceptional: false,
        needs: Needs::none(),
    },
];

/// The material this trade is worked in.
pub const SUB_RES: SubResAxis = SubResAxis {
    graphic: Graphic(0x1BF2),
    name: Text::Cliloc(1044022),
    entries: &[
        SubRes {
            hue: Hue(0x0000),
            name: Text::Cliloc(1044022),
            req_skill: 0,
            message: Text::Cliloc(1044267),
        },
        SubRes {
            hue: Hue(0x0973),
            name: Text::Cliloc(1044023),
            req_skill: 650,
            message: Text::Cliloc(1044268),
        },
        SubRes {
            hue: Hue(0x0966),
            name: Text::Cliloc(1044024),
            req_skill: 700,
            message: Text::Cliloc(1044268),
        },
        SubRes {
            hue: Hue(0x096D),
            name: Text::Cliloc(1044025),
            req_skill: 750,
            message: Text::Cliloc(1044268),
        },
        SubRes {
            hue: Hue(0x0972),
            name: Text::Cliloc(1044026),
            req_skill: 800,
            message: Text::Cliloc(1044268),
        },
        SubRes {
            hue: Hue(0x08A5),
            name: Text::Cliloc(1044027),
            req_skill: 850,
            message: Text::Cliloc(1044268),
        },
        SubRes {
            hue: Hue(0x0979),
            name: Text::Cliloc(1044028),
            req_skill: 900,
            message: Text::Cliloc(1044268),
        },
        SubRes {
            hue: Hue(0x089F),
            name: Text::Cliloc(1044029),
            req_skill: 950,
            message: Text::Cliloc(1044268),
        },
        SubRes {
            hue: Hue(0x08AB),
            name: Text::Cliloc(1044030),
            req_skill: 990,
            message: Text::Cliloc(1044268),
        },
    ],
};
