//! Turns `data/doors.json` into the table [`crate::doors`] looks a graphic up in.
//!
//! Thirteen numbers and thirteen names, out of the source and into a data file
//! for the reason every other table in this workspace moved: the shape a
//! content pack ships is a data file, a shard with a door of its own edits one
//! line, and a list of magic constants in the middle of a module about occlusion
//! reads as noise wherever it is put.
//!
//! What is emitted is a sorted array of `(base, name)`, so the lookup is a
//! binary search over thirteen entries rather than a match arm per family. The
//! order is this build's, not the file's: `doors.json` is written in the order
//! `Doors.cs` declares the classes, which is not sorted, and a lookup that
//! assumed it was would answer wrongly for exactly one family and nobody would
//! notice.

use std::fmt::Write as _;
use std::path::Path;

fn main() {
    let out_dir = std::env::var("OUT_DIR").expect("cargo sets OUT_DIR");
    println!("cargo:rerun-if-changed=build.rs");
    println!("cargo:rerun-if-changed=data");

    let path = Path::new("data").join("doors.json");
    let text = std::fs::read_to_string(&path).unwrap_or_else(|e| panic!("{}: {e}", path.display()));

    // Hand-parsed rather than with `serde_json`: this crate has no dependencies
    // of its own for a reason (see its `Cargo.toml`), and adding one to the
    // *build* graph to read thirteen pairs is a poor trade. The file is written
    // by hand and read by this, and the panics below are what keeps that pair
    // honest — a build that cannot read the table fails loudly rather than
    // emitting an empty one, which would silently turn every door back into a
    // wall.
    let mut families: Vec<(u16, String)> = Vec::new();
    for line in text.lines() {
        let line = line.trim();
        if !line.starts_with("{ \"base\"") {
            continue;
        }
        let base = field(line, "\"base\":")
            .parse::<u16>()
            .unwrap_or_else(|e| panic!("{}: base in {line:?}: {e}", path.display()));
        let name = field(line, "\"name\":").trim_matches('"').to_string();
        families.push((base, name));
    }
    assert!(
        families.len() >= 13,
        "{}: read {} families, which is fewer than the thirteen ServUO names",
        path.display(),
        families.len(),
    );
    families.sort_unstable();
    for pair in families.windows(2) {
        assert!(
            pair[0].0 + FAMILY as u16 <= pair[1].0,
            "{}: {} at {:#06X} runs into {} at {:#06X}",
            path.display(),
            pair[0].1,
            pair[0].0,
            pair[1].1,
            pair[1].0,
        );
    }

    let mut out = String::from("// @generated by build.rs from data/doors.json.\n\n");
    writeln!(
        out,
        "/// Every door family's first graphic — the shut leaf of facing 0 — with the\n\
         /// name ServUO gives the family, sorted by graphic so the lookup can bisect.\n\
         const FAMILIES: [(u16, &str); {}] = [",
        families.len()
    )
    .unwrap();
    for (base, name) in &families {
        writeln!(out, "    ({base:#06X}, {name:?}),").unwrap();
    }
    out.push_str("];\n");

    std::fs::write(Path::new(&out_dir).join("doors.rs"), out).expect("writing doors.rs");
}

/// How many graphics one family occupies: eight facings, shut and open.
const FAMILY: usize = 16;

/// The value after `key` on a one-line JSON object, up to the next comma or brace.
fn field<'a>(line: &'a str, key: &str) -> &'a str {
    let rest = line
        .split_once(key)
        .unwrap_or_else(|| panic!("no {key} in {line:?}"))
        .1;
    rest.split([',', '}']).next().expect("split yields one").trim()
}
